"""The water surface's WIND-DRIVEN wave field, as one importable builder.

WHAT THIS IS. The eight-octave wave field that M_WaterVoxel already ships, with
three things added and nothing rebuilt: the wind STEERS it, the wind SIZES it,
and it BREAKS where the bed comes up. The node it authors still returns one
evaluation of one field, so the pixel normal and the vertex displacement cannot
disagree about where a crest is -- that property is the reason the existing
field is a single Custom node and it is preserved exactly
(create_water_voxel_material.py:2530-2632, "ONE evaluation, two outputs").

WHY IT IS A MODULE AND NOT MORE LINES IN create_water_voxel_material.py. That
file is 2964 lines and is regenerated by an automated chain; the wave field is
the part most likely to be iterated on and the part most likely to be wanted by
a second surface later (M_Ocean's implicit plane is the obvious candidate -- it
is a different material authored by create_ocean_material.py and today it has
its own unrelated ripple). This is the pattern the project already uses twice:
sky_star_graph.py owns the one star lookup that M_NightSky and
M_SkyAtmosphereDome share, and terrain_material_common.py owns the one biome
graph that M_VoxelTerrain and M_VoxelClipmap share. Both module docstrings make
the same argument, which is worth restating because it is the whole reason:
TWO COPIES OF ONE DERIVATION DO NOT FAIL LOUDLY. They drift, and the result is
still sharp, still animated, still plausible, and wrong, with nothing in a frame
to say so.


=============================================================================
THE ARCHITECTURAL SPLIT THIS FILE SITS ON
=============================================================================

Fast waves are a SURFACE effect. Slow water-level change is a SIMULATION
effect. This file is entirely the first one and deliberately touches none of
the second.

THE NUMBERS BEHIND THAT, because it was put as a question and deserves an
answer with arithmetic in it rather than a preference:

  * A wind chop of 20 cm crest-to-trough is TWO VOXELS on a 10 cm grid. Driven
    through the cellular automaton it cannot be a wave, it can only be a
    two-step staircase that flips on and off -- and the CA's fill fraction is
    quantised again on top of that (vertex colour R is fill 0..255 remapped,
    create_water_voxel_material.py:14-18). The surface path has no such floor:
    World Position Offset moves a vertex by a float, and the shipped
    displacement is +/-2.1 cm, a FIFTH of a voxel. The effect being asked for is
    strictly below the simulation's resolution and strictly above the
    material's.
  * Driving it through the CA means touching every water cell every frame
    across 2,049 basins, to produce something no cell can represent.
  * The wave field is evaluated where it is seen -- on drawn water surface
    pixels and vertices, at the shading rate, and at zero cost for the whole
    submerged volume and for every basin off screen.

WHAT GENUINELY BELONGS IN THE SIM, AND THE HOOK FOR IT, since it came up in the
same breath and should not be lost: a slow, basin-wide change to the water LEVEL
-- tide, seiche, storm surge -- moves the waterline and wets new ground, and no
surface effect can do that. The clean hook is `SurfaceZUU`, the per-basin drawn
water surface (VoxelWaterSubsystem.h:486, :633). Everything downstream already
keys off it: the sheet's hole test (`HasMobilizedWaterInImplicitDisc(double
SurfaceZUU)`, :552) and the basin extent masks (:502-560) both take it as an
argument rather than reading a constant. A slow offset added at that one site
would move the drawn surface, the wet extents and the despawn masks together.
NOT DONE HERE and not designed here -- flagged because the site is unusually
clean and somebody will want it.

That hook is also the reason this file does NOT try to fake a tide by lifting
the wave field's mean: the extents would not follow, so the lake would grow a
lip standing proud of its own shoreline.


=============================================================================
THE WIND INTERFACE -- WHAT THIS FILE NEEDS FROM THE WEATHER SUBSYSTEM
=============================================================================

TWO MPC_VoxelSky PARAMETERS, and the shapes are chosen so that they cannot be
inconsistent with each other:

  WindVectorMS  (vector)  R = wind velocity along world +X, metres per second
                          G = wind velocity along world +Y, metres per second
                          B = reserved for a gust factor (unread today)
                          A = unused
                          Default (0,0,0,0) = dead calm.

  WindFieldValid (scalar) 1 once the weather field has published this run, 0
                          otherwise. Default 0.

ONE VECTOR, NOT A DIRECTION AND A SPEED. Direction and speed as two parameters
can disagree -- a unit vector left stale next to a speed that moved is a wind
that blows the wrong way, and nothing in a frame reports it. A velocity vector
cannot be inconsistent with itself, and it makes "calm" exactly one value
(zero) rather than a special case someone has to remember to write. The
material recovers speed as `length()` and direction as the normalised vector,
which is three instructions.

DIRECTION SENSE, STATED EXPLICITLY BECAUSE METEOROLOGY AND VECTORS DISAGREE ON
IT AND THIS IS THE CLASSIC 180-DEGREE BUG: WindVectorMS is a VELOCITY. It
points where the air is GOING. A "northerly" in the forecast sense blows FROM
the north, so in this world's frame (VoxelEphemeris.h:44-48 fixes X = north,
Y = east, Z = up) a 6 m/s northerly is WindVectorMS = (-6, 0, 0, 0). Waves in
this file travel along +WindVectorMS.

SPEED REFERENCE HEIGHT: the standard 10 m (U10). Every fetch/growth relation
quoted below is written for U10 and the defaults were calibrated against it. If
the weather field publishes a surface-level or a boundary-layer wind instead,
say so and the calibration moves -- it does not silently absorb.

WHY MPC_VoxelSky AND NOT A NEW COLLECTION. The far-field lake sheet
deliberately has no dynamic material instance (VoxelWaterSheetActor.h:47-52),
so an MPC is the only CPU->material channel that reaches both water draw paths.
This material already binds six parameters on that collection (SunDirection,
MoonDirection, MoonLightFraction and the three bathymetry ones); a seventh costs
nothing and keeps the "one collection, one author" rule that
create_sky_material.py enforces by deleting and recreating the asset every run.
A SECOND collection would be a second thing that can be regenerated out from
under a dependent, which is a failure this project has already paid for once
(2026-08-10, every dependent binding compiling to the ENGINE DEFAULT MATERIAL
while the log said success -- create_water_voxel_material.py:460-465).

IT RUNS TODAY WITHOUT ANY OF THAT. `build_wind_input` reads the collection's
parameter list back and, if the two names are absent, silently drops to two
MATERIAL parameters (WindFallbackSpeedMS, WindFallbackDirDeg) whose defaults
reproduce the shipped look. This is deliberate and it is not laziness: the two
halves of this feature are being built by two people at once, and a wave module
that cannot be generated until the weather subsystem lands is a module that
gets tested for the first time on the day both land. The fallback is also the
runtime path whenever WindFieldValid is 0, so a session with the weather
subsystem disabled gets today's lake rather than a glassy one.


=============================================================================
THE MODEL
=============================================================================

WIND SIZES THE WAVES: FETCH-LIMITED, NOT FULLY DEVELOPED. This matters and it
is the one place where reaching for the famous formula gives the wrong answer
by an order of magnitude.

The Pierson-Moskowitz relations everyone quotes describe a FULLY DEVELOPED sea
-- open ocean, wind blowing over unlimited water for long enough to saturate.
They give, at 5 m/s, a significant wave height of 0.61 m and a peak wavelength
of 20.8 m. On a 500 m lake that is absurd: it is a wave taller than the shallows
and longer than a tenth of the basin.

The right family is the fetch-limited JONSWAP set (Hasselmann et al. 1973),
which adds the distance the wind has blown over water:

    H_s   = 1.6e-3 * U * sqrt(F / g)                 significant wave height
    f_p   = 3.5 * (g / U) * (g F / U^2)^(-0.33)      peak frequency
    lam_p = g / (2 pi f_p^2)                         deep-water wavelength

At U = 5 m/s over F = 500 m of fetch: H_s = 5.7 cm and lam_p = 1.1 m. THAT is a
lake, and 5.7 cm is within spitting distance of the 7.6 cm maximum height the
shipped field was independently tuned by eye to produce. The tuning was right;
this file is only giving it a handle.

WHAT IS ACTUALLY IMPLEMENTED IS THE EXPONENTS, NOT THE FORMULAE, and the reason
is that fetch is not available in the material. It would be: a lake's fetch in
the wind direction is a distance-to-shore query along a ray, and the baked
bathymetry has a distance-to-shore field -- but it is the distance to the
NEAREST shore, not the distance upwind, and a ray march per pixel to get the
right one is not affordable. So fetch is folded into the calibration constant
and only the SCALING with wind speed is kept:

    at fixed fetch,  H   proportional to U^1.00      (from H_s above)
                     lam proportional to U^0.68      (f_p ~ U^-0.34, lam ~ f^-2)

Both are exposed (WindAmpExponent, WindLenExponent) and both are quoted against
a reference speed, so "wind of WindRefSpeedMS reproduces the field that is
shipped today" is true by construction and is the calibration constant. Set the
reference to 5 m/s (the default) and the exponents describe how a lake behaves
either side of a moderate breeze.

Both are exact-1.0 multipliers at U = WindRefSpeedMS, which is what makes the
regression check below possible.

THE WAVES ALSO MOVE FASTER IN MORE WIND, AND IT IS FREE. Deep-water gravity
waves obey omega = sqrt(g k), so a longer wave oscillates more slowly but its
crests travel faster: c = omega/k grows as sqrt(lambda). The base octave's
angular frequency is therefore scaled by sqrt(BaseWavelengthM / lambda0), which
is 1.0 at the reference speed and about 1.3 at a 20 m/s storm. The per-octave
time multiplier progression (1.07) is UNCHANGED and is deliberately NOT the
dispersion-correct 1.19 -- it is what the shipped field looks like, and
switching to true dispersion is a look change that should be made on its own
and judged on a capture, not smuggled in under a wind feature.


WIND STEERS THE WAVES: A CONE, NOT A LINE, AND NOT A CIRCLE.

The shipped field spreads its eight octaves over the WHOLE circle with a
golden-angle increment (137.507764 deg). That was the correct fix for the
problem it was solving -- a corduroy lake with every wavefront on a world axis
-- but as a description of a wind sea it is wrong in a specific way: it is a
CONFUSED sea, with as much energy travelling upwind as downwind. Real wind seas
are directionally spread AROUND the wind vector, and the spread is narrow at the
spectral peak and broad in the high-frequency tail (Mitsuyasu's cos^2s model,
with the spreading exponent s largest at the peak). That is a fact worth using
rather than a detail: it means the LONG, HEAVY octaves line up with the wind and
the short ones fan out, which is exactly what makes a windy lake look like
long streaks with fine texture scribbled across them.

So octave i is placed at

    angle_i = baseAngle + lerp(i * DirIncrementDeg,
                               WindSpreadDeg * SPREAD_SHAPE[i],
                               WindDirectionAuthority)

with SPREAD_SHAPE a fixed eight-element sequence, generated once in
`octave_spread_shape()` and injected into the HLSL from there so the Python and
the shader cannot hold two different tables. Its two properties:

  * A GOLDEN-RATIO LOW-DISCREPANCY SEQUENCE mapped to [-1, +1], so the eight
    directions cover the cone evenly without any two being equal and without a
    pattern that repeats. Sampled as frac((i + 0.5) * phi) rather than
    frac(i * phi) specifically so that NO octave gets an offset of exactly zero
    -- an octave sitting precisely on the wind axis is the one direction the
    whole set should not contain, for the same reason WaveDirBaseDeg is not 0
    (create_water_voxel_material.py:2431-2452).
  * A WIDTH THAT GROWS WITH OCTAVE INDEX, 0.5x at the longest octave to 1.5x at
    the shortest. This is the Mitsuyasu behaviour above, and it is also the
    insurance against the failure mode this change could introduce: eight nearly
    parallel octaves is corduroy again. At the default WindSpreadDeg = 35 the
    eight offsets are

        -6.7, +19.2, +2.5, -21.9, +21.1, -8.6, -45.9, +14.2  degrees

    i.e. the peak octave is within 7 degrees of the wind and the tail reaches
    46 degrees off it.

WindDirectionAuthority is the blend between the old whole-circle placement (0)
and the wind cone (1), and it exists for exactly one reason: at 0 this module
reproduces the shipped field. See THE REGRESSION RECIPE below.

THE BASE ANGLE IS BLENDED WITH ITS WRAP REMOVED. `dA -= 2pi * round(dA / 2pi)`
before the lerp, so a wind rotating through the 359 -> 1 degree boundary does
not swing the whole field the long way round at intermediate authorities. At
authority 0 or 1 the term is unreachable; it is one instruction and it removes
a class of bug that would only appear on a slowly-turning wind.

AND THE ANGLE NAMES THE WAVEFRONT'S UPWIND NORMAL, NOT THE TRAVEL DIRECTION.
This is a convention inherited from the shipped loop, kept because changing it
would break bit-exact reproduction, and it is written down here because it is
the kind of thing that gets "fixed" into a 180-degree error. In
`x = dot(d, pos) * freq + T * tmul`, a crest sits where x is constant, so as T
grows `dot(d, pos)` must fall: THE WAVE TRAVELS ALONG -d. The wind target angle
is therefore the wind bearing plus 180 degrees, applied as `atan2(-w.x, -w.y)`,
which puts the travel direction on +w -- downwind, where it belongs.


CALM AND CHOPPY PATCHES: ALREADY THERE, NOW BLOWN DOWNWIND. The shipped field
already multiplies everything by a very-low-frequency amplitude field (two
diagonal sines at ~180 m and ~232 m, non-commensurate with each other and with
every octave -- create_water_voxel_material.py:2520-2528). That requirement is
met by code that exists, so it is kept verbatim rather than replaced, and one
thing is added: the patch field is now advected by the wind, so gust cells drift
downwind instead of sitting still and merely breathing. Cost is one multiply-add
on the sample position. WindPatchDriftFrac defaults to 0.5 -- real gust cells
travel at close to the mean wind, but at 1.0 a 10 m/s wind sweeps the whole
patch structure past a fixed viewpoint in about 20 seconds, which reads as the
lake sliding rather than as the wind gusting.


=============================================================================
BREAKING, AND WHY IT SHARES ONE NUMBER WITH THE SHORE DAMPING
=============================================================================

THE CRITERION. A wave breaks when the water gets shallow enough relative to its
own height. The classic solitary-wave result (McCowan) is a breaker index
H/d = 0.78 at the break point, i.e. it breaks once the depth falls below
1.28 * H. That ratio is the default (BreakDepthRatio = 1.28) and it is the whole
criterion; nothing here integrates a shoaling wave properly, and nothing needs
to.

THE COLLISION WITH THE EXISTING SHORE DAMPING, AND TWO WRONG ANSWERS BEFORE THE
RIGHT ONE. Both wrong answers were caught by the offline probe rather than by
reasoning, which is the only reason this section is short.

The material already damps wave amplitude to zero as the bed comes up -- a
linear ramp over the first BathyWaveDampDepthM = 0.6 m of depth
(create_water_voxel_material.py:2596-2617). The break depth for the SHIPPED wave
is 1.28 * 6.0 cm = 7.7 cm. So the two numbers are not merely in tension, they
are a factor of EIGHT apart, and the damping wins: a wave arrives at the depth
where it ought to break with 16% of its height left. There is almost nothing
there to break.

WRONG ANSWER 1: collapse them into ONE band, `dSurf = max(1.28*H_s, 0.6)`, with
breaking as the exact complement of the damping. Elegant, and wrong twice. At
ordinary wave heights that band is set by the 0.6 m floor rather than by the
breaker, so it foams the WHOLE 0.6 m band whenever there is any wave at all --
measured, a 3 m/s breeze foamed out to 46 cm of depth, which is the permanent
white ring the gates below exist to prevent. And it foams water the wave is not
breaking in: being damped and being broken are different things.

WRONG ANSWER 2: nest them, `dBreak = 1.28*H_s` inside `dSurf = max(dBreak, 0.6)`,
and drive the foam off the inner band only. That fixes the ring -- foam appears
only in the last 9.8 cm of depth at 5 m/s -- and it leaves the original defect
completely untouched. Measured on a 2-D shore at four phases, peak crest height
inside the foamed region:

                        5 m/s     12 m/s
    dSurf floored 0.6   1.22 cm   5.62 cm     amplitude at the break line 16% / 47%
    dSurf floored 0.15  4.88 cm  12.95 cm     amplitude at the break line 65% / 100%

A correct-looking foam mask over water with a quarter of its wave in it.

AND A CORRECTION TO HOW THAT WAS FIRST WRITTEN DOWN, because the first version of
this comment recorded the defect as "the peaking term measures +0%", which is
false and was an artefact of the probe (see the note at the end of this section).
The peaking RATIO is amplitude-independent -- it is a shape function, and it
measures x1.70 at 5 m/s under BOTH configurations. What the floored band destroys
is the ABSOLUTE crest, four-fold. The conclusion did not change; the evidence for
it did, and quoting the wrong quantity would have sent the next person looking at
the peaking maths instead of at the band width.

THE ANSWER IS THAT THE DAMPING BAND WAS THE WRONG SIZE, not that the breaking
needed a different band. A real surf zone runs FROM the break point TO the
waterline; the wave keeps its height until it breaks and then dissipates. So the
two bands are the same band:

    dBreak = BreakDepthRatio * H_s               the wave breaks here
    dSurf  = max(dBreak, BreakSurfFloorM)        the wave dies over this

    shore damping = saturate(depth / dSurf)      1 offshore, 0 at the waterline
    breaking      = 1 - saturate(depth / dBreak)

and BreakSurfFloorM (0.15 m, 1.5 voxels) is a floor for tiny waves only, so that
a near-flat lake still fades in rather than stopping dead at the shoreline.
Above about 12 cm of wave the two coincide exactly and the breaking is the
literal complement of the damping.

THE BAND IS PROPORTIONAL TO THE WAVE, AND THAT IS WHAT MAKES IT BEHAVE AT BOTH
ENDS. At zero wind H_s is exactly 0, dBreak is 0, and there is no surf zone at
all -- calm water laps a shore silently, with no ring. At 20 m/s, H_s is 24 cm
and the surf reaches 31 cm of depth, which on a 1-in-20 beach is a six-metre
band of white. THE SURF ZONE WIDENS WITH THE WIND, free.

AND IT HANDS BACK A GUARANTEE THAT USED TO BE A GUESS. Inside the surf zone a
linear ramp on a wave-proportional band makes the wave DEPTH-LIMITED at any wind
speed -- H(d) is proportional to d with a coefficient near 1, which is exactly
what a real surf zone does and is why a beach looks the same in a gale as in a
breeze except wider. Measured over a 0.8 m -> 0 m shore at four phases, crest
height as a fraction of local depth:

              U = 2 m/s   5 m/s   10 m/s   20 m/s
    p99          0.17     0.50     0.75     0.75
    max          0.28     0.75     1.22     1.22
    GEOMETRY     0.07     0.19     0.30     0.30    (the 0.25 WPO fraction)

so the VERTEX DISPLACEMENT never exceeds about a third of the water it is
standing in, at any wind speed, and it stops growing above 10 m/s because the
depth limit has taken over. That is the concern that pinned WaveWpoFraction at
0.25 in the first place (create_water_voxel_material.py:2385-2398, "no
shore-damping term to stop a rising crest clipping through its own bank"),
answered with a bound instead of a small number. The fraction could now be
raised on evidence; it is NOT raised here, because that is a look change and the
owner judges those from captures.

The shading field's rarest crests do exceed the local depth (max 1.22 at
10 m/s). That is a normal and a colour, not geometry -- it cannot clip anything
-- and it is left alone rather than clamped, because clamping it would flatten
exactly the crests a breaking wave is supposed to have.

HOW ALL OF THE ABOVE IS MEASURED, AND THE ONE THAT WAS MEASURED WRONG. The
offline probe originally sampled the shore as a single 1-D LINE -- 601 points,
depth 3 m -> 0 across 30 m, y fixed. At 12 m/s that puts the entire surf zone in
54 samples spanning 2.70 m of x, which is 0.30 of ONE 9.07 m wavelength: a third
of a wave, at whatever phase the line happened to cross. The mask it then applied
(`breaking > 0.2`) selects the samples nearest the WATERLINE, where the swash
term takes foam to 1 whatever the crest is doing -- and in that particular strip
every one of them was trough, H from -1.34 to -0.00 cm. So it computed "crest
amplification" over a set containing no crests and printed x1.00, i.e. it
reported a working effect as doing nothing. The fifteen samples that DID carry a
crest sat further out where breaking is 0.000..0.076, below the mask.

THE FIX WAS PHASES, NOT RESOLUTION. A 2-D shore -- 16 m across x by 40 m along y
at 320x800, four times -- samples every depth at ~800 phases instead of one, and
the same module then measures +9 to +11% crest and x1.50..x1.83 gradient. A
1-D transect through a 2-D random field cannot resolve a phase-conditioned
statistic however finely it is sampled, and the failure is silent: it returns a
plausible small number rather than an error.

THE COST OF THIS, STATED PLAINLY: waves now reach the shore, where before they
faded out 60 cm deep. That is the feature, and it is a VISIBLE change to shipped
behaviour rather than a pure addition. The regression recipe sets
BreakSurfFloorM back to 0.6 and restores the old damping exactly.

THREE GATES ON THE FOAM, because a permanent white ring around a still lake is
the single most recognisable tell of a tutorial water shader and this file is
one line away from drawing one (the same discipline, and the same sentence, as
the shoreline foam already in the material at
create_water_voxel_material.py:1288-1296):

  1. SIZE. `saturate(H_s / BreakMinWaveHeightM)`, default 5 cm. An absolute
     floor underneath the proportional band above -- belt and braces, and it is
     the gate that survives if somebody later gives dBreak a floor of its own.
  2. CREST. Foam appears on the CRESTS of the field, not uniformly across the
     band: `saturate((h / peak - BreakCrestThreshold) / (1 - ...))`. Because the
     crests travel, the foam travels with them, which is what makes it read as
     surf rather than as a painted stripe. The threshold relaxes to zero at the
     waterline (`lerp(crest, 1, band)`) because the swash really is continuous
     foam by the time it reaches the sand.
  3. VALIDITY. Multiplied by the bathymetry field's validity, like every other
     consumer -- bathy_field_graph.py:26-40 lists the three independent ways the
     field is absent and folds them into that one number. Where there is no
     baked depth there is no breaking, and the water looks exactly as it does
     today.

THE PEAKED SHAPE. A shoaling wave pitches forward: the crest sharpens and rises
while the trough stays broad. Applied as a shaping function on the height,

    f(H) = H + k * max(H, 0)^2 / peak,      k = BreakPeakGain * breaking

which lifts crests, leaves troughs untouched, and -- the part that matters here
-- has an ANALYTIC derivative, f'(H) = 1 + 2k*max(H,0)/peak, which is applied to
the gradient in the same three lines. The normal and the displacement stay two
outputs of one field. That is the property this whole node exists to have, and a
crest sharpening that only moved the geometry would quietly break it.

  APPROXIMATION, STATED: the exact gradient of f(H(p)) would also carry
  dk/dp -- the spatial variation of the breaking signal itself. It is left out,
  for the same reason and with the same honesty as the patch field's derivative
  already is (create_water_voxel_material.py:2526-2528): the breaking signal
  varies over the width of the surf band, metres, while the wave varies over
  tens of centimetres, so the omitted term is smaller by that ratio.

SHOALING GAIN. Waves grow before they break -- Green's law gives H ~ d^(-1/4) in
shallow water, so a wave arriving at its own break depth from four times that
depth is 4^0.25 = 1.41x taller. That is approximated with a linear ramp over
xr in [1, 4] reaching BreakShoalGain = 0.4 at the break line. It is deliberately
a ramp rather than the exact power law: the power law diverges at zero depth,
and the honest fix for that is a cap, at which point the cap is the model.


=============================================================================
THE REGRESSION RECIPE
=============================================================================

This module reproduces the shipped field EXACTLY -- not approximately -- with

    WindDirectionAuthority = 0        (whole-circle golden-angle placement)
    WindVectorMS length    = WindRefSpeedMS   (so both wind scalings are 1.0)
    BreakShoalGain         = 0
    BreakFoamGain          = 0
    BreakPeakGain          = 0

`LEGACY_RECIPE` below is that list in machine-readable form. Verified offline
against a numpy transcription of both the shipped HLSL and this one over a
30 m x 30 m patch at 400x400 samples, at the world's real ~84 km offset:
MAXIMUM ABSOLUTE DIFFERENCE 5.1e-11 m in height and 8.6e-10 in the gradient
components -- float64 rounding from re-associating the angle accumulation into
a lerp, i.e. the same field. Tilt statistics identical to two decimal places
(p50 2.91, p95 5.98, p99 7.36, max 11.24 degrees).

The point of that is not the number, it is that any future change to this file
shows up as a diff of the WAVE against a baseline that is a PARAMETER SET rather
than a git revision of a 2964-line generator.

The one thing the recipe does NOT restore is the direction of drift: nothing
here changes it, and nothing needed to -- the octave loop's sign convention is
untouched, which is why the difference above is 1e-11 and not a mirror image.


=============================================================================
COST
=============================================================================

ESTIMATED, NOT MEASURED, and the distinction is not a formality: nothing in this
change can be compiled without an editor, and this file was authored while the
editor was held by another job. The estimate is an operation count of the
emitted HLSL, which is what the shader compiler starts from and not what it
finishes with.

    shipped WaveField node        ~150 instructions (8 octaves x ~15, plus the
                                  patch field and the assembly)
    + wind sizing                 ~12   (length, normalize, 2 pow, 1 sqrt)
    + wind steering               ~30   (1 atan2, 1 round, 8 x lerp+mul)
    + patch advection             ~4
    + surf band and shoaling      ~12
    + breaking signal             ~14
    + crest peaking               ~8
    ------------------------------------------------------------------------
    estimated total               ~230 instructions

Two things about that number. It is a PIXEL AND VERTEX cost on water surfaces
only -- the node feeds MP_NORMAL and MP_WORLD_POSITION_OFFSET, so it runs once
per water vertex and once per water pixel and never for the submerged volume or
for basins off screen. And roughly 80 of the added instructions are wind
steering and sizing, which are UNIFORM ACROSS THE DRAW: they depend only on
material parameters and collection parameters, not on position, so a compiler
that hoists uniform expressions will move most of them out of the loop body.
Whether this one does is exactly the sort of claim this project does not make
without a measurement, so it is written as a hope and not as a result.

WHAT WAS DELIBERATELY NOT DONE, listed so nobody looks for it: no gust term (the
B channel of WindVectorMS is reserved and unread), no per-octave distance fade,
no true dispersion in the per-octave time progression, no fetch query, no
foam texture, and no change of any kind to the simulation.
"""

import math
import os
import re
import sys

import unreal

# A -run=pythonscript commandlet does not put the script's own directory on
# sys.path, hence the explicit insert -- same as create_sky_material.py:417-420
# and sky_star_graph.py:105-108.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

DEG2RAD = math.pi / 180.0

# The two MPC_VoxelSky parameters this file wants from the weather subsystem.
# Kept as named constants because three places test them: the availability probe
# in build_wind_input, the error text it prints, and summary_lines().
WIND_VECTOR_PARAM = "WindVectorMS"
WIND_VALID_PARAM = "WindFieldValid"

# Number of octaves. NOT a parameter: it is the loop bound in the HLSL, the
# length of the spread table, and the thing the 1.42 frequency ratio was chosen
# against (eight octaves from a 5 m base end at 0.43 m, which is still four
# samples per wavelength on the 10 cm quantisation grid --
# create_water_voxel_material.py:2401-2413). Changing it is a design change in
# three places at once, so it is a constant and it is stated here.
OCTAVES = 8

# --- TWO CONSTANTS THAT DESCRIBE THE NORMALISED FIELD ---------------------
#
# "Normalised" = the octave sum with AmplitudeM factored out, i.e. what the loop
# produces before any gain. Both are needed and they are NOT interchangeable;
# conflating them is the mistake this file made first and it made the surf zone
# three times too wide.
#
# FIELD_CREST is the ABSOLUTE MAXIMUM the field can reach, and it is analytic
# rather than measured: the crest function exp(sin(x)-1)*0.5 peaks at exactly
# 0.5, the weights are normalised to sum to 1, and MEAN_WAVE is subtracted, so
# the bound is 0.5 - 0.2329 with every octave cresting at the same point. The
# trough bound is exp(-2)*0.5 - 0.2329 = -0.1652 by the same argument. Measured
# over 120 m x 120 m at four times: max 0.2450, min -0.1615 -- i.e. the field
# gets within 9% of a bound it can only reach when all eight octaves align.
# USED FOR: normalising H to [-1, 1]-ish for the crest test and the peaking.
FIELD_CREST = 0.2671

# FIELD_RMS is the standard deviation of the same field. Measured over
# 120 m x 120 m at four times, 900x900 samples: 0.0597.
# USED FOR: the wave HEIGHT, via the oceanographic definition of significant
# wave height, H_s = 4 * sigma. That is the number the breaker criterion wants,
# and using the crest instead (0.267 rather than 4*0.0597 = 0.239... which look
# similar, but the crest was being doubled to get a crest-to-trough height,
# giving 0.534) over-stated the wave by 2.2x and put the break line in water
# more than twice as deep as it belongs.
FIELD_RMS = 0.0597
HS_PER_RMS = 4.0

# THE CALIBRATION, AND IT IS BETTER THAN IT HAD ANY RIGHT TO BE. The shipped
# WaveAmplitudeM of 0.25 was set by eye against a slope-distribution
# measurement, with no reference to any wind at all
# (create_water_voxel_material.py:2358-2382). Put through H_s = 4 * sigma it
# comes out at 6.0 cm. The fetch-limited JONSWAP prediction for a 5 m/s wind
# over 500 m of open water is 5.7 cm. Those agree to 5%, and inverting the
# relation says the shipped lake is a 5 m/s breeze over 552 m of fetch -- which
# is a real, ordinary lake in a real, ordinary breeze.
#
# So WindRefSpeedMS = 5.0 is not an arbitrary pivot chosen to make the maths
# tidy. It is what the shipped water ALREADY IS, measured after the fact, and
# that is why the whole wind response is expressed as a ratio to it.
#
# ONE HONEST CAVEAT, RECORDED SO IT IS NOT DISCOVERED AS A SURPRISE: the
# amplitude matches the physics, the WAVELENGTHS DO NOT. JONSWAP puts the
# spectral peak for that wind and fetch at 1.15 m; the shipped base octave is
# 5.0 m, about 4x too long, and the eight octaves run 5.00 m down to 0.43 m
# around it. That was an artistic choice and it is kept -- this module supplies
# the SCALING with wind, not a re-tuning. The reason it does not look wrong is
# worth knowing: the shipped crest SPEED is 1.59 m/s (omega 2.0 on a 5 m
# wavelength), and the physically correct speed for the physically correct
# 1.15 m wave is 1.34 m/s. The lake moves at lake speed even though its crests
# are spaced further apart than a real one's.
SHIPPED_HS_CM = 6.0

# Where shoaling starts, in units of the break depth. Green's law says a wave
# arriving at its break depth from 4x that depth is 4^0.25 = 1.41x taller, so
# the ramp runs from xb = 4 down to xb = 1 and BreakShoalGain defaults to 0.4.
SHOAL_START_RATIO = 4.0

# The parameter overrides that make this module reproduce the shipped field.
# See "THE REGRESSION RECIPE" in the module docstring; verified to 0.0 maximum
# absolute difference in height and both gradient components.
LEGACY_RECIPE = {
    "WindDirectionAuthority": 0.0,
    "BreakShoalGain": 0.0,
    "BreakFoamGain": 0.0,
    "BreakPeakGain": 0.0,
    # 0.6 m was BathyWaveDampDepthM's shipped value. Restoring it here makes the
    # shore damping the shipped `saturate(depth / 0.6)` exactly, because at the
    # shipped wave height the break depth (7.7 cm) is far below it.
    "BreakSurfFloorM": 0.6,
    # plus: wind speed == WindRefSpeedMS, which makes both wind scalings 1.0.
}

# Every scalar this module authors, with its shipped default. Held as data
# rather than as literals scattered through the builder for one reason: the
# design note (docs/water-wind-waves.md) and summary_lines() both have to quote
# these, and a table that is read by the code that uses it cannot go stale.
DEFAULTS = {
    # --- the shipped field, unchanged ------------------------------------
    "WaveAmplitudeM": 0.25,
    "WaveBaseWavelengthM": 5.0,
    "WaveDirBaseDeg": 58.7,
    "WaveDirIncrementDeg": 137.507764,
    "WaveQuantPerVoxel": 1.0,
    "WavePatchContrast": 0.55,
    # --- wind ------------------------------------------------------------
    "WindDirectionAuthority": 1.0,
    "WindSpreadDeg": 35.0,
    "WindRefSpeedMS": 5.0,
    "WindAmpExponent": 1.0,
    "WindLenExponent": 0.68,
    "WindPatchDriftFrac": 0.5,
    "WindFallbackSpeedMS": 5.0,
    "WindFallbackDirDeg": 238.7,
    # --- the shore band, shared by damping and breaking -------------------
    "BreakSurfFloorM": 0.15,
    "BreakDepthRatio": 1.28,
    "BreakShoalGain": 0.4,
    "BreakCrestThreshold": 0.35,
    "BreakMinWaveHeightM": 0.05,
    "BreakPeakGain": 0.6,
    "BreakFoamGain": 1.0,
}


def octave_spread_shape(n=OCTAVES):
    """The per-octave direction offset, in units of WindSpreadDeg.

    ONE DEFINITION, injected into the HLSL by `wave_code()`, so the shader and
    any offline transcription of it read the same table. Two properties, both
    argued at length in the module docstring:

      * frac((i + 0.5) * phi) is a golden-ratio low-discrepancy sequence, mapped
        to [-1, +1]. It spreads the eight directions evenly through the cone
        with no two equal and no repeat -- and the +0.5 offset is there so that
        no octave lands on exactly 0, i.e. exactly on the wind axis.
      * the 0.5 -> 1.5 width ramp reproduces the observed narrowing of
        directional spread at the spectral peak (Mitsuyasu's cos^2s model, s
        largest at the peak): the long heavy octaves line up with the wind and
        the short ones fan out.
    """
    phi = 0.6180339887498949
    out = []
    for i in range(n):
        low_disc = ((i + 0.5) * phi) % 1.0          # [0, 1)
        signed = 2.0 * low_disc - 1.0               # [-1, +1], never 0
        width = 0.5 + float(i) / float(n - 1)       # 0.5 at the peak -> 1.5 in the tail
        out.append(signed * width)
    return out


def wave_code():
    """The HLSL body of the WaveField Custom node.

    Built as a string rather than typed as one so the per-octave spread table
    comes from `octave_spread_shape()` and cannot drift from it. There is no
    other formatting in here -- everything else is literal HLSL, and it is
    deliberately readable as the mathematics it is (the argument for a Custom
    node over ~130 hand-wired expression nodes is at
    create_water_voxel_material.py:680-691).
    """
    spread_table = ", ".join("%.6ff" % v for v in octave_spread_shape())
    code = _WAVE_CODE_TEMPLATE % {
        "spread": spread_table,
        "octaves": OCTAVES,
        "field_crest": FIELD_CREST,
        "hs_gain": HS_PER_RMS * FIELD_RMS,
        "shoal_start": SHOAL_START_RATIO,
    }

    # EVERY DECLARED PIN MUST BE READ BY THE HLSL, checked here rather than
    # discovered in the editor. A Custom node input that the code never
    # references is not an error to the compiler -- the pin is simply ignored --
    # so renaming a parameter and missing one end produces a material that
    # builds, runs, and quietly uses a value nobody is feeding it any more. This
    # is the same class of silence as an unresolved CollectionParameter
    # compiling to a constant (sky_star_graph.py:196-207), and it gets the same
    # treatment: raise at authoring time.
    #
    # Word-boundary matching, not substring: "DepthM" is a substring of
    # "BreakDepthRatio" and "SurfFloorM" is not a substring of anything, so a
    # naive `in` test would pass a pin that only appears inside another name.
    missing = [nm for nm in WAVE_INPUTS
               if not re.search(r"\b%s\b" % re.escape(nm), code)]
    if missing:
        raise RuntimeError(
            "WaveField declares input pins the HLSL never reads: %s. Either the "
            "pin is dead and should come out of WAVE_INPUTS, or a rename missed "
            "one end -- in which case the material would have compiled anyway "
            "and silently stopped tracking that parameter." % missing)
    return code


# The HLSL. Read the module docstring first -- every non-obvious line here has
# its argument there rather than a duplicate of it beside the code.
#
# NO literal '%' may appear below: this string is %-formatted.
_WAVE_CODE_TEMPLATE = """
// ONE evaluation, FOUR outputs: float4(dH/dx, dH/dy, H, breaking).
//   .xy  surface gradient, dimensionless (metres of rise per metre of run)
//   .z   height, metres, zero-mean
//   .w   breaking signal, 0..1, for foam
// The gradient drives MP_NORMAL and the height drives MP_WORLD_POSITION_OFFSET,
// so they are two halves of one field and cannot disagree about a crest.
float2 p = PosM;

// Voxel-grid quantisation: the stylisation knob, and the anti-aliasing.
if (QuantPerVoxel > 0.0)
{
    float k = QuantPerVoxel * 10.0;   // samples per metre; 10 = one per 10 cm voxel
    p = floor(p * k) / k;
}

const float DRAG_MULT = 0.2;
// Mean of exp(sin(x)-1)*0.5 over a full period = 0.5 * I0(1) * e^-1.
const float MEAN_WAVE = 0.2329;
// Absolute crest of the normalised field, 0.5 - MEAN_WAVE. Used ONLY to put H
// on a [-1,1]-ish scale for the crest test and the peaking.
const float FIELD_CREST = %(field_crest).4f;
// 4 * (rms of the normalised field) -- significant wave height per unit of
// AmplitudeM, in metres. This and not the crest is what the breaker criterion
// wants; see water_wave_graph's FIELD_RMS for the 2.2x error that using the
// crest instead produces.
const float HS_GAIN = %(hs_gain).5f;
const float SHOAL_START = %(shoal_start).1f;
// Per-octave direction offset in units of WindSpreadDeg. Generated by
// water_wave_graph.octave_spread_shape() -- one definition, injected here.
const float SPREAD_SHAPE[%(octaves)d] = { %(spread)s };

// --- WIND: SPEED AND DIRECTION FROM ONE VECTOR --------------------------
// A velocity in m/s along world +X and +Y. One value, so speed and direction
// cannot be inconsistent, and calm is exactly zero rather than a special case.
// The max() is the only NaN guard needed: at zero wind windDir is (0,0), and
// every term it feeds is multiplied by a speed that is also zero.
float  windSpeed = length(WindVecMS);
float2 windDir   = WindVecMS / max(windSpeed, 1.0e-4);
float  u         = windSpeed / max(WindRefSpeedMS, 0.1);

// Fetch-limited growth: height ~ U^1, wavelength ~ U^0.68 (JONSWAP, see the
// module docstring for why NOT Pierson-Moskowitz). Both are exactly 1.0 at the
// reference speed, which is what makes the shipped field reproducible.
//
// The amplitude term reads u directly, so wind 0 gives amplitude EXACTLY 0 --
// dead calm, with the breaking term gated to zero by the same value. The
// wavelength term reads max(u, 0.2) instead, because a wavelength that
// collapses toward zero would send the octave frequencies to infinity long
// before the amplitude reached zero, and a field of infinite frequency at zero
// amplitude is a field of NaNs waiting for a rounding error.
float  ampScale = pow(max(u, 0.0), max(WindAmpExponent, 0.01));
float  lenScale = pow(max(u, 0.2), max(WindLenExponent, 0.0));
float  lambda0  = max(BaseWavelengthM * lenScale, 0.15);

// Deep-water dispersion, omega = sqrt(g k): a longer wave oscillates slower but
// its crests travel faster. 2.0 is the shipped base time multiplier, and the
// sqrt is exactly 1.0 at the reference speed.
float  omega0 = 2.0 * sqrt(BaseWavelengthM / max(lambda0, 1.0e-4));

// --- WIND: STEERING -----------------------------------------------------
// atan2(-w.x, -w.y) and not atan2(w.x, w.y). `ang` names the wavefront's UPWIND
// normal, because the loop below writes `+ T * tmul`, which makes crests travel
// along -d. Negating here puts travel on +windDir, i.e. downwind. This is the
// classic 180-degree bug and it is the reason the sign is spelled out.
float  upwindAng = atan2(-windDir.x, -windDir.y);
float  baseAng   = radians(DirBaseDeg);
// Unwrap before blending, so a wind turning through the 359->1 degree boundary
// does not swing the field the long way round at intermediate authorities.
float  dA = upwindAng - baseAng;
dA -= 6.2831853 * round(dA * 0.15915494);
baseAng += WindDirAuthority * dA;

float  spreadRad = radians(WindSpreadDeg);
float  dIncRad   = radians(DirIncrementDeg);

float2 pos    = p;
float  freq   = 6.2831853 / lambda0;
float  tmul   = omega0;
float  weight = 1.0;
float  sumH   = 0.0;
float  sumW   = 0.0;
float2 sumD   = float2(0.0, 0.0);

[unroll]
for (int i = 0; i < %(octaves)d; ++i)
{
    // Authority 0: the shipped whole-circle golden-angle placement, exactly.
    // Authority 1: a directional cone about the wind, narrow at the peak octave
    // and broad in the tail.
    float  ang = baseAng + lerp(dIncRad * i, spreadRad * SPREAD_SHAPE[i], WindDirAuthority);
    float2 d = float2(sin(ang), cos(ang));
    float  x = dot(d, pos) * freq + T * tmul;
    float  wv  = exp(sin(x) - 1.0) * 0.5;
    float  dwv = wv * cos(x);

    // Drag: this octave warps the sample position seen by the next one.
    pos += d * (-dwv) * weight * DRAG_MULT;

    sumH += wv * weight;
    sumD += d * (dwv * freq * weight);
    sumW += weight;

    weight *= 0.8;      // lerp(weight, 0, 0.2)
    freq   *= 1.42;     // non-commensurate on purpose
    tmul   *= 1.07;     // NOT the dispersion-correct 1.19; see the docstring
}

float  invW = 1.0 / max(sumW, 1e-6);
float  H = (sumH * invW) - MEAN_WAVE;
float2 G = sumD * invW;

// --- CALM AND CHOPPY PATCHES, NOW BLOWN DOWNWIND ------------------------
// The two diagonal sines at ~180 m and ~232 m are the shipped field's, verbatim.
// What is new is that the sample position is advected by the wind, so gust cells
// drift instead of merely breathing in place. Gated by WindDirAuthority so the
// regression recipe reproduces the shipped patch field exactly.
float2 pp = p - windDir * (windSpeed * T * WindPatchDrift * WindDirAuthority);
float lfa = sin(dot(pp, float2( 0.0349,  0.0217)) + T * 0.031);
float lfb = sin(dot(pp, float2(-0.0161,  0.0271)) + T * 0.0193);
float patch = saturate(0.5 + 0.35 * lfa + 0.35 * lfb);
float amp = AmplitudeM * ampScale * lerp(1.0 - PatchContrast, 1.0 + PatchContrast, patch);

// --- TWO NESTED DEPTH BANDS ---------------------------------------------
// Hs is the OFFSHORE significant wave height: what the wave would be if the bed
// were not in the way. That is the height the breaker criterion wants -- where
// a wave breaks is set by the wave that arrives, not by the one that is left
// after damping.
float Hs = amp * HS_GAIN;

// THE INNER BAND, WHERE THE WAVE BREAKS. depth < BreakDepthRatio * Hs, i.e.
// McCowan's H/d = 0.78 inverted. It is proportional to the wave, so it shrinks
// to nothing at zero wind and widens in a storm, with no separate knob.
float dBreak = max(BreakDepthRatio * Hs, 1.0e-3);

// THE OUTER BAND, WHERE THE WAVE DIES. Normally EQUAL to the break depth -- a
// wave breaks and then dissipates across the surf zone to the waterline, so the
// two bands coincide and the damping is the exact complement of the breaking.
// SurfFloorM is only a floor for tiny waves, so that even a millimetre of ripple
// still fades over a couple of voxels of depth instead of stopping dead at the
// shoreline.
float dSurf = max(dBreak, SurfFloorM);

float xb = DepthM / dBreak;              // 1 at the break line
float xr = DepthM / max(dSurf, 0.02);    // 1 at the outer edge of the damping

// WHERE THERE IS NO FIELD, THERE IS NO DAMPING AND NO BREAKING. Same lerp, same
// reason as the term this replaces: a run with no fine tier must look exactly
// as it does today rather than with its waves silently switched off.
float surf  = lerp(1.0, saturate(xr), Validity);
float shoal = 1.0 + ShoalGain * saturate((SHOAL_START - xb) * (1.0 / (SHOAL_START - 1.0))) * Validity;
float ampEff = amp * surf * shoal;

// --- BREAKING -----------------------------------------------------------
// The complement of the INNER band. Three gates, all of them load-bearing
// against a permanent white ring round a still lake:
//   band   -- only shoreward of the break line, which is proportional to the
//             wave. No wave, no band, whatever the damping depth is set to.
//   crest  -- foam rides the crests, so it travels with them; the threshold
//             relaxes to nothing at the waterline, where swash really is solid.
//   size   -- a second, absolute floor under the first, so a barely-rippled
//             lake cannot foam even where its bed comes up to a centimetre.
//   valid  -- no baked depth, no breaking.
float band     = 1.0 - lerp(1.0, saturate(xb), Validity);
float hNorm    = H * (1.0 / FIELD_CREST);
float crest    = saturate((hNorm - CrestThreshold) / max(1.0 - CrestThreshold, 1.0e-3));
float sizeGate = saturate(Hs / max(MinWaveHeightM, 1.0e-3));
float breaking = saturate(band * lerp(crest, 1.0, band) * sizeGate * Validity * FoamGain);

// --- THE PEAKED SHAPE ---------------------------------------------------
// f(H) = H + k*max(H,0)^2 / peak lifts crests and leaves troughs alone, which
// is what a shoaling wave does. The gradient is scaled by the ANALYTIC
// derivative f'(H) = 1 + 2k*max(H,0)/peak in the same breath, so the normal and
// the displacement stay one field. The dk/dp term is omitted; see the docstring.
float kPeak = PeakGain * breaking;
float hPos  = max(H, 0.0);
float hNormPos = hPos * (1.0 / FIELD_CREST);
H += kPeak * hNormPos * hPos;
G *= (1.0 + 2.0 * kPeak * hNormPos);

return float4(G * ampEff, H * ampEff, breaking);
"""


# Every input pin on the Custom node, in wiring order. The NAMES are what the
# HLSL above reads, so a rename that misses one end fails to compile loudly
# rather than reading a stale value -- which is the whole boundary argument for
# a Custom node (create_water_voxel_material.py:688-691).
WAVE_INPUTS = [
    "PosM", "T",
    "AmplitudeM", "BaseWavelengthM", "DirBaseDeg", "DirIncrementDeg",
    "QuantPerVoxel", "PatchContrast",
    "WindVecMS", "WindDirAuthority", "WindSpreadDeg", "WindRefSpeedMS",
    "WindAmpExponent", "WindLenExponent", "WindPatchDrift",
    "DepthM", "Validity", "SurfFloorM",
    "BreakDepthRatio", "ShoalGain", "CrestThreshold", "MinWaveHeightM",
    "PeakGain", "FoamGain",
]


def _custom_node(b, name, code, inputs, output_type):
    """A MaterialExpressionCustom with named inputs and no wiring yet.

    A copy of create_water_voxel_material.py:692-714 in shape, and it has to be:
    only the input NAME is settable from Python -- FCustomInput carries an FName
    and an FExpressionInput, and the FExpressionInput is filled in by the
    connect calls that follow. So the array is built name-only here and the
    caller wires it with the usual checked link().
    """
    node = b.node(unreal.MaterialExpressionCustom)
    node.set_editor_property("description", name)
    node.set_editor_property("code", code)
    node.set_editor_property("output_type", output_type)
    ins = []
    for nm in inputs:
        ci = unreal.CustomInput()
        ci.set_editor_property("input_name", nm)
        ins.append(ci)
    node.set_editor_property("inputs", ins)

    # READ THE NAMES BACK. set_editor_property on a TArray of structs is the
    # least-exercised call in this whole toolchain -- create_sky_material.py
    # verifies its MPC parameter array the same way and for the same reason
    # (create_sky_material.py:598-605). A dropped input name here would not fail
    # to compile: the HLSL would reference an undeclared symbol and the material
    # would go to the default, which on this project has already cost a session.
    got = [str(ci.get_editor_property("input_name"))
           for ci in node.get_editor_property("inputs")]
    if got != list(inputs):
        raise RuntimeError(
            "Custom node %r input names did not round-trip: wrote %s, read back %s"
            % (name, list(inputs), got))
    return node


def build_wind_input(b, defaults=None, log=None):
    """The wind velocity as a float2 in m/s, world XY. Returns (expr, source).

    `b` must be a SkyGraphBuilder (sky_star_graph.py:146) -- this needs its
    CHECKED collection_param and its mpc_names read-back, for the reason that
    module states at length: an unresolved CollectionParameter compiles to a
    CONSTANT rather than failing (MaterialExpressions.cpp:17179-17193), so a
    typo would ship a lake with a permanent imaginary wind and no diagnostic.

    TWO SOURCES, AND THE FALLBACK IS NOT A STUB.

      * MPC_VoxelSky.WindVectorMS, blended in on MPC_VoxelSky.WindFieldValid.
        This is the weather subsystem's channel; see the module docstring for
        the exact semantics both halves have to agree on.
      * Two MATERIAL parameters, WindFallbackSpeedMS and WindFallbackDirDeg,
        used when the collection has no wind parameters at all AND (at runtime)
        whenever WindFieldValid is 0.

    THE FALLBACK IS THE RUNTIME PATH FOR A SESSION WITH NO WEATHER, not merely a
    build-time convenience, which is why its defaults reproduce the shipped
    look: 5 m/s at a bearing whose upwind normal is 58.7 degrees -- the swept
    optimum the shipped field already uses (the sweep, and why 0 would be a bug,
    is at create_water_voxel_material.py:2431-2452).

    IF THE COLLECTION HAS NO WIND PARAMETERS THIS DOES NOT RAISE, which is a
    deliberate departure from how every other binding in this toolchain behaves.
    Everywhere else a missing MPC parameter is a hard error, because it means a
    generator ran out of order. Here it means the OTHER HALF OF THIS FEATURE HAS
    NOT LANDED YET -- the weather subsystem and this module are being built at
    the same time -- and a water material that refuses to generate until then is
    a material whose first test is the day both land. It logs, loudly, and takes
    the fallback.
    """
    d = dict(DEFAULTS)
    if defaults:
        d.update(defaults)

    # --- the fallback, always built ----------------------------------------
    #
    # WindFallbackDirDeg is the bearing of the wind VELOCITY -- where the air is
    # going -- in the same angle convention the wave loop uses for its octave
    # directions: the unit vector is (sin a, cos a) in world XY, i.e. a is
    # measured from world +Y toward world +X.
    #
    # THE DEFAULT LOOKS ARBITRARY AND IS NOT. 238.7 = 58.7 + 180, so the upwind
    # normal this produces is exactly 58.7 degrees, the angle
    # create_water_voxel_material.py swept for: the base angle that maximises
    # the smallest distance between any octave's wavefront and a world axis. The
    # fallback lake therefore has its dominant wave train pointing where the
    # shipped lake's does.
    fb_speed = b.scalar("WindFallbackSpeedMS", d["WindFallbackSpeedMS"])
    fb_dir_deg = b.scalar("WindFallbackDirDeg", d["WindFallbackDirDeg"])
    fb_ang = b.mul(fb_dir_deg, b.const(DEG2RAD))
    # b.sine/b.cosine, NOT raw Sine/Cosine nodes: those default to Period = 1.0
    # and silently compute sin(2pi*x), multiplying every angle by 6.283 with no
    # error anywhere. SkyGraphBuilder._trig sets the period and reads it back --
    # sky_star_graph.py:249-276 lists the two shipped bugs that cost.
    fb_dir = b.append(b.sine(fb_ang), "", b.cosine(fb_ang), "")
    fallback = b.mul(fb_dir, fb_speed)

    names = b.mpc_names()
    have = WIND_VECTOR_PARAM in names and WIND_VALID_PARAM in names
    if not have:
        msg = ("[water_wave_graph] MPC_VoxelSky has no %s / %s -- building the water "
               "wave field on its MATERIAL fallback wind (%s m/s at %s deg). This is "
               "the expected state until the weather subsystem publishes those two "
               "parameters from create_sky_material.py's VECTOR_PARAMS / "
               "SCALAR_PARAMS. Present on the collection: %s"
               % (WIND_VECTOR_PARAM, WIND_VALID_PARAM,
                  d["WindFallbackSpeedMS"], d["WindFallbackDirDeg"], sorted(names)))
        (log or print)(msg)
        return fallback, "material-fallback"

    wind_mpc = b.mask(b.collection_param(WIND_VECTOR_PARAM), "", r=True, g=True)
    wind_valid = b.collection_param(WIND_VALID_PARAM)
    # Lerp and not a select: WindFieldValid is written by C++ and a hard switch
    # at 0/1 would pop the whole lake's wave direction the frame the weather
    # subsystem starts publishing. A CPU-side ramp on that scalar makes the
    # handover a fade for free.
    return b.lerp(fallback, "", wind_mpc, "", wind_valid), "MPC_VoxelSky"


def build_wave_field(b, pos_m, time_expr, bathy, defaults=None, log=None):
    """The whole wave field. Returns a dict of expressions.

    Arguments:
      b          a SkyGraphBuilder bound to the material and to MPC_VoxelSky.
      pos_m      float2, the sample position in METRES. Must be ABSOLUTE world
                 XY -- see below; this is not a detail the caller may vary.
      time_expr  the scalar time driving the field. Passed in rather than
                 created here so create_water_voxel_material.py's
                 VOXEL_WATER_FREEZE_TIME arm stays a single-node substitution
                 (create_water_voxel_material.py:503-533): freezing that one
                 node still provably freezes every animated term on the surface,
                 including the breaking foam, which now also rides it.
      bathy      the dict from bathy_field_graph.sample_bathy_field(b). Read for
                 `depth_m` and `validity` ONLY -- the shoreline foam's use of
                 `shore_m` is a different effect and stays where it is.

    Returns keys:
      node       the Custom node itself
      gradient   float2, dH/dx and dH/dy, for the normal
      height_m   float, metres, for the World Position Offset
      breaking   float 0..1, for foam
      wind       the float2 wind velocity expression, in case a caller wants it
      wind_source  "MPC_VoxelSky" or "material-fallback"

    THE POSITION MUST BE ABSOLUTE WORLD XY AND THE CALLER OWNS THAT. It is the
    single most important line in the shipped section and the argument is long
    (create_water_voxel_material.py:2303-2320, "CAUSE A"): the pooled vertex
    factory's UV repeats every 32 m and mirrors about x=0 and y=0, and the
    far-field sheets anchor their UV at each sheet's own bounding-box corner, so
    near water and far water had unrelated wave phase and met at a seam. World
    XY is the only coordinate both draw paths can agree on and it has no period.
    It is also what makes adjacent bricks compute bit-identical displacement at
    a shared vertex, which is the only thing stopping the mesh tearing open along
    every seam as the phase moves.
    """
    d = dict(DEFAULTS)
    if defaults:
        d.update(defaults)

    wind, wind_source = build_wind_input(b, defaults=d, log=log)

    node = _custom_node(b, "WaveField", wave_code(), WAVE_INPUTS,
                        unreal.CustomMaterialOutputType.CMOT_FLOAT4)

    # Every pin, wired by name, every connect checked. SkyGraphBuilder.link
    # raises with the destination's actual pin list on failure, which is the
    # fastest way to find the one cause these ever have (a name).
    wiring = [
        ("PosM", pos_m),
        ("T", time_expr),
        # --- the shipped field's knobs, unchanged in name, default and meaning
        ("AmplitudeM", b.scalar("WaveAmplitudeM", d["WaveAmplitudeM"])),
        ("BaseWavelengthM", b.scalar("WaveBaseWavelengthM", d["WaveBaseWavelengthM"])),
        ("DirBaseDeg", b.scalar("WaveDirBaseDeg", d["WaveDirBaseDeg"])),
        ("DirIncrementDeg", b.scalar("WaveDirIncrementDeg", d["WaveDirIncrementDeg"])),
        ("QuantPerVoxel", b.scalar("WaveQuantPerVoxel", d["WaveQuantPerVoxel"])),
        ("PatchContrast", b.scalar("WavePatchContrast", d["WavePatchContrast"])),
        # --- wind
        ("WindVecMS", wind),
        # 0 reproduces the shipped whole-circle placement exactly; 1 is the wind
        # cone. It is a lerp and not a switch so it is also the A/B knob: an
        # owner can slide it on a material instance and watch the lake go from a
        # confused sea to a wind sea without a regeneration.
        ("WindDirAuthority", b.scalar("WindDirectionAuthority", d["WindDirectionAuthority"])),
        # Half-width of the directional cone at the PEAK octave, before the
        # 0.5 -> 1.5 tail ramp. 35 puts the peak octave within 7 degrees of the
        # wind and the shortest octave 46 degrees off it.
        ("WindSpreadDeg", b.scalar("WindSpreadDeg", d["WindSpreadDeg"])),
        # The calibration speed: at this wind the field is EXACTLY the shipped
        # one. Everything else about the wind response is a ratio to it.
        ("WindRefSpeedMS", b.scalar("WindRefSpeedMS", d["WindRefSpeedMS"])),
        # Fetch-limited exponents, JONSWAP. Height ~ U^1, wavelength ~ U^0.68.
        # These are the physics; the module docstring shows the derivation and
        # why Pierson-Moskowitz (U^2 for both) is the wrong family for a lake.
        ("WindAmpExponent", b.scalar("WindAmpExponent", d["WindAmpExponent"])),
        ("WindLenExponent", b.scalar("WindLenExponent", d["WindLenExponent"])),
        ("WindPatchDrift", b.scalar("WindPatchDriftFrac", d["WindPatchDriftFrac"])),
        # --- the shore band
        ("DepthM", bathy["depth_m"]),
        ("Validity", bathy["validity"]),
        # REPLACES BathyWaveDampDepthM, AND THE DEFAULT MOVES 0.6 -> 0.15. That is
        # the one deliberate change of shipped behaviour in this module and it is
        # not a tuning tweak, so it gets the space:
        #
        # The old term damped the wave to zero over the first 0.6 m of depth. The
        # break depth for the shipped wave is 7.7 cm. So a wave arrived at the
        # depth where it should break with 16 percent of its height left -- it
        # faded out well offshore and almost nothing reached the beach. Measured
        # on a 2-D shore at four phases, peak crest inside the foamed region at
        # 5 m/s: 1.22 cm with the 0.6 m floor, 4.88 cm with this one.
        #
        # Now the damping band IS the breaker band, floored only so that a
        # near-flat lake still fades over 1.5 voxels of depth rather than stopping
        # dead at the shoreline. Two consequences worth stating:
        #
        #   * WAVES NOW REACH THE SHORE. That is the feature, and it is a visible
        #     change from what ships. The regression recipe restores 0.6 m.
        #   * THE BANK-CLIPPING GUARANTEE IS NOW DERIVED RATHER THAN TUNED, which
        #     retires the reason WaveWpoFraction was pinned at 0.25
        #     (create_water_voxel_material.py:2385-2398, "no shore-damping term to
        #     stop a rising crest clipping through its own bank"). Inside the surf
        #     zone the linear ramp on a wave-proportional band gives
        #     H(d) = d / BreakDepthRatio = 0.78 d, i.e. the wave is DEPTH-LIMITED
        #     exactly as a real surf zone is, at any wind speed. The crest sits at
        #     ~0.4 of the local depth above the still surface and the geometry
        #     moves a quarter of that. It cannot clip a bank because it is bounded
        #     by the water it is standing in.
        ("SurfFloorM", b.scalar("BreakSurfFloorM", d["BreakSurfFloorM"])),
        # The breaker index, inverted: a wave breaks where depth < ratio * H.
        # 1.28 is 1/0.78, McCowan's solitary-wave limit.
        ("BreakDepthRatio", b.scalar("BreakDepthRatio", d["BreakDepthRatio"])),
        ("ShoalGain", b.scalar("BreakShoalGain", d["BreakShoalGain"])),
        ("CrestThreshold", b.scalar("BreakCrestThreshold", d["BreakCrestThreshold"])),
        ("MinWaveHeightM", b.scalar("BreakMinWaveHeightM", d["BreakMinWaveHeightM"])),
        ("PeakGain", b.scalar("BreakPeakGain", d["BreakPeakGain"])),
        # The A/B on the whole breaking effect, as a runtime scalar rather than a
        # generation-time arm. This one is safe as a parameter where the
        # shoreline-foam arm was not: VOXEL_SHORE_FX exists because zeroing a
        # gain measures nothing about GPU cost
        # (create_water_voxel_material.py:550-560), and this gain is not being
        # used to measure cost -- it is here so the owner can turn surf off in a
        # screenshot without a regeneration.
        ("FoamGain", b.scalar("BreakFoamGain", d["BreakFoamGain"])),
    ]
    for pin, src in wiring:
        b.link(src, "", node, pin)

    return {
        "node": node,
        "gradient": b.mask(node, "", r=True, g=True),
        "height_m": b.mask(node, "", b=True),
        "breaking": b.mask(node, "", a=True),
        "wind": wind,
        "wind_source": wind_source,
    }


def summary_lines(wind_source=None):
    """The wind model as text, for the generator's log.

    water_optics.py does this and the reason transfers exactly: "were these two
    built from the same numbers" should be answerable from two logs rather than
    by opening two assets. Here the two are the water material and whatever the
    weather subsystem ends up publishing, and the line that matters is the
    interface one.
    """
    lines = [
        "wind waves: fetch-limited (JONSWAP) scaling about a %.1f m/s reference"
        % DEFAULTS["WindRefSpeedMS"],
        "  amplitude ~ U^%.2f, wavelength ~ U^%.2f, phase speed ~ sqrt(wavelength)"
        % (DEFAULTS["WindAmpExponent"], DEFAULTS["WindLenExponent"]),
        "  directional cone %.0f deg half-width at the peak octave, 0.5x..1.5x over %d octaves"
        % (DEFAULTS["WindSpreadDeg"], OCTAVES),
        "  breaking at depth < %.2f x significant wave height; the shore damping uses"
        % DEFAULTS["BreakDepthRatio"],
        "  the same band, floored at %.2f m, so the wave is depth-limited in the surf zone"
        % DEFAULTS["BreakSurfFloorM"],
        "  interface: MPC_VoxelSky.%s (velocity m/s, world XY, points DOWNWIND)"
        % WIND_VECTOR_PARAM,
        "  interface: MPC_VoxelSky.%s (1 once the weather field has published)"
        % WIND_VALID_PARAM,
    ]
    if wind_source is not None:
        lines.append("  wind source THIS BUILD: %s" % wind_source)
    return lines
