#!/usr/bin/env node
// Concatenates the stylesheet layers into one shipped file and puts the font
// beside it.
//
// ONE FLAT FILE, ON PURPOSE. The design-sync converter scrapes this stylesheet
// and copies the font files its @font-face rules point at. A build that emitted
// @import chains would hand it paths to resolve across directories, and every
// one that failed would show up as a design rendering in a fallback face --
// visible only to whoever eventually looks at it. Concatenating removes the
// class of problem entirely.
//
// Layer order is cascade order and is not arbitrary: tokens must precede
// everything that reads them, and components must follow utilities so a
// component's own rule wins over a same-specificity utility.

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const dist = resolve(root, 'dist');
mkdirSync(dist, { recursive: true });

const layers = [
  'src/styles/tokens.css',
  'src/styles/fonts.css',
  'src/styles/utilities.css',
  'src/styles/base.css',
  'src/styles/components.css',
];

const parts = [
  '/* VoxelMark design system -- generated by tools/build-css.mjs.',
  ' * Ported from the game front end at ue-project/Source/VoxelEarthUI.',
  ' */',
  '',
];
for (const rel of layers) {
  const body = readFileSync(resolve(root, rel), 'utf8');
  parts.push(`/* ===== ${rel} ===== */`);
  parts.push(body.trimEnd());
  parts.push('');
}
writeFileSync(resolve(dist, 'voxelmark.css'), parts.join('\n'));

// The font is taken from the game's own content tree, not a copy kept here --
// one file, so the design system and the engine can never load different
// metrics. It lands next to the stylesheet so the @font-face url('./...')
// resolves from wherever that stylesheet is copied to.
const fontDir = resolve(root, '../ue-project/Content/UI/Fonts');
copyFileSync(resolve(fontDir, 'MacondoSwashCaps-Regular.ttf'), resolve(dist, 'MacondoSwashCaps-Regular.ttf'));
copyFileSync(resolve(fontDir, 'OFL.txt'), resolve(dist, 'OFL.txt'));

const bytes = readFileSync(resolve(dist, 'voxelmark.css')).length;
console.log(`[CSS] ${layers.length} layers -> dist/voxelmark.css (${(bytes / 1024).toFixed(1)} KB) + font`);
