#!/usr/bin/env node
// Generates the design-system's tokens FROM the game's own C++ header, so the
// web tokens cannot drift from what the engine renders.
//
// Source of truth: ue-project/Source/VoxelEarthUI/VoxelUITheme.h
//   - every `inline const FColor <Name> = FColor(0x..,0x..,0x..);`  -> a colour token
//   - every `<float|int32> <Name> = <n>;` inside FVoxelMenuLayout   -> a layout token
//
// COLOUR SPACE. The FColor literals hold the exact sRGB hex from the Godot
// build's Colors.gd, which is byte-identical to the :root block of the original
// HTML mocks (menus_shared.css) these screens were drawn against. Those hexes
// ARE the authored design values, so they are emitted verbatim. The separate
// question of whether Slate re-encodes them identically on screen
// (voxel.UI.SRGBTint) is a renderer matter on the UE side and deliberately not
// modelled here -- see NOTES.md.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const HEADER = resolve(here, '../../ue-project/Source/VoxelEarthUI/VoxelUITheme.h');

if (!existsSync(HEADER)) {
  console.error(`[TOKENS] source header not found: ${HEADER}`);
  console.error('[TOKENS] this package must live beside ue-project/ in the voxelsim checkout.');
  process.exit(1);
}
const src = readFileSync(HEADER, 'utf8');

// --- colours ---------------------------------------------------------------
const colours = [];
const colourRe = /inline const FColor\s+(\w+)\s*=\s*FColor\(\s*0x([0-9a-fA-F]{2})\s*,\s*0x([0-9a-fA-F]{2})\s*,\s*0x([0-9a-fA-F]{2})\s*\)/g;
for (const m of src.matchAll(colourRe)) {
  colours.push({ name: m[1], hex: `#${m[2]}${m[3]}${m[4]}`.toLowerCase() });
}

// --- layout ----------------------------------------------------------------
// Bounded to the FVoxelMenuLayout struct body so unrelated constants can't leak.
const structStart = src.indexOf('struct VOXELEARTHUI_API FVoxelMenuLayout');
if (structStart < 0) { console.error('[TOKENS] FVoxelMenuLayout not found'); process.exit(1); }
const structBody = src.slice(structStart);
const layout = [];
const layoutRe = /^\s*(?:float|int32)\s+(\w+)\s*=\s*([0-9.]+)f?\s*;/gm;
for (const m of structBody.matchAll(layoutRe)) {
  layout.push({ name: m[1], value: parseFloat(m[2]) });
}

if (colours.length === 0 || layout.length === 0) {
  console.error(`[TOKENS] parse yielded ${colours.length} colours / ${layout.length} layout values - refusing to emit`);
  process.exit(1);
}

// PascalCase -> kebab-case
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2').toLowerCase();

// Godot Color.darkened(k), as VoxelUITheme::Darkened ports it: scales the
// STORED sRGB bytes, round-to-nearest. The pressed and disabled button fills
// are both defined this way, so it is reproduced rather than approximated.
function darkened(hex, amount) {
  const scale = Math.min(Math.max(1 - amount, 0), 1);
  const n = parseInt(hex.slice(1), 16);
  const ch = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((c) => Math.round(c * scale));
  return '#' + ch.map((c) => c.toString(16).padStart(2, '0')).join('');
}

const oak2 = colours.find((c) => c.name === 'PanelOak2');
if (!oak2) { console.error('[TOKENS] PanelOak2 missing - button state fills cannot be derived'); process.exit(1); }

// --- emit CSS --------------------------------------------------------------
const lines = [];
lines.push('/* GENERATED by tools/gen-tokens.mjs from ue-project/Source/VoxelEarthUI/VoxelUITheme.h.');
lines.push(' * Do not edit by hand -- edit the C++ header and re-run `npm run tokens`.');
lines.push(' */');
lines.push(':root {');
lines.push('  /* --- palette (VoxelUITheme, sRGB verbatim) --- */');
for (const c of colours) lines.push(`  --vm-${kebab(c.name)}: ${c.hex};`);
lines.push('');
lines.push('  /* --- derived button fills (VoxelUITheme::Darkened over PanelOak2) --- */');
lines.push(`  --vm-panel-oak2-pressed: ${darkened(oak2.hex, 0.15)};`);
lines.push(`  --vm-panel-oak2-disabled: ${darkened(oak2.hex, 0.30)};`);
lines.push('');
lines.push('  /* --- literals that are FLinearColor in the C++, packed straight to bytes --- */');
lines.push('  --vm-bar-track: #0a0604;      /* the loading bar\'s "dark leather" */');
lines.push('  --vm-shadow-panel: rgba(0, 0, 0, 0.6);');
lines.push('  --vm-wash-loading: rgba(0, 0, 0, 0.62);');
lines.push('');
lines.push('  /* --- layout (FVoxelMenuLayout defaults) --- */');
for (const l of layout) {
  // Three unit families, decided by name: bare ratios (alphas, the animation
  // delta clamp), seconds (every timing the screens animate on), pixels (all
  // the rest). Getting this wrong is silent -- a duration emitted as `2.5`
  // makes an `animation-duration` invalid and the animation simply never runs.
  let unit = 'px';
  if (/Alpha$|Delta$/.test(l.name)) unit = '';
  else if (/Duration|Rotate|Fade|Period|Interval/.test(l.name)) unit = 's';
  lines.push(`  --vm-${kebab(l.name)}: ${l.value}${unit};`);
}
lines.push('');
lines.push('  /* --- typography --- */');
// Just the shipped face and the generic. Naming specific OS fallbacks
// (Papyrus, Luminari) reads to tooling as families the system expects to be
// provided and cannot find -- and neither is present widely enough to be worth
// that. The generic keeps text legible if the .ttf ever fails to load.
lines.push("  --vm-font-serif: 'Macondo Swash Caps', serif;");
lines.push('}');
writeFileSync(resolve(here, '../src/styles/tokens.css'), lines.join('\n') + '\n');

// --- emit TS ---------------------------------------------------------------
const ts = [];
ts.push('// GENERATED by tools/gen-tokens.mjs. Do not edit by hand.');
ts.push('');
ts.push('/** Every VoxelMark palette colour, as the sRGB hex the game defines. */');
ts.push('export const colors = {');
for (const c of colours) ts.push(`  ${c.name}: '${c.hex}',`);
ts.push(`  PanelOak2Pressed: '${darkened(oak2.hex, 0.15)}',`);
ts.push(`  PanelOak2Disabled: '${darkened(oak2.hex, 0.30)}',`);
ts.push('} as const;');
ts.push('');
ts.push('/** Every layout number the front end positions anything with. */');
ts.push('export const layout = {');
for (const l of layout) ts.push(`  ${l.name}: ${l.value},`);
ts.push('} as const;');
ts.push('');
ts.push('export type VoxelMarkColor = keyof typeof colors;');
writeFileSync(resolve(here, '../src/tokens.ts'), ts.join('\n') + '\n');

console.log(`[TOKENS] ${colours.length} colours, ${layout.length} layout values -> src/styles/tokens.css + src/tokens.ts`);
