"""Content-addressed disk cache for tiles (plan §3.1 step 2).

Tiles are generated once and cached forever; the cache key includes the
provider identity+version so switching providers (synthetic dev tiles vs the
real diffusion worker) can never serve stale bytes. Writes are atomic
(tmp + rename) so a crashed worker never leaves a torn tile.

Three artifact kinds share one layout, keyed by an identity string first --
but NOT THE SAME identity string, and that is the load-bearing detail:

    <root>/<provider_id>/<seed:016x>/s1/<x>_<y>.vxtl       coarse tile, 30 m/px
    <root>/<fine_provider_id>/<seed:016x>/s16/<x>_<y>.vxtl FINE TIER, 1.875 m/px
    <root>/<fine_provider_id>/<seed:016x>/flow<L>/<sx>_<sy>.vxfl
                                                           flow superblock, level L
    <root>/<identity>/<seed:016x>/world-identity.json      WHAT MADE ALL OF THE ABOVE

``<identity>/<seed:016x>`` IS the world -- one directory per (identity, seed)
pair, and every artifact under it was generated by one set of inputs. The
manifest sits at that level rather than inside ``s1/`` for exactly that reason:
it describes the world, not a tier of it, and every tool that walks the cache
globs ``*.vxtl`` inside the tier directories, so it cannot be mistaken for one.
See ``world_manifest.py`` for what goes in it and why a world without one
cannot be extended even in principle.

``provider_id`` covers inference identity only; ``fine_provider_id`` is that
plus the bake's digest (``providers/diffusion.py::fine_id_for``). Artifacts key
on what they DEPEND ON, so retuning a bake constant re-keys the fine tier and
the flow pyramid together and leaves the coarse tiles -- ~22.5 s of GPU each,
and unrecreatable on a CPU-only box -- exactly where they are.

Callers must pass the right one. ``path``/``get``/``put`` take whatever they
are given and cannot check it: a fine tile written under a coarse id lands in a
namespace that will not be re-keyed when the bake changes, which is silent
until the day it serves stale geometry. ``pregen._run_bake`` binds
``fine_provider_id`` once at the top for exactly this reason.

The fine tier reuses the scale slot rather than inventing a new axis: the
.vxtl v2 container is one fine tier per COARSE tile coordinate at scale 16
(docs/vxtl-v2-format.md section 1), so ``s16/<x>_<y>.vxtl`` addresses it with
the coarse (x, y) and no new path grammar. That also means the existing
``path``/``get``/``put`` already work for it; ``fine_path``/``get_fine``/
``put_fine`` exist so callers state which tier they mean instead of passing a
bare 16.

Flow superblocks (``terrain_service.bake.pipeline.FlowSuperblock``) are the
hydrology pyramid's cached intermediates: 30 m accumulation over a
world-anchored block of coarse tiles, plus the coarser levels above it. They
are keyed by SUPERBLOCK index, not tile index -- that is the point of them.
Two adjacent tiles that share an edge read the SAME superblock bytes, so they
cannot disagree about how much upstream area crosses that edge; a per-tile
neighbourhood computed on the fly would give each side its own answer.

Being under ``fine_provider_id`` matters for the same reason it matters for the
fine tier: that id covers the bake version and constants (see
``providers/diffusion.py::_bake_fingerprint``), so a bake change lands in a
fresh namespace and can never mix with superblocks built by the old one. They
sit beside the fine tiles they fed rather than beside the coarse tiles they
were computed FROM, because a superblock is bake output, not inference output.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

#: The scale slot the baked fine tier occupies. docs/vxtl-v2-format.md: one
#: fine container per coarse tile coordinate, 8192x8192 at 1.875 m/px.
FINE_SCALE = 16

#: Filename suffix for flow superblocks. Deliberately not ``.vxtl`` -- nothing
#: in voxel-core parses these, they are a server-side intermediate.
FLOW_SUFFIX = ".vxfl"

#: The identity record every world carries, at the world directory's top level.
#: See ``world_manifest.py``.
WORLD_MANIFEST_NAME = "world-identity.json"


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise


class TileCache:
    def __init__(self, root: str | os.PathLike[str]):
        self.root = Path(root)

    # -- the world directory itself ----------------------------------------

    def world_dir(self, provider_id: str, seed: int) -> Path:
        """The directory holding every artifact of one (identity, seed) world."""
        return self.root / provider_id / f"{seed:016x}"

    def world_manifest_path(self, provider_id: str, seed: int) -> Path:
        return self.world_dir(provider_id, seed) / WORLD_MANIFEST_NAME

    def world_has_artifacts(self, provider_id: str, seed: int) -> bool:
        """Does this world already contain tiles/superblocks?

        Used to tell "creating a world" from "writing into one that already
        exists", which decides whether a manifest written now describes
        everything in the directory or only what follows it. Stops at the
        first hit rather than counting -- a 289-tile world is a lot of
        ``stat`` calls to answer a yes/no question.
        """
        d = self.world_dir(provider_id, seed)
        if not d.is_dir():
            return False
        for tier in sorted(d.iterdir()):
            if tier.is_dir() and any(tier.iterdir()):
                return True
        return False

    def get_world_manifest(self, provider_id: str, seed: int) -> bytes | None:
        try:
            return self.world_manifest_path(provider_id, seed).read_bytes()
        except FileNotFoundError:
            return None

    def put_world_manifest(self, provider_id: str, seed: int, data: bytes) -> None:
        _atomic_write(self.world_manifest_path(provider_id, seed), data)

    # -- coarse + fine tiles (both .vxtl, addressed by scale slot) ---------

    def path(self, provider_id: str, seed: int, x: int, y: int, scale: int) -> Path:
        return (
            self.root
            / provider_id
            / f"{seed:016x}"
            / f"s{scale}"
            / f"{x}_{y}.vxtl"
        )

    def get(self, provider_id: str, seed: int, x: int, y: int, scale: int) -> bytes | None:
        p = self.path(provider_id, seed, x, y, scale)
        try:
            return p.read_bytes()
        except FileNotFoundError:
            return None

    def put(
        self, provider_id: str, seed: int, x: int, y: int, scale: int, data: bytes
    ) -> None:
        _atomic_write(self.path(provider_id, seed, x, y, scale), data)

    def fine_path(self, provider_id: str, seed: int, x: int, y: int) -> Path:
        """The baked fine tier for COARSE tile (x, y)."""
        return self.path(provider_id, seed, x, y, FINE_SCALE)

    def get_fine(self, provider_id: str, seed: int, x: int, y: int) -> bytes | None:
        return self.get(provider_id, seed, x, y, FINE_SCALE)

    def put_fine(self, provider_id: str, seed: int, x: int, y: int, data: bytes) -> None:
        self.put(provider_id, seed, x, y, FINE_SCALE, data)

    # -- flow superblocks --------------------------------------------------

    def flow_path(
        self, provider_id: str, seed: int, level: int, sx: int, sy: int
    ) -> Path:
        """One level-``level`` flow superblock at superblock index (sx, sy).

        (sx, sy) is a SUPERBLOCK index (``pipeline.superblock_index``), not a
        tile index, and the two grids are different at every level -- naming
        the level in the directory keeps that impossible to confuse.
        """
        return (
            self.root
            / provider_id
            / f"{seed:016x}"
            / f"flow{level}"
            / f"{sx}_{sy}{FLOW_SUFFIX}"
        )

    def get_flow(
        self, provider_id: str, seed: int, level: int, sx: int, sy: int
    ) -> bytes | None:
        try:
            return self.flow_path(provider_id, seed, level, sx, sy).read_bytes()
        except FileNotFoundError:
            return None

    def put_flow(
        self, provider_id: str, seed: int, level: int, sx: int, sy: int, data: bytes
    ) -> None:
        _atomic_write(self.flow_path(provider_id, seed, level, sx, sy), data)
