"""Write `library/categories.json` -- THE QUERY SEAM for the game side.

    python tools/export_categories.py            # write it
    python tools/export_categories.py --check    # fail if it is stale

WHAT THIS IS FOR. A crafting system needs to enumerate "the items a player can
make", and that question has to have exactly one answer that is not "grep the
specs directory". `forge.categories.members("craftable", specs)` is the Python
half; this file is the half that does not need Python, and both go through
`forge.categories.of`, so a crafting system and the app cannot disagree about
what is craftable.

WHY IT IS NOT IN THE VXM MANIFEST. `species.vxm` is worldgen input: it carries
per-kind x per-biome densities for the deterministic per-chunk scatter, and its
`KIND_ORDER` mirrors `assetmanifest.h`, an append-only ENGINE contract. A
craftable has no density, no biome and no scatter -- it is refused from that
manifest by name (`manifest.KINDS_ENTITY`), deliberately. Putting a crafting
index in there would mean appending a kind to an engine contract to describe
something the engine's world composition must never see. So this is a separate,
smaller, plain-JSON file next to the grids it points at.

WHAT IT POINTS AT. For a craftable there is no bank, so the shipping grid is the
library individual: `library/<name>/<name>-<seed>/tree.vxa`. Paths are relative
to the asset-forge root and are only emitted when the file is ON DISK -- an
index that lists a path nothing wrote is worse than an index missing a row,
because the first one fails at load time in the game and the second fails here.

REFUSALS ARE LISTED, NOT DROPPED. A species whose `category` block is illegible
resolves to nothing (`forge.categories.clean`), and it goes in `refused` with
the reason rather than quietly vanishing from every category. A species that
disappears from an index is invisible; a species in a refusal list has somebody
to tell.
"""
import argparse
import json
import sys
from pathlib import Path

import _path  # noqa: F401  (sys.path bootstrap)
from forge import categories as cat, spec as sm

ROOT = Path(__file__).resolve().parents[1]
SPECS = ROOT / "specs"
LIBRARY = ROOT / "library"
OUT = LIBRARY / "categories.json"

FORMAT = "asset-forge-categories"
VERSION = 1


def grids_for(name: str) -> list[dict]:
    """Every built individual of a species that is actually on disk."""
    out = []
    d = LIBRARY / name
    if not d.is_dir():
        return out
    for entry in sorted(d.iterdir()):
        vxa = entry / "tree.vxa"
        if not entry.is_dir() or not vxa.is_file():
            continue
        seed = entry.name.rsplit("-", 1)[-1]
        row = {"seed": int(seed) if seed.isdigit() else None,
               "vxa": vxa.relative_to(ROOT).as_posix(),
               "bytes": vxa.stat().st_size}
        meta = entry / "meta.json"
        if meta.is_file():
            try:
                st = (json.loads(meta.read_text(encoding="utf-8")).get("stats")
                      or {})
                row["voxels"] = st.get("voxels")
                row["extent_vox"] = st.get("extent_vox")
            except (OSError, ValueError):
                pass
        out.append(row)
    return out


def build() -> dict:
    doc = {
        "format": FORMAT,
        "version": VERSION,
        "note": ("Generated by tools/export_categories.py. THE SEAM: read "
                 "categories.craftable.species to enumerate craftable items. "
                 "Paths are relative to the asset-forge root. voxel_mm is the "
                 "asset's own pitch -- nothing in voxel-core resamples, so a "
                 "grid read at the wrong pitch is not an error, it is an "
                 "object at the wrong size."),
        "categories": {},
        "refused": [],
    }
    for c in cat.CATEGORIES:
        doc["categories"][c.key] = {
            "label": c.label, "blurb": c.blurb,
            "kinds": list(c.kinds),
            "scattered": c.scattered, "in_manifest": c.in_manifest,
            "species": [],
        }
    for p in sorted(SPECS.glob("*.json")):
        body, _rep = sm.load(p)
        key = cat.of(body)
        if key is None:
            doc["refused"].append(
                {"name": p.stem, "kind": body.get("kind"),
                 "why": f"category resolves to nothing ({cat.source_of(body)})"})
            continue
        row = {"name": p.stem, "kind": sm.get(body, "kind"),
               "voxel_mm": float(sm.get(body, "resolution_cm")) * 10,
               "via": cat.source_of(body),
               "curation": sm.curation(body)["status"]}
        if body.get("subcategory"):
            row["subcategory"] = body["subcategory"]
        grids = grids_for(p.stem)
        if grids:
            row["grids"] = grids
        doc["categories"][key]["species"].append(row)
    for c in doc["categories"].values():
        c["species"].sort(key=lambda r: r["name"])
        c["count"] = len(c["species"])
    return doc


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the file on disk is not what today's specs "
                         "would produce, instead of writing it")
    args = ap.parse_args()
    doc = build()
    text = json.dumps(doc, indent=1, sort_keys=True) + "\n"
    if args.check:
        if not OUT.is_file():
            print(f"export_categories --check: FAIL -- {OUT} does not exist")
            return 1
        same = OUT.read_text(encoding="utf-8") == text
        print(f"  {sum(c['count'] for c in doc['categories'].values())} species "
              f"in {len(doc['categories'])} categories, "
              f"{len(doc['refused'])} refused")
        print("export_categories --check:",
              "PASS" if same else "FAIL -- library/categories.json is STALE; "
                                  "run tools/export_categories.py")
        return 0 if same else 1
    LIBRARY.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    for key, c in doc["categories"].items():
        print(f"  {key:<12} {c['count']:>4} species  ({', '.join(c['kinds'])})")
    for r in doc["refused"]:
        print(f"  ! refused {r['name']}: {r['why']}")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
