# Creates the "Asset Forge" desktop shortcut (plan P1; owner rulings 1+2,
# 2026-09-05: name "Asset Forge", script + shortcut, no packaged exe).
#
#     powershell -ExecutionPolicy Bypass -File tools\install-shortcut.ps1
#
# The .lnk targets launch-asset-forge.ps1 in a visible console (ctrl-c is the
# shutdown) and uses the voxel-forge icon generated by tools/make_icon.py.
# Re-running overwrites the shortcut in place, so a moved checkout is fixed
# by running this once more.

$ErrorActionPreference = "Stop"

$launcher = Join-Path $PSScriptRoot "launch-asset-forge.ps1"
$icon = Join-Path $PSScriptRoot "asset-forge.ico"
if (-not (Test-Path $launcher)) { throw "launcher not found: $launcher" }
if (-not (Test-Path $icon)) { throw "icon not found: $icon (run: python tools\make_icon.py)" }

$desktop = [Environment]::GetFolderPath("Desktop")
$lnkPath = Join-Path $desktop "Asset Forge.lnk"

$shell = New-Object -ComObject WScript.Shell
$lnk = $shell.CreateShortcut($lnkPath)
$lnk.TargetPath = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
$lnk.Arguments = "-ExecutionPolicy Bypass -File `"$launcher`""
$lnk.WorkingDirectory = Split-Path $PSScriptRoot -Parent
$lnk.IconLocation = "$icon,0"
$lnk.Description = "Asset Forge - procedural voxel assets for the sim (ctrl-c in the console stops it)"
$lnk.Save()

Write-Host "created $lnkPath"
Write-Host "  target  $($lnk.TargetPath)"
Write-Host "  args    $($lnk.Arguments)"
Write-Host "  icon    $icon"
