"""Common name -> binomial for every tree spec, hand-checked.

The land-animal work found GBIF resolving `lion` to *Macaca silenus* and that
mapping passing every downstream quality test, so this file is deliberately a
hand-written table and not a lookup. Where a spec names no species -- a generic
snag, a generic emergent -- the entry is None and it is skipped rather than
approximated. See docs/plant-proportion-research.md.
"""
TREES = {
 "alpine-krummholz":   ("Pinus mugo", "generic krummholz form; mugo pine is the archetype"),
 "american-beech":     ("Fagus grandifolia", ""),
 "baobab":             ("Adansonia digitata", ""),
 "beach-hibiscus":     ("Hibiscus tiliaceus", ""),
 "bigleaf-maple":      ("Acer macrophyllum", ""),
 "birch":              ("Betula pendula", "generic 'birch'"),
 "black-cherry":       ("Prunus serotina", ""),
 "black-mangrove":     ("Avicennia germinans", ""),
 "bur-oak":            ("Quercus macrocarpa", ""),
 "casuarina":          ("Casuarina equisetifolia", ""),
 "cecropia":           ("Cecropia", "genus-level"),
 "cherry-blossom":     ("Prunus serrulata", "ornamental cultivar group"),
 "coast-palm":         ("Cocos nucifera", "palm - no secondary thickening"),
 "columnar-cypress":   ("Cupressus sempervirens", "'Stricta' cultivar habit"),
 "common-alder":       ("Alnus glutinosa", ""),
 "common-ash":         ("Fraxinus excelsior", ""),
 "cork-oak":           ("Quercus suber", ""),
 "crab-apple":         ("Malus sylvestris", ""),
 "date-palm":          ("Phoenix dactylifera", "palm"),
 "desert-dead":        (None, "generic dead snag - no species"),
 "desert-ironwood":    ("Olneya tesota", ""),
 "douglas-fir":        ("Pseudotsuga menziesii", ""),
 "doum-palm":          ("Hyphaene thebaica", "palm"),
 "eastern-cottonwood": ("Populus deltoides", ""),
 "eastern-hemlock":    ("Tsuga canadensis", ""),
 "european-beech":     ("Fagus sylvatica", ""),
 "european-yew":       ("Taxus baccata", ""),
 "fever-tree":         ("Vachellia xanthophloea", "syn. Acacia xanthophloea"),
 "field-elm":          ("Ulmus minor", ""),
 "field-maple":        ("Acer campestre", ""),
 "flowering-dogwood":  ("Cornus florida", ""),
 "hawthorn-scrub":     ("Crataegus monogyna", ""),
 "hero-sequoia":       ("Sequoiadendron giganteum", ""),
 "holm-oak":           ("Quercus ilex", ""),
 "honey-locust":       ("Gleditsia triacanthos", ""),
 "hornbeam":           ("Carpinus betulus", ""),
 "jackalberry":        ("Diospyros mespiliformis", ""),
 "japanese-maple":     ("Acer palmatum", ""),
 "joshua-tree":        ("Yucca brevifolia", "arborescent monocot"),
 "jungle-emergent":    (None, "generic emergent - no species"),
 "kapok":              ("Ceiba pentandra", ""),
 "maritime-pine":      ("Pinus pinaster", ""),
 "marula":             ("Sclerocarya birrea", ""),
 "monterey-cypress":   ("Hesperocyparis macrocarpa", "syn. Cupressus macrocarpa"),
 "mopane":             ("Colophospermum mopane", ""),
 "norway-spruce":      ("Picea abies", ""),
 "olive":              ("Olea europaea", ""),
 "quaking-aspen":      ("Populus tremuloides", ""),
 "red-mangrove":       ("Rhizophora mangle", ""),
 "river-broadleaf":    (None, "generic riparian broadleaf - no species"),
 "rowan":              ("Sorbus aucuparia", ""),
 "saguaro":            ("Carnegiea gigantea", "columnar cactus - not a tree"),
 "sausage-tree":       ("Kigelia africana", ""),
 "savanna-acacia":     ("Vachellia tortilis", "syn. Acacia tortilis, umbrella thorn"),
 "scots-pine":         ("Pinus sylvestris", ""),
 "screwpine":          ("Pandanus tectorius", "monocot"),
 "sea-grape":          ("Coccoloba uvifera", ""),
 "shagbark-hickory":   ("Carya ovata", ""),
 "siberian-larch":     ("Larix sibirica", ""),
 "sitka-spruce":       ("Picea sitchensis", ""),
 "small-leaved-lime":  ("Tilia cordata", ""),
 "stone-pine":         ("Pinus pinea", ""),
 "strangler-fig":      ("Ficus", "genus-level; many strangler species"),
 "sugar-maple":        ("Acer saccharum", ""),
 "sweet-chestnut":     ("Castanea sativa", ""),
 "sycamore-maple":     ("Acer pseudoplatanus", ""),
 "temperate-oak":      ("Quercus robur", "generic 'temperate oak'"),
 "temperate-sapling":  (None, "generic sapling - no species"),
 "tree-fern":          ("Dicksonia antarctica", "tree fern - no secondary thickening"),
 "tulip-tree":         ("Liriodendron tulipifera", ""),
 "tundra-pine":        ("Pinus sylvestris", "generic treeline pine"),
 "weeping-willow":     ("Salix babylonica", ""),
 "western-hemlock":    ("Tsuga heterophylla", ""),
 "western-red-cedar":  ("Thuja plicata", ""),
 "white-poplar":       ("Populus alba", ""),
 "wild-banana":        ("Musa acuminata", "giant herb, not a tree"),
 "wild-pear":          ("Pyrus pyraster", ""),
 "wych-elm":           ("Ulmus glabra", ""),
}
