#include "VoxelOceanActor.h"

#include "Camera/PlayerCameraManager.h"
#include "VoxelFrontEndPolicy.h" // IsWorldHeldForMenu -- backlog 0.0k
#include "Components/PostProcessComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/Scene.h" // FWeightedBlendable -- the post-process blendable list entry
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "UObject/ConstructorHelpers.h"
#include "VoxelCoords.h" // VoxelSizeUU -- the one UU-per-voxel constant, for the UU -> m conversion
#include "VoxelEarth.h"
#include "VoxelSkySubsystem.h" // SetUnderwaterFogSuppression -- see the blend push below
#include "VoxelWaterSubsystem.h"
#include "VoxelWorldSubsystem.h"

// The one spelling of the material parameter name; see the header for why it is
// a named constant rather than a literal at the SetScalarParameterValue call.
const FName AVoxelOceanActor::ParamSubmergedDepthM(TEXT("SubmergedDepthM"));

namespace
{
// /Game/Voxel/M_Underwater, generated by ue-project/Tools/. Path spelled the
// same way M_Ocean's is below (package.object), because StaticLoadObject wants
// the object path and a package-only path silently resolves to nullptr.
const TCHAR* kUnderwaterMaterialPath = TEXT("/Game/Voxel/M_Underwater.M_Underwater");

// UU -> METRES, for the material's SubmergedDepthM parameter, which is
// documented in metres while everything on this side of the boundary is in UU.
//
// 1 UU = 1 cm by UE's own definition of an unreal unit, and the voxel
// convention pins the identical number from the other side: VoxelCoords.h fixes
// a voxel at VoxelCoords::VoxelSizeUU = 10 UU and voxelcore/core.h fixes the
// same voxel at vxc::kVoxelSizeMm = 100 mm, so 1 UU = 10 mm = 0.01 m. (Those
// two are held in lockstep by a static_assert in VoxelWorldSubsystem.cpp, which
// VoxelCoords.h names as the one translation unit allowed to include both
// headers -- which is why this file asserts only the half it can see rather
// than including voxelcore just to restate the pair.)
constexpr double kUUPerMetre = 100.0;
static_assert(VoxelCoords::VoxelSizeUU == 10.0,
              "VoxelCoords::VoxelSizeUU moved. kUUPerMetre above is derived from it against "
              "vxc::kVoxelSizeMm; re-derive it (see VoxelCoords.h's lockstep note) before trusting "
              "the UU->metre conversion fed to M_Underwater's SubmergedDepthM.");
} // namespace

AVoxelOceanActor::AVoxelOceanActor()
{
	PrimaryActorTick.bCanEverTick = true;

	OceanPlane = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("OceanPlane"));
	SetRootComponent(OceanPlane);
	OceanPlane->SetMobility(EComponentMobility::Movable); // recentred every tick, see UpdateFollowPlane
	OceanPlane->SetCollisionEnabled(ECollisionEnabled::NoCollision); // cosmetic only -- no gameplay forces yet (W1)
	OceanPlane->SetCastShadow(false);
	OceanPlane->SetReceivesDecals(false);

	static ConstructorHelpers::FObjectFinder<UStaticMesh> PlaneMeshFinder(TEXT("/Engine/BasicShapes/Plane.Plane"));
	if (PlaneMeshFinder.Succeeded())
	{
		OceanPlane->SetStaticMesh(PlaneMeshFinder.Object);
	}
	const double Scale = PlaneSizeUU / SourcePlaneSizeUU;
	OceanPlane->SetRelativeScale3D(FVector(Scale, Scale, 1.0));

	// Loaded by path in BeginPlay-adjacent code below is the terrain
	// material's pattern; the ocean material is instead resolved here in the
	// constructor (StaticLoadObject works fine at CDO construction time too)
	// so OceanPlane never renders with the engine default material even for
	// one frame.
	UMaterialInterface* OceanMaterial = Cast<UMaterialInterface>(
		StaticLoadObject(UMaterialInterface::StaticClass(), nullptr, TEXT("/Game/Voxel/M_Ocean.M_Ocean")));
	if (OceanMaterial)
	{
		OceanPlane->SetMaterial(0, OceanMaterial);
	}
	// else: engine default material (visible, if untinted) -- matches the
	// terrain material's "never crash, just warn" fallback; warning logged in
	// BeginPlay once GetWorld()/logging is safe to call from an easily
	// greppable place.

	UnderwaterPostProcess = CreateDefaultSubobject<UPostProcessComponent>(TEXT("UnderwaterPostProcess"));
	UnderwaterPostProcess->SetupAttachment(RootComponent);
	UnderwaterPostProcess->bUnbound = true; // applies globally -- there's no volume to swim into, water is everywhere the water datum says it is
	UnderwaterPostProcess->BlendWeight = 0.f; // starts above water (see AVoxelEarthGameMode spawn height)

	// THE VIGNETTE STAYS, and it is the one part of the old treatment that was
	// never part of the disagreement. It is not a claim about what the water is
	// made of -- it is the mask/goggles cue, the darkening at the edge of vision
	// that reads as "your eyes are in a medium", and it is the same cue in a
	// mountain tarn as in the sea. The tint and the fog were claims about the
	// liquid; this is a claim about the viewer.
	UnderwaterPostProcess->Settings.bOverride_VignetteIntensity = true;
	UnderwaterPostProcess->Settings.VignetteIntensity = 0.6f;

	// SceneColorTint IS DELIBERATELY NOT SET HERE ANY MORE. It used to be
	// FLinearColor(0.05, 0.30, 0.35), unconditionally, from the CDO onward. It
	// is now only ever set as the FALLBACK for a missing M_Underwater, in
	// BeginPlay, so that the normal path cannot double up a flat tint on top of
	// the material's own extinction. Setting it here and clearing it there would
	// work too and is worse: the fallback would then be the invisible default
	// and the intended path the special case.
	//
	// The MID itself is created in BeginPlay rather than here. A constructor
	// runs on the CDO as well as on instances, and a UMaterialInstanceDynamic
	// created on a CDO is a real bug (it is not transient there and gets
	// serialized), which is why this does not follow M_Ocean's
	// load-in-the-constructor pattern immediately above -- that one loads a
	// plain UMaterialInterface, which is fine at CDO time, and it has a
	// first-frame reason to (the plane is visible on frame 0; this
	// post-process's weight is 0 on frame 0).
}

void AVoxelOceanActor::BeginPlay()
{
	Super::BeginPlay();

	if (OceanPlane && OceanPlane->GetMaterial(0) == nullptr)
	{
		UE_LOG(LogVoxelEarth, Warning,
		       TEXT("M_Ocean not found at /Game/Voxel/M_Ocean -- ocean plane using the engine default material."));
	}

	// --- THE UNDERWATER HEIGHT FOG IS GONE, ON PURPOSE ------------------------
	//
	// This is where an AExponentialHeightFog used to be spawned (transient,
	// hidden, shown by UpdateUnderwaterState) with FogDensity 0.08,
	// FogHeightFalloff 0 and a hand-picked inscattering colour of
	// (0.02, 0.14, 0.18). It is deleted rather than left dormant behind a flag,
	// and the deletion is the substance of this change rather than tidying
	// around it.
	//
	// WHY IT CANNOT COEXIST WITH THE MATERIAL. The fog and the post-process
	// material model the SAME physical thing -- light being lost between the
	// camera and whatever it is looking at -- so running both means the
	// extinction is applied twice. That is not merely "a bit too dark": the two
	// use different colours (the fog's teal against whatever the material
	// derives from depth) and different falloff shapes (the fog's is uniform,
	// because FogHeightFalloff was 0, against the material's per-pixel
	// depth-correct one), so the composite is a colour neither of them intended
	// and it drifts with view distance. Double-counting extinction with two
	// disagreeing colour tables is EXACTLY the disagreement this change exists
	// to remove; keeping the fog would fix the pond-versus-swimming mismatch and
	// then reintroduce it one layer up.
	//
	// AND THE FOG WAS THE MORE WRONG OF THE TWO. FogHeightFalloff = 0 means
	// uniform density at every altitude, which was defensible when the only
	// water was the ocean at a single datum and is simply false now that 2,049
	// lake basins sit at their own surfaces around ~1650 m. Its density and
	// colour were also tuned by eye at sea level with no volumetric model of the
	// water surface to agree with, so there is nothing in it worth carrying
	// forward -- no measurement, no derivation, just two numbers that looked
	// right in the sea in 2026.
	//
	// LEFT DORMANT WOULD HAVE BEEN WORSE THAN DELETED. A hidden fog actor that
	// nothing shows is a member, a spawn, a lifetime and a hidden/visible pair
	// of states that every future reader has to prove is dead, and the first
	// person to debug "why is there no underwater fog" turns it back on and gets
	// the double count with no comment attached to explain it.
	//
	// WHAT WOULD BRING IT BACK: nothing about fog specifically. If the material
	// turns out to need a cheap far-distance term the deferred pass cannot give
	// it, that term belongs IN the material, driven by the same depth, not in a
	// second actor with its own colour.

	// --- The underwater post-process material ---------------------------------
	//
	// Loaded here rather than in the constructor (CDO safety -- see the note at
	// the end of the constructor).
	UMaterialInterface* UnderwaterBase = Cast<UMaterialInterface>(
		StaticLoadObject(UMaterialInterface::StaticClass(), nullptr, kUnderwaterMaterialPath));
	if (UnderwaterBase && UnderwaterPostProcess)
	{
		UnderwaterMID = UMaterialInstanceDynamic::Create(UnderwaterBase, this);
	}
	if (UnderwaterMID && UnderwaterPostProcess)
	{
		// Weight 1.0 on the blendable itself; the fade in and out is carried by
		// the COMPONENT's BlendWeight (UpdateUnderwaterState), so there is one
		// place that decides how strongly the treatment applies rather than two
		// that multiply.
		//
		// FPostProcessSettings::AddBlendable is the sugar for this and does a
		// linear search to replace an existing entry for the same object; there
		// is exactly one blendable here and it is added exactly once, so the
		// direct Array.Add is the same thing without the search. If a second
		// blendable ever joins, switch to AddBlendable so re-adding is safe.
		//
		// .Get() rather than handing the TObjectPtr straight over:
		// FWeightedBlendable's constructor takes a UObject*, and going
		// TObjectPtr -> UMaterialInstanceDynamic* -> UObject* leans on a
		// user-defined conversion followed by a derived-to-base one. That is
		// legal, but it is the kind of thing that stops being legal when an
		// overload is added, and this is not a place worth being clever.
		UnderwaterPostProcess->Settings.WeightedBlendables.Array.Add(
			FWeightedBlendable(1.0f, UnderwaterMID.Get()));

		// THE MATERIAL'S OTHER THREE PARAMETERS ARE NOT SET FROM HERE, and that
		// is a decision rather than an oversight. M_Underwater authors
		// UnderwaterExtinctionScale (0.5), UnderwaterAmbientGain (1.0) and
		// UnderwaterAmbientColor as parameter defaults. Pushing values for them
		// from C++ would make this file the authority on the look and the
		// material's own defaults dead weight -- two sources of truth, with the
		// C++ one silently winning, which is the same shape of bug as the
		// hard-coded tint being removed. The actor drives only the thing the
		// material CANNOT know: where the camera is relative to the surface.
		//
		// If a tuning pass wants these live-editable, expose them as UPROPERTYs
		// here AND delete the defaults in the generator, so there is still one
		// owner.
		UE_LOG(LogVoxelEarth, Log,
		       TEXT("Ocean: underwater post-process material loaded from %s; depth-driven extinction is ACTIVE ")
		       TEXT("(parameter '%s', metres). The legacy constant SceneColorTint and the underwater height fog ")
		       TEXT("are both retired."),
		       kUnderwaterMaterialPath, *ParamSubmergedDepthM.ToString());
	}
	else if (UnderwaterPostProcess)
	{
		// FALLBACK, following the same "never crash, just warn" discipline
		// M_Ocean uses above and M_VoxelTerrain/M_WaterVoxel use elsewhere: a
		// missing material must not mean a missing effect. The old constant tint
		// comes back verbatim.
		//
		// IT IS KNOWN TO BE WRONG and the warning says so, because a silent
		// fallback here would look exactly like the bug being fixed and someone
		// would spend a session re-diagnosing it: these numbers were tuned for
		// the ocean at sea level and are the reason a lake at ~1650 m reads as a
		// different liquid from inside than from outside.
		UnderwaterPostProcess->Settings.bOverride_SceneColorTint = true;
		UnderwaterPostProcess->Settings.SceneColorTint = FLinearColor(0.05f, 0.30f, 0.35f);
		UE_LOG(LogVoxelEarth, Warning,
		       TEXT("M_Underwater not found at %s -- falling back to the legacy constant SceneColorTint ")
		       TEXT("(0.05, 0.30, 0.35). That constant was tuned for the OCEAN at sea level and does not match ")
		       TEXT("what the lake surface material draws at altitude, so underwater shots taken in this state ")
		       TEXT("are not judgeable."),
		       kUnderwaterMaterialPath);
	}

	UpdateFollowPlane();
}

void AVoxelOceanActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	UpdateFollowPlane();
	UpdateUnderwaterState(DeltaTime);
}

void AVoxelOceanActor::UpdateFollowPlane()
{
	UWorld* World = GetWorld();
	APlayerController* PC = World ? World->GetFirstPlayerController() : nullptr;
	if (!PC)
	{
		return;
	}

	FVector CameraLoc;
	if (PC->PlayerCameraManager)
	{
		CameraLoc = PC->PlayerCameraManager->GetCameraLocation();
	}
	else if (APawn* P = PC->GetPawn())
	{
		CameraLoc = P->GetActorLocation();
	}
	else
	{
		return; // nothing to follow yet
	}

	const double SnappedX = FMath::GridSnap(CameraLoc.X, FollowSnapUU);
	const double SnappedY = FMath::GridSnap(CameraLoc.Y, FollowSnapUU);
	// The visual plane sits ON the datum, by name (voxelcore/core.h
	// kSeaLevelMm via UVoxelWaterSubsystem::SeaLevelZUU) rather than on a
	// literal 0 that happened to agree with it.
	SetActorLocation(FVector(SnappedX, SnappedY, UVoxelWaterSubsystem::SeaLevelZUU()));
}

void AVoxelOceanActor::UpdateUnderwaterState(float DeltaTime)
{
	UWorld* World = GetWorld();
	APlayerController* PC = World ? World->GetFirstPlayerController() : nullptr;
	if (!PC)
	{
		return;
	}

	// Held while the menu owns the screen -- the second offender of the pair in
	// backlog 0.0k, and the one that only appeared after the first was silenced.
	// The camera fallback below is the pawn's location, and during the menu
	// there is no pawn (bStartPlayersAsSpectators), so this ran its underwater
	// test at the world origin and faulted worldgen on an unbaked tile. There
	// is nothing to be underwater in front of while a menu is up.
	if (VoxelFrontEnd::IsWorldHeldForMenu(World))
	{
		return;
	}

	FVector CameraPos = FVector::ZeroVector;
	bool bHaveCamera = false;
	if (PC->PlayerCameraManager)
	{
		CameraPos = PC->PlayerCameraManager->GetCameraLocation();
		bHaveCamera = true;
	}
	else if (APawn* P = PC->GetPawn())
	{
		CameraPos = P->GetActorLocation();
		bHaveCamera = true;
	}
	if (!bHaveCamera)
	{
		return;
	}
	const double CameraZ = CameraPos.Z;

	// WAS `CameraZ < 0.0`, with nothing else consulted. A dry cavern below sea
	// level -- which this world has plenty of, caves.h only refuses to carve
	// AT or below the datum, not above it under a valley floor -- got full
	// underwater fog and the tinted post-process, and the post-process is
	// `bUnbound = true`, so the tint was global. See
	// UVoxelWaterSubsystem::IsUnderwaterAtWorld for what replaces it and what
	// it still cannot tell apart (docs/watershed-system-plan.md §5.3).
	UVoxelWaterSubsystem* Water = World->GetSubsystem<UVoxelWaterSubsystem>();
	bool bNowUnderwater;
	if (Water)
	{
		bNowUnderwater = Water->IsUnderwaterAtWorld(CameraPos);
	}
	else if (UVoxelWorldSubsystem* Terrain = World->GetSubsystem<UVoxelWorldSubsystem>())
	{
		// No water simulation in this world (the transient loading world, or a
		// stripped configuration): the ocean datum alone, which is still the
		// terrain-aware test rather than the camera one.
		bNowUnderwater = UVoxelWaterSubsystem::IsOpenSeaAtWorld(
			CameraZ, Terrain->GetSurfaceHeightUU(CameraPos.X, CameraPos.Y));
	}
	else
	{
		bNowUnderwater = false;
	}

	// --- The depth handed to the material -------------------------------------
	//
	// Refreshed BEFORE the transition log below, so an "entered water" line
	// reports the depth of the frame it entered on rather than the previous
	// frame's stale value.
	//
	// Only refreshed while actually submerged; see LastSubmergedDepthM's comment
	// in the header for why it is frozen rather than re-queried during the fade
	// out (the query correctly answers 0 above the surface, and pushing that
	// mid-fade would collapse the extinction in one frame -- the exit pop, at
	// the exit).
	//
	// bNowUnderwater, not bUnderwater: the edge below has not been consumed yet
	// at this point, and reading the stale flag here would skip the first
	// submerged frame's depth. The two are equal on every other frame.
	if (bNowUnderwater && Water)
	{
		LastSubmergedDepthM = float(Water->SubmergedDepthUUAtWorld(CameraPos) / kUUPerMetre);
	}
	if (UnderwaterMID)
	{
		// Pushed every tick, not only on change. A MID scalar set is a cheap
		// uniform write and the alternative -- tracking the last pushed value
		// and comparing -- would silently stop updating if anything else ever
		// touched the parameter.
		UnderwaterMID->SetScalarParameterValue(ParamSubmergedDepthM, LastSubmergedDepthM);
	}

	// --- THE TRANSITION EDGE, WHICH IS NO LONGER THE SAME THING AS "DO WORK" ---
	//
	// This function used to early-return whenever bNowUnderwater matched the
	// stored bUnderwater, because with a 0/1 snap there genuinely was nothing to
	// do between transitions. With a ramp and a per-tick depth push there is, so
	// the early return is gone and the LOG now has to be guarded by the edge
	// explicitly instead of getting that for free from the early return.
	//
	// Getting that wrong is not cosmetic. This line is the only observable
	// signal for this branch in an unattended screenshot run (task spec: verify
	// via log lines instead of a second screenshot), and one line per frame at
	// 60 fps would bury the rest of the run's output in a few seconds of
	// swimming -- turning the one instrument into noise.
	if (bNowUnderwater != bUnderwater)
	{
		bUnderwater = bNowUnderwater;

		// The ground height goes in the line because it is HALF THE ANSWER: a
		// transition at z=-500 over ground at +12000 would be the old
		// camera-only bug returning (see the paragraph above the predicate).
		//
		// The depth and which treatment is live are in the line for the same
		// reason -- an underwater screenshot that looks wrong now has two more
		// possible causes than it used to (a depth of 0.00 m at 30 m down means
		// the datum did not resolve and the material got nothing to work with;
		// "legacy constant tint" means M_Underwater never loaded), and neither
		// is distinguishable from a shading problem in the image alone.
		const double GroundZ = World->GetSubsystem<UVoxelWorldSubsystem>()
		                           ? World->GetSubsystem<UVoxelWorldSubsystem>()->GetSurfaceHeightUU(CameraPos.X, CameraPos.Y)
		                           : 0.0;
		UE_LOG(LogVoxelEarth, Log,
		       TEXT("Ocean: camera %s water (camera z=%.1f UU, worldgen ground z=%.1f UU, sea z=%.1f UU, ")
		       TEXT("submerged depth %.2f m, treatment=%s, fogSuppression=%.2f)"),
		       bUnderwater ? TEXT("entered") : TEXT("exited"), CameraZ, GroundZ,
		       UVoxelWaterSubsystem::SeaLevelZUU(), LastSubmergedDepthM,
		       UnderwaterMID ? TEXT("M_Underwater") : TEXT("legacy constant tint"),
		       UnderwaterBlendWeight);
	}

	// --- The blend ------------------------------------------------------------
	//
	// FInterpConstantTo, not FInterpTo: a constant rate reaches the target in a
	// bounded, stated time (UnderwaterBlendSeconds) and arrives exactly, whereas
	// the exponential FInterpTo never quite arrives and its "speed" is not a
	// duration anyone can reason about from the call site. The duration is the
	// thing being specified here, so the interp that takes a duration is the
	// right one.
	//
	// DeltaTime is used as given -- no clamp. A hitch long enough to make this
	// jump straight to the target is a hitch the player already saw; smoothing
	// the water transition across it would be dishonest about when they entered.
	if (UnderwaterPostProcess)
	{
		const float Target = bUnderwater ? 1.f : 0.f;
		UnderwaterBlendWeight = FMath::FInterpConstantTo(UnderwaterBlendWeight, Target, DeltaTime,
		                                                 1.f / UnderwaterBlendSeconds);
		UnderwaterPostProcess->BlendWeight = UnderwaterBlendWeight;

		// THE SAME WEIGHT suppresses the atmospheric height fog (fog plan,
		// 2026-08-20). One number drives both transitions so the two extinction
		// models -- air fog above, Beer-Lambert below -- CROSS-FADE and can
		// never sum at full strength, which is the double-count the old height
		// fog was deleted for (:133-164 above). Pushed every tick the blend is
		// live rather than only on transitions, because the fade itself is the
		// window where double-counting would happen.
		//
		// Direction of dependency: the OCEAN pushes to the sky, never the
		// reverse -- the sky must not know oceans exist (it works in ocean-less
		// worlds; suppression just stays 0 there). Same lifetime reasoning as
		// the exposure-ownership rule in VoxelSkySubsystem.cpp.
		if (UWorld* FogWorld = GetWorld())
		{
			if (UVoxelSkySubsystem* Sky = FogWorld->GetSubsystem<UVoxelSkySubsystem>())
			{
				Sky->SetUnderwaterFogSuppression(UnderwaterBlendWeight);
			}
		}
	}
}
