#include "VoxelOceanActor.h"

#include "VoxelClipmapActor.h" // NumLevels, for the plane-extent static_assert

#include "Camera/PlayerCameraManager.h"
#include "VoxelFrontEndPolicy.h" // IsWorldHeldForMenu -- backlog 0.0k
#include "Components/PostProcessComponent.h"
#include "Engine/Scene.h" // FWeightedBlendable -- the post-process blendable list entry
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "ProceduralMeshComponent.h" // the ring grid; see the header's 2026-09-04 note
#include "VoxelCoords.h" // VoxelSizeUU -- the one UU-per-voxel constant, for the UU -> m conversion
#include "VoxelEarth.h"
#include "VoxelSkySubsystem.h" // SetUnderwaterFogSuppression -- see the blend push below
#include "VoxelWaterSubsystem.h"
#include "VoxelWorldSubsystem.h"

#include "HAL/IConsoleManager.h"

// ---------------------------------------------------------------------------
// CONSOLE VARIABLES
// ---------------------------------------------------------------------------
//
// The player-facing "Ocean Mesh Detail" row fronts this
// (VoxelGraphicsUserSettings). It is an int rather than a bool because the
// detail ladder is a seed CELL SIZE and there is an obvious third rung
// (quarter detail) if one is ever wanted; a bool would have to be replaced
// rather than extended, and the persisted key would then mean two things.
//
// READ AT BUILD TIME, and the build is what Tick triggers when this no longer
// matches what is on screen. It is deliberately not read anywhere else: every
// other use of the cell size goes through BuiltCellUU, so a cvar changed
// mid-frame cannot make the follow-snap disagree with the geometry it is
// snapping.
TAutoConsoleVariable<int32> CVarVoxelOceanHalfDetail(
	TEXT("voxel.Ocean.HalfDetail"), 0,
	TEXT("Ocean surface mesh detail. 0 (default) builds the ring grid on a 1.5 m finest cell -- ")
	TEXT("~40 k vertices, matching the lake sheet's fine band so ocean and lake carry wave ")
	TEXT("displacement at the same density. 1 doubles the seed cell to 3.0 m and derives the whole ")
	TEXT("ring ladder from there: about a quarter of the centre patch's vertices, one ring fewer, ")
	TEXT("and the same reach (the reach is asserted for BOTH levels in VoxelOceanActor.h). Only ")
	TEXT("the centre patch carries visible waves -- the material fades World Position Offset to ")
	TEXT("zero by 72 m -- so this trades wave resolution underfoot, not horizon quality. Changing ")
	TEXT("it rebuilds the grid once, on the next tick."),
	ECVF_Default);

// The one spelling of the material parameter name; see the header for why it is
// a named constant rather than a literal at the SetScalarParameterValue call.
const FName AVoxelOceanActor::ParamSubmergedDepthM(TEXT("SubmergedDepthM"));

namespace
{
// /Game/Voxel/M_Underwater, generated by ue-project/Tools/. Path spelled the
// same way M_Ocean's is below (package.object), because StaticLoadObject wants
// the object path and a package-only path silently resolves to nullptr.
const TCHAR* kUnderwaterMaterialPath = TEXT("/Game/Voxel/M_Underwater.M_Underwater");

// UU -> METRES, for the material's SubmergedDepthM parameter, which is
// documented in metres while everything on this side of the boundary is in UU.
//
// 1 UU = 1 cm by UE's own definition of an unreal unit, and the voxel
// convention pins the identical number from the other side: VoxelCoords.h fixes
// a voxel at VoxelCoords::VoxelSizeUU = 10 UU and voxelcore/core.h fixes the
// same voxel at vxc::kVoxelSizeMm = 100 mm, so 1 UU = 10 mm = 0.01 m. (Those
// two are held in lockstep by a static_assert in VoxelWorldSubsystem.cpp, which
// VoxelCoords.h names as the one translation unit allowed to include both
// headers -- which is why this file asserts only the half it can see rather
// than including voxelcore just to restate the pair.)
constexpr double kUUPerMetre = 100.0;
static_assert(VoxelCoords::VoxelSizeUU == 10.0,
              "VoxelCoords::VoxelSizeUU moved. kUUPerMetre above is derived from it against "
              "vxc::kVoxelSizeMm; re-derive it (see VoxelCoords.h's lockstep note) before trusting "
              "the UU->metre conversion fed to M_Underwater's SubmergedDepthM.");
} // namespace

AVoxelOceanActor::AVoxelOceanActor()
{
	PrimaryActorTick.bCanEverTick = true;

	OceanMesh = CreateDefaultSubobject<UProceduralMeshComponent>(TEXT("OceanPlane"));
	SetRootComponent(OceanMesh);
	OceanMesh->SetMobility(EComponentMobility::Movable); // recentred every tick, see UpdateFollowPlane
	OceanMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision); // cosmetic only -- no gameplay forces yet (W1)
	OceanMesh->bUseAsyncCooking = false;
	OceanMesh->SetCastShadow(false);
	OceanMesh->SetReceivesDecals(false);
	// SUBOBJECT NAME KEPT AS "OceanPlane" ON PURPOSE, even though the member is
	// now OceanMesh and the mesh is not a plane. A CreateDefaultSubobject name
	// is serialized identity, and renaming it orphans the subobject in anything
	// that already holds a reference by name. The name is not documentation.

	// The ocean must reach at least as far as the clipmap draws ground (see
	// VoxelOcean::kReachDiameterUU). The multiple restates the clipmap's extent
	// arithmetic; NumLevels is the term that actually changes, so it is the
	// term asserted (HalfIndex/HoleHalfIndex are private and their ratio -- the
	// leading 2 -- has been fixed since the actor existed).
	static_assert(VoxelOcean::kClipmapExtentMultiple ==
	                  2.0 * double(int64(1) << (AVoxelClipmapActor::NumLevels - 1)),
	              "the ocean grid is sized to the clipmap's outer half-extent (2 * 2^(NumLevels-1) "
	              "ring edges); AVoxelClipmapActor::NumLevels moved without this multiple -- water "
	              "will end before the far terrain does");

	// Loaded by path in BeginPlay-adjacent code below is the terrain
	// material's pattern; the ocean material is instead resolved here in the
	// constructor (StaticLoadObject works fine at CDO construction time too)
	// so the mesh never renders with the engine default material even for
	// one frame. ONE MATERIAL SLOT, index 0, on every section -- the sections
	// are LOD rings of one surface, not different surfaces.
	UMaterialInterface* OceanMaterial = Cast<UMaterialInterface>(
		StaticLoadObject(UMaterialInterface::StaticClass(), nullptr, TEXT("/Game/Voxel/M_Ocean.M_Ocean")));
	if (OceanMaterial)
	{
		OceanMesh->SetMaterial(0, OceanMaterial);
	}
	// else: engine default material (visible, if untinted) -- matches the
	// terrain material's "never crash, just warn" fallback; warning logged in
	// BeginPlay once GetWorld()/logging is safe to call from an easily
	// greppable place.

	UnderwaterPostProcess = CreateDefaultSubobject<UPostProcessComponent>(TEXT("UnderwaterPostProcess"));
	UnderwaterPostProcess->SetupAttachment(RootComponent);
	UnderwaterPostProcess->bUnbound = true; // applies globally -- there's no volume to swim into, water is everywhere the water datum says it is
	UnderwaterPostProcess->BlendWeight = 0.f; // starts above water (see AVoxelEarthGameMode spawn height)

	// THE VIGNETTE STAYS, and it is the one part of the old treatment that was
	// never part of the disagreement. It is not a claim about what the water is
	// made of -- it is the mask/goggles cue, the darkening at the edge of vision
	// that reads as "your eyes are in a medium", and it is the same cue in a
	// mountain tarn as in the sea. The tint and the fog were claims about the
	// liquid; this is a claim about the viewer.
	UnderwaterPostProcess->Settings.bOverride_VignetteIntensity = true;
	UnderwaterPostProcess->Settings.VignetteIntensity = 0.6f;

	// SceneColorTint IS DELIBERATELY NOT SET HERE ANY MORE. It used to be
	// FLinearColor(0.05, 0.30, 0.35), unconditionally, from the CDO onward. It
	// is now only ever set as the FALLBACK for a missing M_Underwater, in
	// BeginPlay, so that the normal path cannot double up a flat tint on top of
	// the material's own extinction. Setting it here and clearing it there would
	// work too and is worse: the fallback would then be the invisible default
	// and the intended path the special case.
	//
	// The MID itself is created in BeginPlay rather than here. A constructor
	// runs on the CDO as well as on instances, and a UMaterialInstanceDynamic
	// created on a CDO is a real bug (it is not transient there and gets
	// serialized), which is why this does not follow M_Ocean's
	// load-in-the-constructor pattern immediately above -- that one loads a
	// plain UMaterialInterface, which is fine at CDO time, and it has a
	// first-frame reason to (the plane is visible on frame 0; this
	// post-process's weight is 0 on frame 0).
}

void AVoxelOceanActor::BeginPlay()
{
	Super::BeginPlay();

	if (OceanMesh && OceanMesh->GetMaterial(0) == nullptr)
	{
		UE_LOG(LogVoxelEarth, Warning,
		       TEXT("M_Ocean not found at /Game/Voxel/M_Ocean -- ocean surface using the engine default material."));
	}

	// THE GRID, ONCE. Before UpdateFollowPlane at the end of this function, so
	// the first frame draws real geometry at the right place rather than an
	// empty component that pops in on tick 2.
	BuildOceanGrid();

	// --- THE UNDERWATER HEIGHT FOG IS GONE, ON PURPOSE ------------------------
	//
	// This is where an AExponentialHeightFog used to be spawned (transient,
	// hidden, shown by UpdateUnderwaterState) with FogDensity 0.08,
	// FogHeightFalloff 0 and a hand-picked inscattering colour of
	// (0.02, 0.14, 0.18). It is deleted rather than left dormant behind a flag,
	// and the deletion is the substance of this change rather than tidying
	// around it.
	//
	// WHY IT CANNOT COEXIST WITH THE MATERIAL. The fog and the post-process
	// material model the SAME physical thing -- light being lost between the
	// camera and whatever it is looking at -- so running both means the
	// extinction is applied twice. That is not merely "a bit too dark": the two
	// use different colours (the fog's teal against whatever the material
	// derives from depth) and different falloff shapes (the fog's is uniform,
	// because FogHeightFalloff was 0, against the material's per-pixel
	// depth-correct one), so the composite is a colour neither of them intended
	// and it drifts with view distance. Double-counting extinction with two
	// disagreeing colour tables is EXACTLY the disagreement this change exists
	// to remove; keeping the fog would fix the pond-versus-swimming mismatch and
	// then reintroduce it one layer up.
	//
	// AND THE FOG WAS THE MORE WRONG OF THE TWO. FogHeightFalloff = 0 means
	// uniform density at every altitude, which was defensible when the only
	// water was the ocean at a single datum and is simply false now that 2,049
	// lake basins sit at their own surfaces around ~1650 m. Its density and
	// colour were also tuned by eye at sea level with no volumetric model of the
	// water surface to agree with, so there is nothing in it worth carrying
	// forward -- no measurement, no derivation, just two numbers that looked
	// right in the sea in 2026.
	//
	// LEFT DORMANT WOULD HAVE BEEN WORSE THAN DELETED. A hidden fog actor that
	// nothing shows is a member, a spawn, a lifetime and a hidden/visible pair
	// of states that every future reader has to prove is dead, and the first
	// person to debug "why is there no underwater fog" turns it back on and gets
	// the double count with no comment attached to explain it.
	//
	// WHAT WOULD BRING IT BACK: nothing about fog specifically. If the material
	// turns out to need a cheap far-distance term the deferred pass cannot give
	// it, that term belongs IN the material, driven by the same depth, not in a
	// second actor with its own colour.

	// --- The underwater post-process material ---------------------------------
	//
	// Loaded here rather than in the constructor (CDO safety -- see the note at
	// the end of the constructor).
	UMaterialInterface* UnderwaterBase = Cast<UMaterialInterface>(
		StaticLoadObject(UMaterialInterface::StaticClass(), nullptr, kUnderwaterMaterialPath));
	if (UnderwaterBase && UnderwaterPostProcess)
	{
		UnderwaterMID = UMaterialInstanceDynamic::Create(UnderwaterBase, this);
	}
	if (UnderwaterMID && UnderwaterPostProcess)
	{
		// Weight 1.0 on the blendable itself; the fade in and out is carried by
		// the COMPONENT's BlendWeight (UpdateUnderwaterState), so there is one
		// place that decides how strongly the treatment applies rather than two
		// that multiply.
		//
		// FPostProcessSettings::AddBlendable is the sugar for this and does a
		// linear search to replace an existing entry for the same object; there
		// is exactly one blendable here and it is added exactly once, so the
		// direct Array.Add is the same thing without the search. If a second
		// blendable ever joins, switch to AddBlendable so re-adding is safe.
		//
		// .Get() rather than handing the TObjectPtr straight over:
		// FWeightedBlendable's constructor takes a UObject*, and going
		// TObjectPtr -> UMaterialInstanceDynamic* -> UObject* leans on a
		// user-defined conversion followed by a derived-to-base one. That is
		// legal, but it is the kind of thing that stops being legal when an
		// overload is added, and this is not a place worth being clever.
		UnderwaterPostProcess->Settings.WeightedBlendables.Array.Add(
			FWeightedBlendable(1.0f, UnderwaterMID.Get()));

		// THE MATERIAL'S OTHER THREE PARAMETERS ARE NOT SET FROM HERE, and that
		// is a decision rather than an oversight. M_Underwater authors
		// UnderwaterExtinctionScale (0.5), UnderwaterAmbientGain (1.0) and
		// UnderwaterAmbientColor as parameter defaults. Pushing values for them
		// from C++ would make this file the authority on the look and the
		// material's own defaults dead weight -- two sources of truth, with the
		// C++ one silently winning, which is the same shape of bug as the
		// hard-coded tint being removed. The actor drives only the thing the
		// material CANNOT know: where the camera is relative to the surface.
		//
		// If a tuning pass wants these live-editable, expose them as UPROPERTYs
		// here AND delete the defaults in the generator, so there is still one
		// owner.
		UE_LOG(LogVoxelEarth, Log,
		       TEXT("Ocean: underwater post-process material loaded from %s; depth-driven extinction is ACTIVE ")
		       TEXT("(parameter '%s', metres). The legacy constant SceneColorTint and the underwater height fog ")
		       TEXT("are both retired."),
		       kUnderwaterMaterialPath, *ParamSubmergedDepthM.ToString());
	}
	else if (UnderwaterPostProcess)
	{
		// FALLBACK, following the same "never crash, just warn" discipline
		// M_Ocean uses above and M_VoxelTerrain/M_WaterVoxel use elsewhere: a
		// missing material must not mean a missing effect. The old constant tint
		// comes back verbatim.
		//
		// IT IS KNOWN TO BE WRONG and the warning says so, because a silent
		// fallback here would look exactly like the bug being fixed and someone
		// would spend a session re-diagnosing it: these numbers were tuned for
		// the ocean at sea level and are the reason a lake at ~1650 m reads as a
		// different liquid from inside than from outside.
		UnderwaterPostProcess->Settings.bOverride_SceneColorTint = true;
		UnderwaterPostProcess->Settings.SceneColorTint = FLinearColor(0.05f, 0.30f, 0.35f);
		UE_LOG(LogVoxelEarth, Warning,
		       TEXT("M_Underwater not found at %s -- falling back to the legacy constant SceneColorTint ")
		       TEXT("(0.05, 0.30, 0.35). That constant was tuned for the OCEAN at sea level and does not match ")
		       TEXT("what the lake surface material draws at altitude, so underwater shots taken in this state ")
		       TEXT("are not judgeable."),
		       kUnderwaterMaterialPath);
	}

	UpdateFollowPlane();
}

void AVoxelOceanActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	// menu tick gate 2026-09-07 (docs/backlog.md §0.0o-adjacent): BuildOceanGrid
	// and UpdateFollowPlane below are real per-frame mesh rebuild / transform
	// work with no camera-relative water surface to follow while the front
	// end holds the world (UpdateUnderwaterState already gates itself at
	// :733-ish below; this early return makes that redundant but harmless).
	// -VoxelMenuTickGates=0 is the A/B off arm: same build, this early return
	// never taken.
	if (VoxelFrontEnd::MenuTickGatesEnabled() && VoxelFrontEnd::IsWorldHeldForMenu(GetWorld()))
	{
		return;
	}

	// ---- THE DETAIL TOGGLE, CHECKED AGAINST THE MESH AND NOT AGAINST A FLAG --
	//
	// One integer compare per tick, and it is the whole rebuild trigger. The
	// question asked is "is what is on screen made of what the cvar says?", so
	// there is no way for a writer of the cvar (the settings row, the console,
	// an -ExecCmds line) to forget to announce itself -- a state that cannot be
	// forgotten is worth a compare a frame.
	//
	// BEFORE UpdateFollowPlane, so the transform applied this tick snaps to the
	// cell size of the grid that is about to be drawn rather than the one that
	// has just been thrown away.
	const int32 WantHalfDetail = CVarVoxelOceanHalfDetail.GetValueOnGameThread() != 0 ? 1 : 0;
	if (WantHalfDetail != BuiltHalfDetail)
	{
		BuildOceanGrid();
	}

	UpdateFollowPlane();
	UpdateUnderwaterState(DeltaTime);
}

namespace
{
// ============================================================================
// ONE LEVEL OF THE RING GRID
// ============================================================================
//
// A square annulus of cells, all the same size, with a square hole in the
// middle -- or, when HoleAcrossCells is 0, a solid patch (the centre).
// Everything is in MESH-LOCAL UU around (0,0); the actor's transform puts it
// under the camera.
//
// --- THE STITCH, WHICH IS THE ONLY SUBTLE PART ------------------------------
//
// This level's hole is exactly filled by the level inside it, whose cells are
// HALF the size. So along the hole's boundary the fine side has a vertex at the
// midpoint of every coarse edge, and the coarse side does not: that is a
// T-junction, and a T-junction is invisible until the two sides are displaced
// by different amounts -- which is precisely what World Position Offset waves
// do. The crack opens exactly where the eye is already looking, at the LOD
// change, and it opens and closes with the swell.
//
// The fix is COARSE-SIDE INDEXING: this level adds the midpoint vertex itself
// on every edge it shares with the hole, and triangulates those boundary cells
// as a five-vertex fan instead of two triangles. The fine side is then untouched
// -- it emits its ordinary grid and never has to know it is being stitched to,
// which is what keeps every level's code the same code.
//
// The fan apex is always a corner NOT on the split edge. Fanning from an
// endpoint of the split edge produces a degenerate triangle (the midpoint is
// collinear with it), which the RHI will happily accept and which shows up as a
// missing sliver rather than as an error.
//
// --- WHAT THE VERTICES CARRY ------------------------------------------------
//
// The lake sheet's convention, deliberately identical (see
// VoxelWaterSheetActor.h): colour (255,255,255,0) = full fill, no AO, on the
// +Z boundary, no foam; up normal; (1,0,0) tangent; and UVs in METRES.
//
// THE UV IS MESH-LOCAL METRES, AND THAT IS A CONTRACT WITH THE MATERIAL. The
// sheet can anchor its UV at a fixed world corner because a sheet never moves;
// this mesh is recentred under the camera every tick, so a world-anchored UV
// cannot be baked into its vertices at all. TexCoord0 here therefore slides by
// whole finest cells (1.5 m) as the grid recentres. A wave module that reads
// TexCoord0 as a world position WILL swim; the shared module must derive its
// world anchor from absolute WorldPosition (which is what M_Ocean already does
// for its ripple term) and use TexCoord0 only for things that are legitimately
// mesh-relative.
void AppendOceanLevel(double CellUU, int32 HalfCells, int32 HoleAcrossCells, TArray<FVector>& Verts,
                      TArray<int32>& Tris, TArray<FVector>& Normals, TArray<FVector2D>& UVs,
                      TArray<FColor>& Colors, TArray<FProcMeshTangent>& Tangents)
{
	const int32 Side = 2 * HalfCells;      // cells across
	const int32 Stride = Side + 1;         // vertices across
	const int32 H0 = HalfCells - HoleAcrossCells / 2; // first hole cell index
	const int32 H1 = HalfCells + HoleAcrossCells / 2 - 1; // last hole cell index (inclusive)

	// Lazy vertex allocation. The frame of a ring uses well under half of its
	// bounding grid's vertices, and the hole's interior uses none at all; a map
	// of slots means only the ones an emitted triangle actually references get
	// built, with no second pass and no per-vertex search.
	TArray<int32> Slots;
	Slots.Init(INDEX_NONE, Stride * Stride);

	auto AddVertAt = [&](double X, double Y) -> int32
	{
		const int32 Index = Verts.Num();
		Verts.Add(FVector(X, Y, 0.0));
		Normals.Add(FVector::UpVector);
		Tangents.Add(FProcMeshTangent(1.f, 0.f, 0.f));
		UVs.Add(FVector2D(X / 100.0, Y / 100.0)); // METRES, mesh-local -- see above
		Colors.Add(FColor(255, 255, 255, 0));
		return Index;
	};

	auto Corner = [&](int32 i, int32 j) -> int32
	{
		int32& Slot = Slots[i + Stride * j];
		if (Slot == INDEX_NONE)
		{
			Slot = AddVertAt((double(i) - double(HalfCells)) * CellUU, (double(j) - double(HalfCells)) * CellUU);
		}
		return Slot;
	};

	for (int32 cj = 0; cj < Side; ++cj)
	{
		for (int32 ci = 0; ci < Side; ++ci)
		{
			if (HoleAcrossCells > 0 && ci >= H0 && ci <= H1 && cj >= H0 && cj <= H1)
			{
				continue; // the hole: the finer level inside fills it
			}

			// CCW in XY, matching AppendRectQuad's winding exactly so the ocean
			// and the lake sheets cannot end up with opposite facing.
			const int32 A = Corner(ci, cj);         // -x -y
			const int32 B = Corner(ci + 1, cj);     // +x -y
			const int32 C = Corner(ci + 1, cj + 1); // +x +y
			const int32 D = Corner(ci, cj + 1);     // -x +y

			// Which edge, if any, this cell shares with the hole. At most one:
			// the hole is convex, so the cell diagonally off a hole corner
			// touches it at a POINT (a shared corner vertex, no T-junction) and
			// needs no split.
			const bool bInSpan = (ci >= H0 && ci <= H1);
			const bool bJnSpan = (cj >= H0 && cj <= H1);
			const bool bSplitTop = HoleAcrossCells > 0 && bInSpan && cj == H0 - 1;    // D-C
			const bool bSplitBottom = HoleAcrossCells > 0 && bInSpan && cj == H1 + 1; // A-B
			const bool bSplitRight = HoleAcrossCells > 0 && bJnSpan && ci == H0 - 1;  // B-C
			const bool bSplitLeft = HoleAcrossCells > 0 && bJnSpan && ci == H1 + 1;   // D-A

			if (!bSplitTop && !bSplitBottom && !bSplitRight && !bSplitLeft)
			{
				Tris.Add(A); Tris.Add(B); Tris.Add(C);
				Tris.Add(A); Tris.Add(C); Tris.Add(D);
				continue;
			}

			const FVector PA = Verts[A], PB = Verts[B], PC = Verts[C], PD = Verts[D];
			int32 Poly[5];
			int32 Apex = 0;
			if (bSplitTop)
			{
				const int32 M = AddVertAt(0.5 * (PD.X + PC.X), 0.5 * (PD.Y + PC.Y));
				Poly[0] = A; Poly[1] = B; Poly[2] = C; Poly[3] = M; Poly[4] = D;
				Apex = 0; // A, not on D-C
			}
			else if (bSplitRight)
			{
				const int32 M = AddVertAt(0.5 * (PB.X + PC.X), 0.5 * (PB.Y + PC.Y));
				Poly[0] = A; Poly[1] = B; Poly[2] = M; Poly[3] = C; Poly[4] = D;
				Apex = 0; // A, not on B-C
			}
			else if (bSplitBottom)
			{
				const int32 M = AddVertAt(0.5 * (PA.X + PB.X), 0.5 * (PA.Y + PB.Y));
				Poly[0] = A; Poly[1] = M; Poly[2] = B; Poly[3] = C; Poly[4] = D;
				Apex = 3; // C, not on A-B
			}
			else // bSplitLeft
			{
				const int32 M = AddVertAt(0.5 * (PD.X + PA.X), 0.5 * (PD.Y + PA.Y));
				Poly[0] = A; Poly[1] = B; Poly[2] = C; Poly[3] = D; Poly[4] = M;
				Apex = 1; // B, not on D-A
			}
			for (int32 t = 0; t < 3; ++t)
			{
				Tris.Add(Poly[Apex]);
				Tris.Add(Poly[(Apex + t + 1) % 5]);
				Tris.Add(Poly[(Apex + t + 2) % 5]);
			}
		}
	}
}
} // namespace

void AVoxelOceanActor::BuildOceanGrid()
{
	if (!OceanMesh)
	{
		return;
	}

	// ---- THE DETAIL LEVEL, LATCHED ONCE FOR THE WHOLE BUILD -----------------
	//
	// Read exactly here and nowhere else in the function. Reading the cvar again
	// partway through would let a console write between two rings build a grid
	// whose inner half and outer half disagree about the cell size -- a seam
	// that would be geometrically wrong and would still log a healthy vertex
	// count, which is the shape of failure this file's log line exists to catch.
	const int32 HalfDetail = CVarVoxelOceanHalfDetail.GetValueOnGameThread() != 0 ? 1 : 0;
	const double SeedCellUU = VoxelOcean::CellUUForHalfDetail(HalfDetail != 0);
	const int32 RingCount = VoxelOcean::RingCountForReach(SeedCellUU);

	// What was on screen before this call, for the rebuild line below. Captured
	// before the counters are reset, because "40,017 -> 40,017" and
	// "40,017 -> 0" are the two answers the line has to be able to tell apart.
	const int32 PrevVertexCount = BuiltVertexCount;
	const int32 PrevSectionCount = BuiltSectionCount;
	const bool bRebuild = BuiltHalfDetail >= 0;

	// ---- THE ARITHMETIC, WRITTEN DOWN SO THE LOG LINE CAN BE JUDGED ---------
	//
	// At the shipped FULL-DETAIL constants (kCellUU 150, kCentreHalfUU 9600, min
	// ring half 22 cells, min width 10 cells, VoxelCoords::kNumLevels 8):
	//
	//   centre  128 x 128 cells   16,641 verts   32,768 tris   +-96 m
	//   ring 1  hole 64, half 42   3,512 verts    6,176 tris   +-126 m
	//   ring 2  hole 42, half 32   2,712 verts    4,832 tris   +-192 m
	//   ring 3  hole 32, half 26   1,976 verts    3,488 tris   +-312 m
	//   ring 4  hole 26, half 24   1,880 verts    3,360 tris   +-576 m
	//   ring 5  hole 24, half 22   1,592 verts    2,816 tris   +-1,056 m
	//   rings 6-12 (steady state)  1,672 verts    2,992 tris each, doubling
	//                                                           out to +-135 km
	//   TOTAL  40,017 verts, 74,384 tris, 13 sections
	//
	// Required reach is VoxelOcean::kRequiredHalfExtentUU = 81.92 km, so the
	// derived 135 km clears it with the whole of ring 12 to spare. The budget
	// this was designed against is the plan's 40-60 k vertices.
	//
	// AT HALF DETAIL (voxel.Ocean.HalfDetail=1, seed cell 300 UU) the same
	// derivation runs on a 64 x 64 centre patch and needs ONE RING FEWER for the
	// same reach -- which is exactly why the clear below is not optional. Every
	// number above is derived, so none of them is restated for that case: the
	// log line prints what was actually built and that is the thing to read.
	//
	// ONE SECTION PER LEVEL rather than one section for the lot: each level has
	// its own tight bounds, so a camera at sea level looking at the horizon can
	// cull the levels behind it, and a level that failed to build shows up as a
	// missing section in the log instead of as a silently short vertex count.
	// The cost is 13 draws for the ocean, all with the same material.
	TArray<FVector> Verts;
	TArray<int32> Tris;
	TArray<FVector> Normals;
	TArray<FVector2D> UVs;
	TArray<FColor> Colors;
	TArray<FProcMeshTangent> Tangents;

	BuiltVertexCount = 0;
	BuiltTriangleCount = 0;
	BuiltSectionCount = 0;

	// Captured ONCE, and BEFORE the clear: PMC grows its material array with the
	// sections, and reading slot 0 back mid-loop would make the material
	// assignment depend on that growth behaviour. Before the clear rather than
	// merely before the loop because slot 0 is the one thing being read out of
	// the component that the clear could plausibly disturb -- and a rebuild that
	// silently dropped the ocean material would look like a lighting bug.
	UMaterialInterface* const OceanMaterial = OceanMesh->GetMaterial(0);

	// EVERY SECTION GOES, and the reason is in the header: the two detail levels
	// build a different NUMBER of sections, so overwriting by index would leave
	// the last ring of the previous grid drawn at its old cell size -- a stale
	// annulus of water at the horizon, z-fighting nothing and matching nothing.
	// Harmless on the BeginPlay call (there is nothing to clear), which is what
	// makes this function safe to call twice.
	OceanMesh->ClearAllMeshSections();

	int32 HalfCells = int32(VoxelOcean::kCentreHalfUU / SeedCellUU);
	double CellUU = SeedCellUU;
	double HalfUU = VoxelOcean::kCentreHalfUU;

	for (int32 Level = 0; Level <= RingCount; ++Level)
	{
		int32 HoleAcross = 0;
		if (Level > 0)
		{
			// The hole is the previous level's outer extent measured in THIS
			// level's cells, which -- because the cells doubled -- is exactly
			// the previous level's half-extent in cells. Recomputed from the
			// running HalfUU rather than carried, so the hole and the geometry
			// it must meet cannot drift apart.
			CellUU *= 2.0;
			HoleAcross = int32(FMath::RoundToDouble((2.0 * HalfUU) / CellUU));
			HalfCells = VoxelOcean::NextRingHalfCells(HoleAcross);
			HalfUU = double(HalfCells) * CellUU;
		}

		Verts.Reset();
		Tris.Reset();
		Normals.Reset();
		UVs.Reset();
		Colors.Reset();
		Tangents.Reset();
		AppendOceanLevel(CellUU, HalfCells, HoleAcross, Verts, Tris, Normals, UVs, Colors, Tangents);
		if (Verts.Num() == 0 || Tris.Num() == 0)
		{
			// Cannot happen with the derivation above, which is exactly why it
			// is checked: an empty level is the silent failure that would leave
			// a square hole in the sea and nothing in the log.
			UE_LOG(LogVoxelEarth, Error,
			       TEXT("Ocean: level %d built NOTHING (cell %.1f UU, half %d cells, hole %d cells). There will "
			            "be a hole in the ocean at that range."),
			       Level, CellUU, HalfCells, HoleAcross);
			continue;
		}
		OceanMesh->CreateMeshSection(BuiltSectionCount, Verts, Tris, Normals, UVs, Colors, Tangents,
		                             /*bCreateCollision*/ false);
		if (OceanMaterial)
		{
			OceanMesh->SetMaterial(BuiltSectionCount, OceanMaterial);
		}
		BuiltVertexCount += Verts.Num();
		BuiltTriangleCount += Tris.Num() / 3;
		++BuiltSectionCount;
	}

	// THE STATE THE REBUILD TRIGGER READS, set only after the mesh actually
	// exists. Set it before the loop and a build that threw out halfway would
	// leave Tick agreeing with a grid that was never finished.
	BuiltHalfDetail = HalfDetail;
	BuiltCellUU = SeedCellUU;

	// THE BUILD IS THE ONLY THING THAT CAN FAIL SILENTLY HERE -- it happens at
	// BeginPlay and then only on a detail change, so a wrong grid is a wrong
	// ocean for the whole session with no second chance to notice. The line
	// prints what was built AND what it reaches, so it can be read against the
	// table above.
	UE_LOG(LogVoxelEarth, Log,
	       TEXT("Ocean: ring grid built -- %d section(s) (1 centre + %d ring(s)), %d vertices, %d triangles, "
	            "finest cell %.2f m over +-%.0f m, reach +-%.1f km (clipmap needs +-%.1f km). Detail: %s "
	            "(voxel.Ocean.HalfDetail=%d). The camera is followed by transform."),
	       BuiltSectionCount, RingCount, BuiltVertexCount, BuiltTriangleCount, SeedCellUU / kUUPerMetre,
	       VoxelOcean::kCentreHalfUU / kUUPerMetre,
	       VoxelOcean::ReachHalfExtentUU(SeedCellUU) / (kUUPerMetre * 1000.0),
	       VoxelOcean::kRequiredHalfExtentUU / (kUUPerMetre * 1000.0),
	       HalfDetail != 0 ? TEXT("HALF") : TEXT("FULL"), HalfDetail);

	// ---- THE REBUILD'S ENGAGEMENT PROOF -------------------------------------
	//
	// A SECOND LINE, only on a rebuild, and it prints the vertex count BEFORE
	// and AFTER. That pair is the only thing that can distinguish "the toggle
	// rebuilt the ocean" from "the toggle was clicked, the cvar moved, and the
	// mesh is exactly what it was" -- which is what a rebuild that read the
	// wrong cvar, or that ran before the setting was applied, would look like
	// from every other symptom, including this function's own build line above.
	if (bRebuild)
	{
		UE_LOG(LogVoxelEarth, Log,
		       TEXT("Ocean: ring grid REBUILT for a detail change -- %s, %d -> %d vertices in %d -> %d "
		            "section(s), finest cell %.2f m. Rebuilt on the tick the cvar changed; nothing else "
		            "about the ocean moved."),
		       HalfDetail != 0 ? TEXT("FULL -> HALF") : TEXT("HALF -> FULL"), PrevVertexCount,
		       BuiltVertexCount, PrevSectionCount, BuiltSectionCount, SeedCellUU / kUUPerMetre);
	}
}

void AVoxelOceanActor::UpdateFollowPlane()
{
	UWorld* World = GetWorld();
	APlayerController* PC = World ? World->GetFirstPlayerController() : nullptr;
	if (!PC || !PC->GetPawn())
	{
		return;
	}

	FVector CameraLoc;
	// Cache-time guard as in UpdateUnderwaterState below: before the manager's
	// first update the cache is the origin, and the pawn is the camera.
	if (PC->PlayerCameraManager && PC->PlayerCameraManager->GetCameraCacheTime() > 0.f)
	{
		CameraLoc = PC->PlayerCameraManager->GetCameraLocation();
	}
	else if (APawn* P = PC->GetPawn())
	{
		CameraLoc = P->GetActorLocation();
	}
	else
	{
		return; // nothing to follow yet
	}

	// SNAPPED TO THE FINEST CELL, not to a round metre -- see the header. The
	// ring boundaries are mesh-space, so the mesh's world alignment has to move
	// in whole cells of the finest level or every LOD seam sweeps across the
	// world at a different sub-cell phase each frame.
	//
	// BuiltCellUU, NOT VoxelOcean::kCellUU: the finest cell is now whichever one
	// the grid on screen was built with. Snapping to the constant while a half
	// detail grid was drawn would put every ring boundary on a half-cell phase
	// -- the exact defect this snap exists to prevent, reintroduced by the
	// toggle that was supposed to be free.
	const double SnappedX = FMath::GridSnap(CameraLoc.X, BuiltCellUU);
	const double SnappedY = FMath::GridSnap(CameraLoc.Y, BuiltCellUU);

	// THE SEA SURFACE, NOW. SeaSurfaceZNowUU() is the geological datum
	// (voxelcore/core.h kSeaLevelMm) plus the QUANTISED tide offset; it returns
	// SeaLevelZUU() unchanged when the tide is disarmed, which is what makes a
	// no-tide run byte-identical to every capture in the archive. The static
	// SeaLevelZUU() is the fallback for a world with no water subsystem at all
	// (the transient loading world, or a stripped configuration) -- there is no
	// tide state there to ask.
	double SeaZUU = UVoxelWaterSubsystem::SeaLevelZUU();
	if (const UVoxelWaterSubsystem* Water = World->GetSubsystem<UVoxelWaterSubsystem>())
	{
		SeaZUU = Water->SeaSurfaceZNowUU();
	}
	// Skip the no-op move: an unchanged SetActorLocation still dirties the
	// transform of a 13-section, 40k-vertex PMC every frame (this is the
	// optimisation the header's LastSeaSurfaceZUU members promised and the
	// first cut only applied to the LOG line -- review finding #7).
	const FVector NewLoc(SnappedX, SnappedY, SeaZUU);
	if (!NewLoc.Equals(GetActorLocation(), 0.01))
	{
		SetActorLocation(NewLoc);
	}

	// ONE LINE PER DATUM STEP, and it is the ocean half of the tide's
	// engagement proof. The datum is quantised and rate-limited, so this fires
	// at most every couple of seconds; a tide leg where the subsystem logs
	// steps and this never does means the water surface did not follow them.
	// Exact != on purpose: the value compared is a quantised datum, so it
	// either stepped or it did not.
	if (!bHaveSeaSurfaceZ || SeaZUU != LastSeaSurfaceZUU)
	{
		if (bHaveSeaSurfaceZ)
		{
			UE_LOG(LogVoxelEarth, Log,
			       TEXT("Ocean: sea surface moved %.1f -> %.1f UU (%.3f m of tide off the %.1f UU geological "
			            "datum). The grid follows by transform -- nothing re-meshes."),
			       LastSeaSurfaceZUU, SeaZUU, (SeaZUU - UVoxelWaterSubsystem::SeaLevelZUU()) / kUUPerMetre,
			       UVoxelWaterSubsystem::SeaLevelZUU());
		}
		LastSeaSurfaceZUU = SeaZUU;
		bHaveSeaSurfaceZ = true;
	}
}

void AVoxelOceanActor::UpdateUnderwaterState(float DeltaTime)
{
	UWorld* World = GetWorld();
	APlayerController* PC = World ? World->GetFirstPlayerController() : nullptr;
	if (!PC || !PC->GetPawn())
	{
		return;
	}

	// Held while the menu owns the screen -- the second offender of the pair in
	// backlog 0.0k, and the one that only appeared after the first was silenced.
	// The camera fallback below is the pawn's location, and during the menu
	// there is no pawn (bStartPlayersAsSpectators), so this ran its underwater
	// test at the world origin and faulted worldgen on an unbaked tile. There
	// is nothing to be underwater in front of while a menu is up.
	if (VoxelFrontEnd::IsWorldHeldForMenu(World))
	{
		return;
	}

	FVector CameraPos = FVector::ZeroVector;
	bool bHaveCamera = false;
	// THE CAMERA CACHE IS THE ORIGIN UNTIL ITS FIRST UPDATE. On 2026-09-08 an
	// unattended capture leg died on frame 1: the pawn had its spawn pose
	// applied, but PlayerCameraManager had not run UpdateCamera yet, so
	// GetCameraLocation() answered (0,0,0), the underwater test asked worldgen
	// for fine pixel (-2,-2), and tile (-1,-1) is not baked -- a fatal gate leak
	// under -unattended (Saved/capture-chainproof-boat.log). GetCameraCacheTime()
	// is 0 exactly until that first update, so until then the pawn's own
	// location is the truthful camera, and with no pawn there is nothing to be
	// underwater in front of.
	if (PC->PlayerCameraManager && PC->PlayerCameraManager->GetCameraCacheTime() > 0.f)
	{
		CameraPos = PC->PlayerCameraManager->GetCameraLocation();
		bHaveCamera = true;
	}
	else if (APawn* P = PC->GetPawn())
	{
		CameraPos = P->GetActorLocation();
		bHaveCamera = true;
	}
	if (!bHaveCamera)
	{
		return;
	}
	const double CameraZ = CameraPos.Z;

	// WAS `CameraZ < 0.0`, with nothing else consulted. A dry cavern below sea
	// level -- which this world has plenty of, caves.h only refuses to carve
	// AT or below the datum, not above it under a valley floor -- got full
	// underwater fog and the tinted post-process, and the post-process is
	// `bUnbound = true`, so the tint was global. See
	// UVoxelWaterSubsystem::IsUnderwaterAtWorld for what replaces it and what
	// it still cannot tell apart (docs/watershed-system-plan.md §5.3).
	UVoxelWaterSubsystem* Water = World->GetSubsystem<UVoxelWaterSubsystem>();
	bool bNowUnderwater;
	if (Water)
	{
		// THE FULL PREDICATE, AND IT IS ALREADY THE TIDED ONE. IsUnderwaterAtWorld
		// composes simulated water, the implicit field and the ocean datum, and
		// plan A4 threads the tide through the ocean half of that composition --
		// so the waterline this test uses is the same one the mesh above is
		// standing at, by construction rather than by two agreeing constants.
		bNowUnderwater = Water->IsUnderwaterAtWorld(CameraPos);
	}
	else if (UVoxelWorldSubsystem* Terrain = World->GetSubsystem<UVoxelWorldSubsystem>())
	{
		// THE STATIC, AND ONLY BECAUSE THERE IS NO INSTANCE TO ASK.
		//
		// Plan A4 adds an INSTANCE UVoxelWaterSubsystem::IsOpenSeaNowAtWorld
		// that carries the tide, and keeps the STATIC IsOpenSeaAtWorld meaning
		// the geological datum. This branch is reachable only when the water
		// subsystem does not exist (the transient loading world, or a stripped
		// configuration) -- which is precisely the case where there is no tide
		// state to consult and the geological datum IS the whole answer. So the
		// static is not a leftover here, it is the correct half of the pair; it
		// is named and explained so a later sweep does not "convert" it into a
		// call that has no object to make it on.
		bNowUnderwater = UVoxelWaterSubsystem::IsOpenSeaAtWorld(
			CameraZ, Terrain->GetSurfaceHeightUU(CameraPos.X, CameraPos.Y));
	}
	else
	{
		bNowUnderwater = false;
	}

	// --- The depth handed to the material -------------------------------------
	//
	// Refreshed BEFORE the transition log below, so an "entered water" line
	// reports the depth of the frame it entered on rather than the previous
	// frame's stale value.
	//
	// Only refreshed while actually submerged; see LastSubmergedDepthM's comment
	// in the header for why it is frozen rather than re-queried during the fade
	// out (the query correctly answers 0 above the surface, and pushing that
	// mid-fade would collapse the extinction in one frame -- the exit pop, at
	// the exit).
	//
	// bNowUnderwater, not bUnderwater: the edge below has not been consumed yet
	// at this point, and reading the stale flag here would skip the first
	// submerged frame's depth. The two are equal on every other frame.
	if (bNowUnderwater && Water)
	{
		LastSubmergedDepthM = float(Water->SubmergedDepthUUAtWorld(CameraPos) / kUUPerMetre);
	}
	if (UnderwaterMID)
	{
		// Pushed every tick, not only on change. A MID scalar set is a cheap
		// uniform write and the alternative -- tracking the last pushed value
		// and comparing -- would silently stop updating if anything else ever
		// touched the parameter.
		UnderwaterMID->SetScalarParameterValue(ParamSubmergedDepthM, LastSubmergedDepthM);
	}

	// --- THE TRANSITION EDGE, WHICH IS NO LONGER THE SAME THING AS "DO WORK" ---
	//
	// This function used to early-return whenever bNowUnderwater matched the
	// stored bUnderwater, because with a 0/1 snap there genuinely was nothing to
	// do between transitions. With a ramp and a per-tick depth push there is, so
	// the early return is gone and the LOG now has to be guarded by the edge
	// explicitly instead of getting that for free from the early return.
	//
	// Getting that wrong is not cosmetic. This line is the only observable
	// signal for this branch in an unattended screenshot run (task spec: verify
	// via log lines instead of a second screenshot), and one line per frame at
	// 60 fps would bury the rest of the run's output in a few seconds of
	// swimming -- turning the one instrument into noise.
	if (bNowUnderwater != bUnderwater)
	{
		bUnderwater = bNowUnderwater;

		// The ground height goes in the line because it is HALF THE ANSWER: a
		// transition at z=-500 over ground at +12000 would be the old
		// camera-only bug returning (see the paragraph above the predicate).
		//
		// The depth and which treatment is live are in the line for the same
		// reason -- an underwater screenshot that looks wrong now has two more
		// possible causes than it used to (a depth of 0.00 m at 30 m down means
		// the datum did not resolve and the material got nothing to work with;
		// "legacy constant tint" means M_Underwater never loaded), and neither
		// is distinguishable from a shading problem in the image alone.
		const double GroundZ = World->GetSubsystem<UVoxelWorldSubsystem>()
		                           ? World->GetSubsystem<UVoxelWorldSubsystem>()->GetSurfaceHeightUU(CameraPos.X, CameraPos.Y)
		                           : 0.0;
		UE_LOG(LogVoxelEarth, Log,
		       TEXT("Ocean: camera %s water (camera z=%.1f UU, worldgen ground z=%.1f UU, sea z=%.1f UU, ")
		       TEXT("submerged depth %.2f m, treatment=%s, fogSuppression=%.2f)"),
		       bUnderwater ? TEXT("entered") : TEXT("exited"), CameraZ, GroundZ,
		       UVoxelWaterSubsystem::SeaLevelZUU(), LastSubmergedDepthM,
		       UnderwaterMID ? TEXT("M_Underwater") : TEXT("legacy constant tint"),
		       UnderwaterBlendWeight);
	}

	// --- The blend ------------------------------------------------------------
	//
	// FInterpConstantTo, not FInterpTo: a constant rate reaches the target in a
	// bounded, stated time (UnderwaterBlendSeconds) and arrives exactly, whereas
	// the exponential FInterpTo never quite arrives and its "speed" is not a
	// duration anyone can reason about from the call site. The duration is the
	// thing being specified here, so the interp that takes a duration is the
	// right one.
	//
	// DeltaTime is used as given -- no clamp. A hitch long enough to make this
	// jump straight to the target is a hitch the player already saw; smoothing
	// the water transition across it would be dishonest about when they entered.
	if (UnderwaterPostProcess)
	{
		const float Target = bUnderwater ? 1.f : 0.f;
		UnderwaterBlendWeight = FMath::FInterpConstantTo(UnderwaterBlendWeight, Target, DeltaTime,
		                                                 1.f / UnderwaterBlendSeconds);
		UnderwaterPostProcess->BlendWeight = UnderwaterBlendWeight;

		// THE SAME WEIGHT suppresses the atmospheric height fog (fog plan,
		// 2026-08-20). One number drives both transitions so the two extinction
		// models -- air fog above, Beer-Lambert below -- CROSS-FADE and can
		// never sum at full strength, which is the double-count the old height
		// fog was deleted for (:133-164 above). Pushed every tick the blend is
		// live rather than only on transitions, because the fade itself is the
		// window where double-counting would happen.
		//
		// Direction of dependency: the OCEAN pushes to the sky, never the
		// reverse -- the sky must not know oceans exist (it works in ocean-less
		// worlds; suppression just stays 0 there). Same lifetime reasoning as
		// the exposure-ownership rule in VoxelSkySubsystem.cpp.
		if (UWorld* FogWorld = GetWorld())
		{
			if (UVoxelSkySubsystem* Sky = FogWorld->GetSubsystem<UVoxelSkySubsystem>())
			{
				Sky->SetUnderwaterFogSuppression(UnderwaterBlendWeight);
			}
		}
	}
}
