// VoxelWaveMirror.generated.h -- DO NOT EDIT BY HAND.
// Generated by Tools/water_wave_graph.py (write_cpu_mirror_header), re-emitted
// by every water material regeneration so it cannot go stale silently against
// the shipped WaveField HLSL. Change the field there, never here.
//
// WHAT THIS IS. The CPU mirror of the water surface's wind-driven wave field,
// for buoyancy probes (ocean/tides plan D2 stretch, activated 2026-09-05):
// the SAME eight-octave sum, drag warp, wind sizing, F8.1 two-bin direction
// crossfade and calm/choppy patch modulation the materials evaluate per
// pixel, transcribed to C++ so UVoxelWaterSubsystem can ask "how high is the
// drawn wave at this world position right now" without a readback.
//
// ============================= PHASE COHERENCE =============================
// WHAT THE CALLER MUST MIRROR, EXACTLY:
//   * TIME: the material's clock is MaterialExpressionTime == View.GameTime
//     == UWorld::GetTimeSeconds() (pause-aware seconds since world start).
//     Pass ScaledTimeS = World->GetTimeSeconds() * <WaveTimeScale as last
//     pushed to MPC_VoxelSky>. NOT the sky epoch -- the sky runs a different,
//     offset clock and mixing the two is the known phase-drift trap the plan
//     records. A live WaveTimeScale change steps material phase (T*s is not
//     an integral); this mirror steps identically, so the two stay coherent
//     through the step.
//   * WIND: the same WindVectorMS.xy (sustained, smoothed) the subsystem
//     pushed to the collection this frame. The MPC write is one frame ahead
//     of the draw at worst; at the wind's smoothed rate of change that is
//     sub-millimetre of phase.
//   * PARAMS: FParams defaults below equal the generators' shipped material
//     parameter defaults. An INSTANCE override on the material (a ladder, a
//     tuned WindDirBinDeg) is not visible here -- query the material and
//     fill FParams from it if instance parity ever matters.
// WHAT THE MIRROR DELIBERATELY IS:
//   * the OPEN-WATER field: exactly the material's bathy-validity-0 branch.
//     No shore damping, shoaling, breaking or crest peaking -- near a shore
//     the drawn wave is depth-limited SMALLER than this value, so probes
//     overstate bob amplitude in the surf zone by up to the amplitude itself
//     (centimetres at shipped defaults). No ripple field (that is the C++
//     simulation's own render target -- probe the ripple subsystem if wake
//     bobbing is ever wanted).
//   * the FIELD height, metres. The DRAWN surface displaces by
//     FieldHeightM * kWaveWpoFraction, faded to zero between
//     kWpoFadeStartM..kWpoFadeEndM of CAMERA distance -- so multiply by
//     kWaveWpoFraction for probe-vs-pixel contact, and accept that past the
//     fade the pixels stop moving while the probe keeps bobbing (invisible
//     at that range; physics must not depend on the camera).
// RESIDUAL, HONESTLY: GPU/CPU float op ordering differs -> sub-mm; the
// one-frame MPC latency -> sub-mm; instance overrides -> whatever was
// overridden. Expected total probe-vs-pixel mismatch: a FEW CENTIMETRES,
// which is the acceptance band the owner verdict set (plausible bobbing,
// not pixel-exact contact).
//
// ============================== STALENESS ==================================
// VOXELWAVEMIRROR_FINGERPRINT hashes the octave table, the defaults and the
// HLSL template. Both regenerated water materials carry the same value as
// the scalar parameter "WaveMirrorFingerprint". Assert at startup:
//   ensure(GetScalarParameterDefaultValue(WaterMat, "WaveMirrorFingerprint")
//          == float(VOXELWAVEMIRROR_FINGERPRINT))
// and treat a mismatch as "header and asset were built from different field
// math" -- rebuild one of them, do not bob boats on the disagreement.

#pragma once

#include <algorithm>
#include <cmath>

#define VOXELWAVEMIRROR_FINGERPRINT 0xB0BDDDu

namespace VoxelWaveMirror
{

// The generators' shipped defaults for every parameter the field math reads.
struct FParams
{
    float WaveAmplitudeM = 0.25f;
    float WaveBaseWavelengthM = 5.0f;
    float WaveDirBaseDeg = 58.7f;
    float WaveDirIncrementDeg = 137.507764f;
    float WaveQuantPerVoxel = 0.0f;
    float WavePatchContrast = 0.55f;
    float WindDirectionAuthority = 1.0f;
    float WindSpreadDeg = 35.0f;
    float WindRefSpeedMS = 5.0f;
    float WindAmpExponent = 1.0f;
    float WindLenExponent = 0.68f;
    float WindPatchDriftFrac = 0.5f;
    float WindDirBinDeg = 30.0f;
    float WindSpeedBinLog2 = 0.5f;
};

// The displayed-surface constants (shared parameter defaults in both water
// generators; see WaveWpoFraction's one-name-one-default argument there).
constexpr float kWaveWpoFraction = 0.25f;
constexpr float kWpoFadeStartM = 55.0f;
constexpr float kWpoFadeEndM = 72.0f;

inline float FieldHeightM(float PosXM, float PosYM, float ScaledTimeS,
                          float WindXMS, float WindYMS,
                          const FParams& P = FParams())
{
    constexpr int   kOctaves = 8;
    constexpr float kDragMult = 0.2f;
    constexpr float kMeanWave = 0.2329f;
    constexpr float kTwoPi = 6.2831853f;
    const float kSpread[kOctaves] = { -0.190983f, 0.549066f, 0.070848f, -0.625636f, 0.602471f, -0.244832f, -1.310400f, 0.405765f };

    const float T = ScaledTimeS;

    float px = PosXM, py = PosYM;
    if (P.WaveQuantPerVoxel > 0.0f)
    {
        const float k = P.WaveQuantPerVoxel * 10.0f;
        px = std::floor(px * k) / k;
        py = std::floor(py * k) / k;
    }

    const float windSpeed = std::sqrt(WindXMS * WindXMS + WindYMS * WindYMS);
    const float invWS = 1.0f / ((windSpeed > 1.0e-4f) ? windSpeed : 1.0e-4f);
    const float wdx = WindXMS * invWS, wdy = WindYMS * invWS;
    const float u = windSpeed / std::max(P.WindRefSpeedMS, 0.1f);

    const float ampScale = std::pow(std::max(u, 0.0f), std::max(P.WindAmpExponent, 0.01f));

    // F8.1: the phase sees direction BINS, never the continuous direction.
    const float upwindAng = std::atan2(-wdx, -wdy);
    const float nBins = std::max(std::round(360.0f / std::max(P.WindDirBinDeg, 1.0f)), 3.0f);
    const float binW = kTwoPi / nBins;
    const float aBin = upwindAng / binW;
    const float kBin = std::floor(aBin);
    const float fr = aBin - kBin;
    const float wBin = fr * fr * (3.0f - 2.0f * fr);   // smoothstep(0,1,frac)

    // F8.1 second half: the WAVELENGTH sees speed BINS, never the continuous
    // speed (amplitude above stays continuous -- it never touches a phase).
    const float ue = std::max(u, 0.2f);
    const float sBinW = std::max(P.WindSpeedBinLog2, 0.01f);
    const float aSpd = std::log2(ue) / sBinW;
    const float jSpd = std::floor(aSpd);
    const float sfr = aSpd - jSpd;
    const float wSpd = sfr * sfr * (3.0f - 2.0f * sfr); // smoothstep(0,1,frac)
    const float lenExpEff = std::max(P.WindLenExponent, 0.0f);

    const float baseRef = P.WaveDirBaseDeg * 0.017453293f;
    const float spreadRad = P.WindSpreadDeg * 0.017453293f;
    const float dIncRad = P.WaveDirIncrementDeg * 0.017453293f;

    float H4[2][2];
    float patch2[2];
    for (int bin = 0; bin < 2; ++bin)
    {
        const float upA = (kBin + float(bin)) * binW;
        float dA = upA - baseRef;
        dA -= kTwoPi * std::round(dA * 0.15915494f);
        const float baseAng = baseRef + P.WindDirectionAuthority * dA;

        for (int sb = 0; sb < 2; ++sb)
        {
            const float lenScaleB = std::exp2((jSpd + float(sb)) * sBinW * lenExpEff);
            const float lambda0B = std::max(P.WaveBaseWavelengthM * lenScaleB, 0.15f);
            const float omega0B =
                2.0f * std::sqrt(P.WaveBaseWavelengthM / std::max(lambda0B, 1.0e-4f));

            float posX = px, posY = py;
            float freq = kTwoPi / lambda0B;
            float tmul = omega0B;
            float weight = 1.0f;
            float sumH = 0.0f, sumW = 0.0f;
            for (int i = 0; i < kOctaves; ++i)
            {
                const float ang = baseAng
                    + (dIncRad * float(i)) * (1.0f - P.WindDirectionAuthority)
                    + (spreadRad * kSpread[i]) * P.WindDirectionAuthority;
                const float dx = std::sin(ang), dy = std::cos(ang);
                const float x = (dx * posX + dy * posY) * freq + T * tmul;
                const float wv = std::exp(std::sin(x) - 1.0f) * 0.5f;
                const float dwv = wv * std::cos(x);
                posX += dx * (-dwv) * weight * kDragMult;
                posY += dy * (-dwv) * weight * kDragMult;
                sumH += wv * weight;
                sumW += weight;
                weight *= 0.8f;
                freq *= 1.42f;
                tmul *= 1.07f;
            }
            H4[bin][sb] = (sumH / std::max(sumW, 1.0e-6f)) - kMeanWave;
        }

        const float drift = P.WindRefSpeedMS * T * P.WindPatchDriftFrac * P.WindDirectionAuthority;
        const float ppx = px + std::sin(upA) * drift;
        const float ppy = py + std::cos(upA) * drift;
        const float lfa = std::sin(ppx * 0.0349f + ppy * 0.0217f + T * 0.031f);
        const float lfb = std::sin(ppx * -0.0161f + ppy * 0.0271f + T * 0.0193f);
        const float pr = 0.5f + 0.35f * lfa + 0.35f * lfb;
        patch2[bin] = std::min(std::max(pr, 0.0f), 1.0f);
    }

    const float Hs0 = H4[0][0] + (H4[0][1] - H4[0][0]) * wSpd;
    const float Hs1 = H4[1][0] + (H4[1][1] - H4[1][0]) * wSpd;
    const float H = Hs0 + (Hs1 - Hs0) * wBin;
    const float patch = patch2[0] + (patch2[1] - patch2[0]) * wBin;
    const float lo = 1.0f - P.WavePatchContrast;
    const float hi = 1.0f + P.WavePatchContrast;
    const float amp = P.WaveAmplitudeM * ampScale * (lo + (hi - lo) * patch);
    return H * amp;
}

} // namespace VoxelWaveMirror
