"""Generate the UI's read-only handbook from the approved capability proposal."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/design/crafting-capabilities-v1.json"
DEST = ROOT / "ue-project/Source/VoxelEarthUI/VoxelCraftingHandbook.inl"

def generate():
    graph = json.loads(SOURCE.read_text(encoding="utf-8"))
    nodes = {n["id"]: n for n in graph["resources"] + graph["capabilities"]}
    def label(key):
        return nodes[key]["label"]
    def literal(value):
        return 'TEXT(' + json.dumps(value, ensure_ascii=True) + ')'
    rows = ["// Generated by tools/generate-crafting-handbook.py. No runtime recipes or quantities."]
    for rule in graph["rules"]:
        title = " / ".join(label(k) for k in rule["grants"])
        family = nodes[rule["grants"][0]].get("family", "survival").replace("_", " ").title()
        required = [label(k) for k in rule["requires_all"]]
        required += ["One of: " + " OR ".join(label(k) for k in group) for group in rule["requires_any_groups"]]
        following = [r for r in graph["rules"] if any(k in r["requires_all"] or any(k in g for g in r["requires_any_groups"]) for k in rule["grants"])]
        unlocks = list(dict.fromkeys(label(k) for r in following for k in r["grants"]))
        rows.append("{" + ", ".join(literal(x) for x in (rule["id"], title, family, "\n\n".join(required), "\n\n".join(unlocks) or "Established workshop capability", rule.get("note", ""))) + "},")
    return "\n".join(rows) + "\n"

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        assert DEST.read_text(encoding="utf-8") == expected, "Crafting handbook is stale; run generator."
        print("Crafting handbook matches all design rules and dependencies.")
    else:
        DEST.write_text(expected, encoding="utf-8")
        print(DEST)
