"""Validate `terrain_service.geomorph` against real Earth and against convincing fakes.

A metric that returns a number is worthless until it has been shown to separate the
cases we care about. This tool is that demonstration, and its output is
``terrain-service/docs/geomorph-validation.md``.

Three sweeps, each internally at **one** cell size, because slope, curvature, geomorphon
histograms and pit density all move with resolution and a table whose columns were
measured at different pixel sizes is worse than no table:

``--sweep earth`` (30 m)
    Five Copernicus GLO-30 windows -- alpine, dissected fluvial upland, high plains,
    sand sea, arid mountains -- against four synthetic controls: fBm with a plausible
    Hurst exponent, multi-octave value noise, a **phase-randomised surrogate of the
    alpine window itself** (identical power spectrum, no drainage), and the same window
    pixel-shuffled. The surrogate is the case that matters: it is the field that a
    spectral check cannot tell from real terrain.

``--sweep bake`` (1.875 m)
    A real 30 m window run through `bake.pipeline.bake_padded_domain` at a
    CI-sized geometry, measured at three points in the pipeline -- B0+B1 (carrier plus
    roughness, no erosion), the depression-filled surface, and the final B3 output --
    against an fBm control at the same 1.875 m. This is where the bake's own prediction
    ``theta = m/n = 0.5625`` is either met or not.

``--sweep tiers`` (1.875 m)
    Variogram of the baked surface across the 30 m tier boundary, to demonstrate what
    `variogram.tier_continuity` sees.

Reference data. ``terrain-service/tools/earth_reference.py`` is another agent's corpus
builder and is the right long-term source; at the time of writing it had not landed, so
this tool fetches its own windows straight from the Copernicus GLO-30 public bucket over
``/vsicurl`` and caches them as ``.npy``. ``--source etopo`` falls back to the local
``etopo_10m.tif``, which is real but 18 km/px and therefore useless for anything fluvial
-- it is there so the tool runs offline, not because its numbers mean much.

Determinism: every synthetic field is seeded explicitly, the window manifest is a
constant in this file, and nothing reads the clock. Re-running reproduces the table
byte for byte.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from dataclasses import dataclass

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from terrain_service import geomorph as G  # noqa: E402
from terrain_service.geomorph import report as R  # noqa: E402

# One arcsecond of latitude on the WGS84 ellipsoid, near enough everywhere for our
# purposes (30.87 m at the equator, 30.92 at 60 deg; we use the mean).
ARCSEC_M = 30.87


@dataclass(frozen=True)
class Window:
    """A named 1-degree GLO-30 tile plus a pixel window inside it."""

    case: str
    lat: int
    lon: int
    row0: int
    col0: int
    note: str


#: Chosen by scanning each tile's relief on a decimated overview (see ``--scout``) for a
#: window that is (a) entirely land, (b) unambiguously of its class, and (c) not
#: straddling a class boundary. Held as a constant so the table is reproducible.
MANIFEST = (
    Window("alpine", 46, 8, 900, 150,
           "Bernese Oberland, Switzerland -- glaciated high alpine, 3 km relief"),
    Window("fluvial_upland", 37, -83, 2240, 1500,
           "Cumberland Plateau, Kentucky -- humid dendritic dissection, the textbook "
           "fluvial network"),
    Window("plains", 39, -100, 1200, 1200,
           "High Plains, western Kansas -- low-relief depositional plain"),
    Window("desert_dunes", 19, 48, 2200, 1200,
           "Rub' al Khali, Saudi Arabia -- linear aeolian dunes, no fluvial network"),
    Window("desert_mountains", 36, -117, 2400, 200,
           "Panamint Range / Death Valley -- arid mountains and alluvial fans"),
)


#: Prepended to the generated report. Kept here, beside the code that produced the
#: numbers, so the conclusions cannot drift away from the evidence: re-running the tool
#: rewrites the whole document, interpretation included.
CONCLUSIONS = """\
# Does `terrain_service.geomorph` measure anything?

*Generated by `terrain-service/tools/geomorph_validate.py --sweep all --size 1024
--bake-coarse 96 --replicates`. Everything below is reproducible from that command; the
reference windows come from the public Copernicus GLO-30 bucket and are cached locally.*

Two questions are asked separately, because a metric can pass one and fail the other,
and several do.

**Question 1 -- does the metric see through a good fake?** The fake is a
*spectrum-matched surrogate*: a Gaussian random field carrying a real scene's own
variogram to within 15% at every lag, with the same variance and the same roughness at
every scale, and no drainage network whatsoever. This is the field that a spectral check
cannot distinguish from real terrain, and it is the specific mistake this package exists
to stop repeating.

**Question 2 -- does the metric tell the Alps from Kansas?** Five real terrain classes,
with the within-class noise estimated by splitting each scene into quadrants.

## The verdict

**Three metric families see through the surrogate, and a fourth is marginal.**

| metric | real | surrogate | gap |
|---|---|---|---|
| `fill_volume_per_area_m` (pit statistics) | 0.07 - 0.97 m | 19.9 - 64.8 m | 15x, no overlap |
| `curvature_asymmetry` = abs Laplacian skew | 0.010 - 0.111 | < 0.003 | 10-100x |
| `hack_h` (Hack's law) | 0.475 - 0.557 | 0.161 - 0.287 | ~2x, no overlap |
| `tail_asymmetry` (curvature p01/p99) | 0.87 - 1.32 | 0.99 - 1.00 | small but clean |
| *marginal:* `theta` (slope-area) | 0.18 - 0.40 | 0.13 - 0.15 | ~1.8x both pairs |

`theta` is reported as marginal rather than promoted: it separates both pairs by a
consistent factor of about 1.8, but the gap is only 2.6 times the within-scene spread,
so on a single window it is suggestive rather than decisive. It stays in the package
because it is the only metric that checks our own erosion model against its own
prediction, not because it is a strong realism detector. `convex_frac` and
`dd_km_per_km2` are marginal on the same criterion.

**Everything else is blind to it**, including several metrics that sound like they
should not be:

* **Slope statistics.** The Cumberland Plateau and its surrogate agree on mean slope to
  7% (19.8 vs 18.4 deg), on p99 to 2%, and on the fraction above the angle of repose to
  3% (0.029 vs 0.030). A slope histogram catches a badly *scaled* fake and nothing else.
* **Geomorphon histograms.** Ridge+peak 0.179 vs 0.166, valley+pit 0.166 vs 0.166. The
  classifier is looking at openness, and openness is a second-order property.
* **The variogram**, by construction -- the surrogate was built to match it.
* **Hypsometry.** Its spread across five real terrain classes (sd 0.072) is *smaller*
  than its spread between quadrants of one scene (sd 0.132). It cannot see spatial
  structure at all: a pixel-shuffled DEM has a bit-identical curve.
* **Drainage density.** Tried at 10^4, 10^5, 3x10^5 and 10^6 m^2 channel heads; the real
  range (2.4-10.7 km/km^2) contains the synthetic range (5.6-6.5) at every one of them.
* **Raw pit density.** The obvious statistic, and it fails: the alpine surrogate has
  *fewer* local minima per km^2 than the real Alps (4.4 vs 7.7). A Gaussian field's
  minima are few and enormous; a real landscape's are many and shallow. Only the fill
  *volume* separates them.

**On question 2** -- separating real terrain classes -- the ranking is nearly the
reverse. `variogram_max_kink`, `hurst_overall`, `laplacian_quantile_skew`, `p99_deg`,
`frac_above_repose`, `convex_frac`, `profile_quantile_skew` and `dd_km_per_km2` all clear
three within-class sigmas; `hypsometric_integral`, `hack_h` and `fill_volume_per_area_m`
do not. **Geomorphons deserve a special note here**: `frac_flat` at a 3 deg flatness
threshold runs 0.577 on the High Plains, 0.422 on the Rub' al Khali and 0.000246 on the
Cumberland Plateau. It reads "no" in the table only because the Death Valley scene is
genuinely half playa and half mountain, so its own quadrants disagree violently -- which
is a fact about that scene, not a failure of the metric.

## What this says about our bake

Sweep 2 amplifies a real 30 m alpine window to 1.875 m through
`bake.pipeline.bake_padded_domain` at the production apron and scale, and measures three
points in the pipeline. Three findings, in descending order of how much they should
worry someone:

1. **The slope-area concavity does not go where the model says it should.** The bake
   incises with `m = 0.45, n = 0.8`, which predicts `theta = m/n = 0.5625`. Measured on
   the B0+B1 surface (carrier plus roughness, before any erosion) theta = 0.121; after
   B2 incision and B3 relaxation it is **0.067** -- it moved *away* from the prediction,
   not towards it. For scale, real 30 m scenes measure 0.18-0.40 by the identical method
   and the 30 m input to this very bake measures 0.203. Caveats, honestly: `theta = m/n`
   holds at topographic steady state and the bake runs one incision pass, so the
   prediction is an attractor rather than a requirement; and the domain here is 2.9 km
   across, which is three decades of contributing area rather than five.

2. **The fine tier has almost no landform structure of its own.** At a matched 10-cell
   lookout, the baked 1.875 m surface classifies as 77% SLOPE with 0.5% ridge+peak and
   0.7% valley+pit. Real terrain at its own resolution runs 5-18% ridge+peak. The
   variogram agrees: Hurst = 0.958 over the whole range, i.e. the surface between 30 m
   carrier samples is very nearly the smooth spline interpolating them.

3. **But the incision pass does build a real network, and one metric proves it.** Hack's
   exponent on the B0+B1 surface is **-0.003** with an r2 of 0.0001: contributing area
   grows without the mainstem getting any longer, which is what a field of unorganised
   blobs looks like. After incision it is **0.626 with an r2 of 0.82**. The erosion pass
   creates drainage topology; what it does not yet create is channel concavity.

Two things the bake sweep cannot tell you, stated so nobody reads them out of the table:
the baked surface's `fill_volume_per_area_m` is 0.003 m and its `fill_depth_p99_m` is
zero **because the bake ran its own epsilon fill in B2a**, so the pit metrics are
measuring our fill and not the landscape; and the tier-continuity check across 30 m
reports dH = -0.025 on the baked tier against -0.029 on its un-eroded predecessor, i.e.
no band is being double-counted or dropped at that hand-off.

## Caveats on the reference corpus

`terrain-service/tools/earth_reference.py` -- another agent's corpus builder -- had not
landed when this was written, so the five windows below are fetched by this tool
directly. They are one window per class, not a distribution over each class, so the
"real range" columns above are five points and not a confidence interval. ETOPO
(`--source etopo`) is available for offline runs and is 18 km/px, which is useless for
anything fluvial; it is there so the tool runs, not because its numbers mean anything.

---

"""


def _tile_url(lat: int, lon: int) -> str:
    ns = "N%02d" % lat if lat >= 0 else "S%02d" % (-lat)
    ew = "E%03d" % lon if lon >= 0 else "W%03d" % (-lon)
    n = f"Copernicus_DSM_COG_10_{ns}_00_{ew}_00_DEM"
    return f"/vsicurl/https://copernicus-dem-30m.s3.amazonaws.com/{n}/{n}.tif"


def _square_resample(a: np.ndarray, factor: float) -> np.ndarray:
    """Resample the x axis by ``factor`` with bilinear interpolation.

    GLO-30 is on a geographic grid, so its cells are 1 arcsec tall and 1 arcsec wide --
    30.87 m by ``30.87 * cos(lat)`` m. Every metric in this package assumes **square**
    cells (slope is ``hypot`` of two differences that are implicitly at the same pitch;
    the geomorphon rays step ``sqrt(2)`` on the diagonal). Feeding a 46-degree-latitude
    window in raw would report the x-direction slope 45% too small, so the grid is
    resampled to square metric cells before anything else touches it.
    """
    h, w = a.shape
    new_w = int(round(w * factor))
    src = np.linspace(0.0, w - 1.0, new_w)
    i0 = np.floor(src).astype(int)
    i1 = np.minimum(i0 + 1, w - 1)
    t = (src - i0)[None, :]
    return a[:, i0] * (1.0 - t) + a[:, i1] * t


def fetch_window(win: Window, size: int, cache_dir: str, *, verbose: bool = True):
    """Read a GLO-30 window and return ``(z_metres, cell_m)`` on square cells."""
    path = os.path.join(cache_dir, f"{win.case}_{size}.npy")
    if os.path.exists(path):
        return np.load(path), ARCSEC_M
    import rasterio
    from rasterio.windows import Window as RWindow

    os.environ.setdefault("GDAL_DISABLE_READDIR_ON_OPEN", "EMPTY_DIR")
    lat_c = win.lat + 0.5
    cosl = math.cos(math.radians(lat_c))
    src_cols = int(math.ceil(size / cosl)) + 2
    if verbose:
        print(f"  fetching {win.case}: {size}x{src_cols} px at ({win.lat},{win.lon})",
              flush=True)
    with rasterio.open(_tile_url(win.lat, win.lon)) as ds:
        a = ds.read(1, window=RWindow(win.col0, win.row0, src_cols, size)).astype(
            np.float64)
    if not np.isfinite(a).all():
        raise RuntimeError(f"{win.case} window contains voids; move it")
    z = _square_resample(a, cosl)[:, :size]
    if z.shape != (size, size):
        raise RuntimeError(f"{win.case} came back {z.shape}, wanted {(size, size)}")
    os.makedirs(cache_dir, exist_ok=True)
    np.save(path, z)
    return z, ARCSEC_M


def etopo_window(case: str, size: int, cache_dir: str):
    """Fallback: a window of the local ETOPO 10-arcmin grid. Real, and far too coarse."""
    import rasterio

    path = r"D:\terrain-diffusion\data\global\etopo_10m.tif"
    picks = {"alpine": (250, 1090), "fluvial_upland": (300, 630),
             "plains": (295, 620), "desert_dunes": (400, 1180),
             "desert_mountains": (300, 600)}
    r0, c0 = picks.get(case, (250, 1090))
    n = min(size, 128)
    with rasterio.open(path) as ds:
        a = ds.read(1, window=((r0, r0 + n), (c0, c0 + n))).astype(np.float64)
    return a, 10.0 * 60.0 * ARCSEC_M   # 10 arcmin


# --------------------------------------------------------------------------- sweeps
def _quadrants(z):
    h, w = z.shape
    return [z[:h // 2, :w // 2], z[:h // 2, w // 2:],
            z[h // 2:, :w // 2], z[h // 2:, w // 2:]]


def sweep_earth(args) -> dict:
    """Five real classes plus four controls, all at GLO-30's 30 m."""
    fields: dict = {}
    for win in MANIFEST:
        if args.source == "etopo":
            z, cell = etopo_window(win.case, args.size, args.cache)
        else:
            z, cell = fetch_window(win, args.size, args.cache)
        fields[win.case] = (z, cell)

    ref_z, cell = fields["alpine"]
    shape = ref_z.shape
    fields["fbm_h075"] = (
        G.fbm(shape, cell, hurst=0.75, seed=1,
              rms_m=float(ref_z.std())), cell)
    fields["value_noise"] = (
        G.value_noise(shape, cell, seed=2, octaves=9,
                      rms_m=float(ref_z.std())), cell)
    fields["surrogate_alpine"] = (
        G.spectrum_matched_surrogate(ref_z, cell, seed=3), cell)
    fields["surrogate_fluvial"] = (
        G.spectrum_matched_surrogate(fields["fluvial_upland"][0], cell, seed=7), cell)
    fields["shuffled_alpine"] = (G.shuffled(ref_z, cell, seed=4), cell)

    cases, reps, objs = {}, {}, {}
    for name, (z, c) in fields.items():
        print(f"  measuring {name} ...", flush=True)
        cases[name] = R.describe(z, c, search_m=args.search_m)
        ctx = G.flow_context(z, c)
        objs[name] = {
            "slope_area": _safe_sa(ctx),
            "variogram": G.variogram(z, c),
            "hypsometry": G.hypsometry(z, c),
        }
        reps[name] = [R.describe(q, c, search_m=args.search_m, skip_flow=False)
                      for q in _quadrants(z)] if args.replicates else []

    # The control has to be audited too: a surrogate that is rougher than the field it
    # was made from is a strawman, and this is the number that says whether it is.
    fidelity = []
    for real, surr in (("alpine", "surrogate_alpine"),
                       ("fluvial_upland", "surrogate_fluvial")):
        v1 = objs[real]["variogram"]
        v2 = objs[surr]["variogram"]
        r = v2.gamma_m2 / v1.gamma_m2
        fidelity.append((real, surr, float(r.min()), float(np.median(r)),
                         float(r.max())))
    for win in MANIFEST:
        z, c = fields[win.case]
        s = G.spectrum_matched_surrogate(z, c, seed=11)
        r = G.variogram(s, c).gamma_m2 / objs[win.case]["variogram"].gamma_m2
        fidelity.append((win.case, "(spot check)", float(r.min()),
                         float(np.median(r)), float(r.max())))
    return {"cases": cases, "replicates": reps, "objs": objs, "fields": fields,
            "cell_m": cell, "fidelity": fidelity}


def _safe_sa(ctx):
    try:
        return G.slope_area_relation(ctx=ctx)
    except ValueError:
        return None


def sweep_bake(args) -> dict:
    """Amplify a real 30 m window to 1.875 m with the real bake, and measure it."""
    from terrain_service.bake.pipeline import (
        BakeGeometry, CONSTANTS, bake_padded_domain, load_kernels,
    )

    # A CI-sized geometry: 128 coarse px of tile plus the production 32 px apron is a
    # 192 px padded coarse domain, i.e. 3072^2 fine cells at 1.875 m. The apron is the
    # production one because the whole point is to measure what the shipped bake makes.
    geom = BakeGeometry(coarse_tile_px=args.bake_coarse, coarse_pixel_m=30.0,
                        scale=16, apron_coarse_px=32)
    n = geom.padded_coarse_px
    win = {w.case: w for w in MANIFEST}[args.bake_case]
    z30, cell30 = fetch_window(win, max(args.size, n + 8), args.cache)
    coarse = np.ascontiguousarray(z30[:n, :n], dtype=np.float32)
    print(f"  baking {n}x{n} coarse -> {geom.padded_fine_px}^2 at "
          f"{geom.fine_pixel_m} m ...", flush=True)
    out = bake_padded_domain(coarse, world_seed=20260729, tile_x=0, tile_y=0,
                             kernels=load_kernels(), geom=geom, consts=CONSTANTS)
    sl = geom.interior()
    fine = geom.fine_pixel_m
    fields = {
        "coarse_input_30m": (coarse[32:-32, 32:-32].astype(np.float64), 30.0),
        "B0B1_carrier_rough": (np.asarray(out["carrier_plus_roughness"])[sl, sl]
                               .astype(np.float64), fine),
        "B3_baked": (np.asarray(out["z"])[sl, sl].astype(np.float64), fine),
    }
    ref = fields["B3_baked"][0]
    fields["fbm_at_1p875"] = (
        G.fbm(ref.shape, fine, hurst=0.75, seed=5, rms_m=float(ref.std())), fine)
    fields["surrogate_B3"] = (
        G.spectrum_matched_surrogate(ref, fine, seed=6), fine)

    cases, objs = {}, {}
    for name, (z, c) in fields.items():
        if name == "coarse_input_30m":
            continue  # different cell size: reported separately, never in the table
        print(f"  measuring {name} ...", flush=True)
        cases[name] = R.describe(z, c, search_m=args.search_m * fine / 30.0)
        ctx = G.flow_context(z, c)
        objs[name] = {"slope_area": _safe_sa(ctx), "variogram": G.variogram(z, c),
                      "hypsometry": G.hypsometry(z, c)}
    coarse_case = R.describe(*fields["coarse_input_30m"], search_m=args.search_m)
    return {"cases": cases, "objs": objs, "fields": fields,
            "coarse_case": coarse_case, "cell_m": fine,
            "interior_dead_ends": int(out["interior_dead_ends"])}


# --------------------------------------------------------------------------- output
def _tier_lines(name: str, vg) -> list:
    rows = G.tier_continuity(vg)
    if not rows:
        return [f"- `{name}`: variogram spans {vg.lag_m.min():.2f}-{vg.lag_m.max():.0f} m; "
                "no tier boundary falls strictly inside it."]
    out = []
    for r in rows:
        flag = " **KINK**" if r["kink"] else ""
        imp = " **H>1 (impossible)**" if r["impossible"] else ""
        out.append(
            f"- `{name}` at {r['boundary_m']} m: H below = {r['h_below']:.3f}, "
            f"H above = {r['h_above']:.3f}, ΔH = {r['delta_h']:+.3f}{flag}{imp}")
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    default_cache = os.environ.get("GEOMORPH_CACHE") or os.path.join(
        os.path.expanduser("~"), ".cache", "voxelsim-geomorph")
    ap.add_argument("--sweep", default="earth",
                    choices=("earth", "bake", "all"))
    ap.add_argument("--source", default="copernicus", choices=("copernicus", "etopo"))
    ap.add_argument("--size", type=int, default=1024, help="window edge, cells")
    ap.add_argument("--search-m", type=float, default=300.0,
                    help="geomorphon lookout distance at 30 m")
    ap.add_argument("--cache", default=default_cache)
    ap.add_argument("--out", default=None, help="directory for plots and json")
    ap.add_argument("--markdown", default=None, help="write the report here")
    ap.add_argument("--replicates", action="store_true",
                    help="also measure each field's four quadrants, for the "
                         "within-class noise column of the separation table")
    ap.add_argument("--bake-case", default="alpine")
    ap.add_argument("--bake-coarse", type=int, default=128)
    ap.add_argument("--no-plots", action="store_true")
    args = ap.parse_args(argv)

    os.makedirs(args.cache, exist_ok=True)
    out_dir = args.out or os.path.join(args.cache, "out")
    os.makedirs(out_dir, exist_ok=True)

    md: list = [CONCLUSIONS] if args.sweep == "all" else []
    payload: dict = {}

    if args.sweep in ("earth", "all"):
        print("== earth sweep ==", flush=True)
        e = sweep_earth(args)
        payload["earth"] = {k: _jsonable(v) for k, v in e["cases"].items()}
        md += ["## Sweep 1 -- real Earth vs synthetic, all at "
               f"{e['cell_m']:.2f} m ({args.size}x{args.size} windows)", ""]
        md += [w.case.ljust(18) + " -- " + w.note for w in MANIFEST]
        md += ["", R.discrimination_table(e["cases"]), ""]
        md += ["", R.paired_contrast_table(
            R.paired_contrast(e["cases"],
                              [("alpine", "surrogate_alpine"),
                               ("fluvial_upland", "surrogate_fluvial")],
                              e["replicates"]),
            title="Question 1 -- does the metric see through a spectrum-matched fake?"),
            "",
            "Each fake has the same variogram as the real field beside it (see the "
            "fidelity table below), so anything that separates them is seeing "
            "structure the power spectrum does not contain. `worst fold` is the "
            "fractional gap on the *worse* of the two pairs; `worst gap/noise` divides "
            "that gap by the within-scene spread of the metric.", ""]
        if args.replicates:
            real_names = [w.case for w in MANIFEST]
            md += ["", R.separation_table(
                R.separation(e["cases"], e["replicates"], subset=real_names),
                title="Question 2 -- does the metric separate the five real terrain "
                      "classes? (within-class noise = the four quadrants of each "
                      "scene)"), ""]

        md += ["", "### Kink tolerance, calibrated", "",
               "`variogram.tier_continuity` flags a step in the local Hurst exponent "
               "as a tier-bookkeeping bug. These scenes have no tier boundary, so the "
               "change in local H across a lag in the middle of their range is the "
               "natural drift the tolerance has to clear:", ""]
        for name, o in e["objs"].items():
            vg = o["variogram"]
            mid = float(np.sqrt(vg.lag_m.min() * vg.lag_m.max()))
            rows = G.tier_continuity(vg, boundaries_m=(mid,), kink_tol=99.0)
            if rows:
                md.append(f"- `{name}`: ΔH = {rows[0]['delta_h']:+.3f} across "
                          f"{mid:.0f} m")
        md += ["### Is the surrogate a fair control?", "",
               "Ratio of the surrogate's semivariance to the original's, over every "
               "measured lag. A fair control sits near 1: it must be as rough as the "
               "terrain it is standing in for, or the metrics separate it for the "
               "wrong reason.", "",
               "| field | surrogate | min | median | max |",
               "|---|---|---|---|---|"]
        for real, surr, lo, mid, hi in e["fidelity"]:
            md.append(f"| {real} | {surr} | {lo:.2f} | {mid:.2f} | {hi:.2f} |")
        md += ["", "### Tier continuity (variogram)", ""]
        for name, o in e["objs"].items():
            md += _tier_lines(name, o["variogram"])
        md += [""]
        if not args.no_plots:
            _plots(e, out_dir, "earth")

    if args.sweep in ("bake", "all"):
        print("== bake sweep ==", flush=True)
        b = sweep_bake(args)
        payload["bake"] = {k: _jsonable(v) for k, v in b["cases"].items()}
        payload["bake"]["_coarse_input_30m"] = _jsonable(b["coarse_case"])
        md += [f"## Sweep 2 -- the real bake, at {b['cell_m']} m", "",
               f"Interior dead ends after routing: {b['interior_dead_ends']} "
               "(must be 0).", "",
               R.discrimination_table(b["cases"]), "",
               "The 30 m input window is measured too, but is reported here and not in "
               "the table above, because it is at a different cell size and the two "
               "are not comparable:", "",
               "```", json.dumps(_scalars(b["coarse_case"]), indent=2), "```", "",
               "### Tier continuity across the 30 m boundary", ""]
        for name, o in b["objs"].items():
            md += _tier_lines(name, o["variogram"])
        md += [""]
        if not args.no_plots:
            _plots(b, out_dir, "bake")

    text = "\n".join(md)
    print()
    print(text)
    if args.markdown:
        with open(args.markdown, "w", encoding="utf-8") as fh:
            fh.write(text + "\n")
        print(f"\n[wrote {args.markdown}]")
    with open(os.path.join(out_dir, "geomorph_validate.json"), "w",
              encoding="utf-8") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True)
    return 0


def _plots(sweep: dict, out_dir: str, tag: str) -> None:
    sa = {k: v["slope_area"] for k, v in sweep["objs"].items() if v["slope_area"]}
    if sa:
        R.plot_slope_area(sa, os.path.join(out_dir, f"{tag}_slope_area.png"),
                          title=f"slope-area ({tag})")
    R.plot_variogram({k: v["variogram"] for k, v in sweep["objs"].items()},
                     os.path.join(out_dir, f"{tag}_variogram.png"),
                     title=f"variogram ({tag})")
    R.plot_hypsometry({k: v["hypsometry"] for k, v in sweep["objs"].items()},
                      os.path.join(out_dir, f"{tag}_hypsometry.png"),
                      title=f"hypsometry ({tag})")


def _scalars(d: dict) -> dict:
    return {k: (float(v) if isinstance(v, (int, float, np.floating, np.integer))
                and not isinstance(v, bool) else v)
            for k, v in d.items()
            if isinstance(v, (int, float, bool, np.floating, np.integer))}


def _jsonable(d):
    out = {}
    for k, v in d.items():
        if isinstance(v, (np.floating, np.integer)):
            v = v.item()
        if isinstance(v, (int, float, bool, str)) or v is None:
            out[k] = v
        elif isinstance(v, list):
            out[k] = v
    return out


if __name__ == "__main__":
    raise SystemExit(main())
