#!/usr/bin/env python3
"""Author the coarse conditioning rasters terrain-diffusion generates from.

WHY THIS EXISTS. The model is always conditioned on a 5-channel coarse sketch
(elevation, temperature, temp seasonality, precipitation, precip CV). By default
that sketch comes from `synthetic_map.py`: Perlin FBm quantile-matched to
Earth's histogram. Two consequences, both measured (docs/worldgen-levers.md):

  * Perlin FBm is isotropic, so every world is an archipelago. Inland reach
    never exceeded 92 km across four seeds. A seed picks a realization, not a
    process.
  * Precipitation is an INDEPENDENT Perlin field, never touched by elevation or
    by distance from ocean. There is no orographic rainfall, no rain shadow and
    no continentality, so DESERTS CANNOT FORM AT ANY LANDMASS SCALE -- a
    315,000 km2 continent generated by tuning frequency_mult alone still
    classified DESERT 0.0%.

This tool writes the sketch instead, with the causal structure the default
generator omits. It does not touch the model: `tiff-export` feeds these rasters
through the same pipeline, and `--snr` decides how literally they are obeyed.

WHAT IT MODELS, and why each one is here rather than left to the diffusion:

  * CONTINENTS as seeded blobs joined by linear ranges. Perlin cannot make a
    long feature; plate boundaries are long, and that is most of why Earth does
    not look like this model's default output.
  * CONTINENTALITY. Precipitation decays with distance from open water, because
    moisture comes off the ocean and is spent crossing land. THIS is what makes
    a dry interior, and it is the single reason this tool exists.
  * OROGRAPHIC RAIN SHADOW. Terrain rising against the prevailing wind wrings
    out moisture; the lee side is dry. Computed by marching the wind vector
    across the elevation field and accumulating lift.
  * LATITUDE. Temperature falls toward the poles; precipitation peaks near the
    equator and in the mid-latitude storm belt, with subtropical dry zones near
    +/-25 degrees -- which is where Earth's deserts actually are.
  * LAPSE RATE. Temperature falls ~6.5 C/km with elevation, matching biome.h's
    treeline derivation.

NOT A SIMULATION. This is a plausible-looking sketch at 7.68 km per cell, whose
only job is to give the diffusion model a large-scale layout worth refining.
Every constant below is a designer-facing dial, not a physical claim.

KNOWN LIMITATION, stated because the preview makes it obvious: the mountain
ranges still read as drawn ribbons rather than as orogens, even with a wandering
ridge line and along-strike width/height variation. Chasing that further here
would be misplaced effort. The elevation channel's default `cond_snr` is 0.3 --
deliberately loose -- so the model is free to substantially reinterpret this
geometry, and it is far better at mountains than a dozen lines of numpy is. What
this file must get right is the LARGE-SCALE LAYOUT and, above all, the climate
fields, because those are the parts the model cannot infer. Raise `--snr` on
channel 0 only if you want your drawn shapes obeyed literally.

THE NATURAL-LANGUAGE SEAM. Every knob is a named scalar in WorldSpec. Mapping
"a big temperate continent with a dry interior and a wet west coast" onto that
struct is a small, well-posed translation job -- and it is the ONLY part of the
NL-to-world path that needs a language model. Everything downstream is this file
plus terrain-diffusion. Keep the spec small and human-meaningful for that reason.

Usage:
    python tools/make_conditioning.py --out cond/ --continents 2 --arid-interior
    python tools/make_conditioning.py --out cond/ --spec myworld.json
    python tools/make_conditioning.py --out cond/ --preview preview.png

Then hand the directory to terrain-diffusion:
    python -m terrain_diffusion <checkpoint> tiff-export cond/ out.tif \\
        --snr 0.2,0.2,1.0,0.2,1.0
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np

#: One conditioning cell is one coarse cell: 256 fine pixels x 30 m.
CELL_KM = 256 * 30 / 1000.0


@dataclass
class WorldSpec:
    """Everything that decides the world. The natural-language target."""

    # --- shape -------------------------------------------------------------
    cells: int = 160                    # square grid; 160 -> ~1229 km across
    seed: int = 20260719
    continents: int = 2                 # major landmasses
    land_fraction: float = 0.38         # target, hit by choosing the sea level
    roughness: float = 0.55             # 0 = smooth blobs, 1 = ragged coastlines
    #: Mountain ranges are drawn along the lines JOINING continent seeds -- a
    #: crude stand-in for plate collision, and the one feature Perlin cannot
    #: produce. 0 disables them.
    range_height_m: float = 3200.0
    range_width_km: float = 90.0
    #: How far the ridge line wanders off the straight path between its
    #: anchors. 0 gives a capsule, which is what a straight segment with a
    #: gaussian falloff looks like and is unmistakably artificial.
    range_wander: float = 0.55
    abyss_depth_m: float = 5000.0

    # --- climate -----------------------------------------------------------
    #: Mean temperature at the map's centre latitude, before lapse rate.
    base_temp_c: float = 12.0
    #: How much colder the poleward edge is than the equatorward edge.
    lat_temp_drop_c: float = 26.0
    #: Rain at the coast, before continentality and orography.
    coastal_precip_mm: float = 1400.0
    #: e-folding distance for the continentality decay. THE desert knob:
    #: smaller = drier interiors. 350 km puts a 1200 km continent's centre at
    #: about 18% of its coastal rainfall.
    continentality_km: float = 350.0
    #: Prevailing wind, degrees clockwise from north (270 = westerlies).
    wind_from_deg: float = 270.0
    #: How hard the rain shadow bites, 0 disables orography.
    orographic_strength: float = 1.0
    #: Floor, so nowhere is bone dry unless you ask for it.
    min_precip_mm: float = 40.0

    def describe(self) -> str:
        return (f"{self.cells}x{self.cells} cells ({self.cells * CELL_KM:.0f} km), "
                f"{self.continents} continent(s), land {self.land_fraction:.0%}, "
                f"coastal rain {self.coastal_precip_mm:.0f} mm/yr decaying over "
                f"{self.continentality_km:.0f} km")


# ---------------------------------------------------------------------------
# helpers (numpy only)
# ---------------------------------------------------------------------------

def _fbm(rng: np.random.Generator, n: int, octaves: int = 6) -> np.ndarray:
    """Fractal value noise in [-1, 1]. Not Perlin, and it does not need to be --
    this only breaks up shapes that are otherwise too geometric."""
    out = np.zeros((n, n))
    amp, total = 1.0, 0.0
    for o in range(octaves):
        size = max(2, int(4 * 2 ** o))
        grid = rng.random((size, size)) * 2 - 1
        yi = np.linspace(0, size - 1, n)
        xi = np.linspace(0, size - 1, n)
        y0 = np.clip(yi.astype(int), 0, size - 2)
        x0 = np.clip(xi.astype(int), 0, size - 2)
        fy = (yi - y0)[:, None]
        fx = (xi - x0)[None, :]
        fy = fy * fy * (3 - 2 * fy)          # smoothstep
        fx = fx * fx * (3 - 2 * fx)
        g = grid[np.ix_(y0, x0)]
        gx = grid[np.ix_(y0, x0 + 1)]
        gy = grid[np.ix_(y0 + 1, x0)]
        gxy = grid[np.ix_(y0 + 1, x0 + 1)]
        out += amp * ((g * (1 - fx) + gx * fx) * (1 - fy) + (gy * (1 - fx) + gxy * fx) * fy)
        total += amp
        amp *= 0.5
    return out / total


def _distance_to(mask: np.ndarray, cell_km: float) -> np.ndarray:
    """Distance in km from every cell to the nearest True cell, by dilation.

    Same construction as world_map.py's inland_reach_km, which is already
    trusted. A two-pass chamfer was tried first and leaked its INF sentinel into
    cells the sweep never reached, which silently zeroed every rainfall term
    downstream (exp(-1e9/260) == 0) and made the whole continent desert. The
    dilation cannot do that: a cell either gets a real step count or the loop
    has provably converged.

    Grids here are a few hundred cells square, so the naive version is fast
    enough and cannot be wrong in that way.
    """
    if not mask.any():
        # No ocean at all: everything is maximally inland. Saturate rather than
        # divide by nothing.
        return np.full(mask.shape, max(mask.shape) * cell_km, dtype=np.float64)
    dist = np.zeros(mask.shape, dtype=np.float64)
    frontier = mask.copy()
    for step in range(1, mask.shape[0] + mask.shape[1] + 2):
        grown = frontier.copy()
        grown[1:, :] |= frontier[:-1, :]
        grown[:-1, :] |= frontier[1:, :]
        grown[:, 1:] |= frontier[:, :-1]
        grown[:, :-1] |= frontier[:, 1:]
        newly = grown & ~frontier
        if not newly.any():
            break
        dist[newly] = step
        frontier = grown
    return dist * cell_km


def _polyline_distance(n: int, pts) -> np.ndarray:
    """Distance in cells from every point to a polyline through `pts`."""
    yy, xx = np.mgrid[0:n, 0:n]
    best = np.full((n, n), float(n * 2))
    for (ay, ax), (by, bx) in zip(pts[:-1], pts[1:]):
        vy, vx = by - ay, bx - ax
        L2 = vy * vy + vx * vx
        if L2 == 0:
            d = np.hypot(yy - ay, xx - ax)
        else:
            t = np.clip(((yy - ay) * vy + (xx - ax) * vx) / L2, 0, 1)
            d = np.hypot(yy - (ay + t * vy), xx - (ax + t * vx))
        best = np.minimum(best, d)
    return best


def _wandering_ridge(rng, n: int, a, b, wander: float):
    """A perturbed polyline from a to b.

    A straight segment with a gaussian falloff reads as a capsule, not a
    mountain range -- it was the most obviously fake thing in the first version
    of this tool. Displacing the interior control points perpendicular to the
    line, midpoint-displacement style, gets a ridge that bends and forks the way
    a real orogen does, for about ten lines.
    """
    steps = 12
    ay, ax = a
    by, bx = b
    vy, vx = by - ay, bx - ax
    L = max(1e-6, math.hypot(vy, vx))
    py, px = -vx / L, vy / L                    # unit perpendicular
    pts = []
    for i in range(steps + 1):
        t = i / steps
        # Zero displacement at the ends so the ridge still joins its anchors.
        env = math.sin(math.pi * t)
        off = (rng.random() * 2 - 1) * wander * L * 0.25 * env
        pts.append((ay + vy * t + py * off, ax + vx * t + px * off))
    return pts


# ---------------------------------------------------------------------------
# the channels
# ---------------------------------------------------------------------------

def build_elevation(spec: WorldSpec) -> np.ndarray:
    rng = np.random.default_rng(spec.seed)
    n = spec.cells

    # Continent seeds, kept away from the border so coastlines are not clipped.
    margin = n // 6
    seeds = [(int(rng.integers(margin, n - margin)), int(rng.integers(margin, n - margin)))
             for _ in range(max(1, spec.continents))]

    # Broad landmass field: a smooth bump per seed, plus noise for ragged edges.
    field = np.zeros((n, n))
    radius = n / (1.7 * math.sqrt(max(1, spec.continents)))
    yy, xx = np.mgrid[0:n, 0:n]
    for (sy, sx) in seeds:
        r = np.hypot(yy - sy, xx - sx) / radius
        field += np.exp(-r * r)
    field += spec.roughness * 0.8 * _fbm(rng, n)

    # MOUNTAIN RANGES along the lines joining seeds. Long linear features are
    # what a noise field cannot produce and what makes terrain read as tectonic
    # rather than as blobs; they are also what casts the rain shadow below.
    ranges = np.zeros((n, n))
    if spec.range_height_m > 0 and len(seeds) >= 1:
        if len(seeds) > 1:
            pairs = [(seeds[i], seeds[(i + 1) % len(seeds)]) for i in range(len(seeds))]
        else:
            # One continent still gets a range: run it across the landmass on a
            # random bearing rather than a fixed diagonal.
            ang = rng.random() * math.pi
            r = n * 0.34
            cy, cx = seeds[0]
            pairs = [((cy - r * math.cos(ang), cx - r * math.sin(ang)),
                      (cy + r * math.cos(ang), cx + r * math.sin(ang)))]
        w_cells = max(1.0, spec.range_width_km / CELL_KM)
        # Width varies along strike as well as height. With a constant width the
        # result is a uniform ribbon -- recognisably a drawn curve rather than an
        # orogen, even after the ridge line itself is made to wander.
        wmod = 0.55 + 0.9 * np.clip(_fbm(rng, n, octaves=3) * 0.5 + 0.5, 0, 1)
        for a, b in pairs:
            d = _polyline_distance(n, _wandering_ridge(rng, n, a, b, spec.range_wander))
            ranges = np.maximum(ranges, np.exp(-(d / (w_cells * wmod)) ** 2))
        # Along-strike height variation, so the crest rises and falls into
        # distinct massifs instead of holding one height for its whole length.
        ranges *= 0.45 + 0.85 * np.clip(_fbm(rng, n, octaves=4) * 0.5 + 0.5, 0, 1)

    # Sea level chosen to hit the requested land fraction exactly, which is far
    # more predictable for a designer than tuning an offset by hand.
    thresh = np.quantile(field, 1.0 - spec.land_fraction)
    land = field > thresh
    span = max(1e-6, field.max() - thresh)
    above = np.clip((field - thresh) / span, 0, 1)

    # Interior relief. Without this the continent is a featureless ramp from
    # coast to 900 m, which reads as a mudflat once the diffusion refines it.
    # Two extra octave bands, both damped near the coast so the shoreline stays
    # where land_fraction put it.
    hills = (0.6 * _fbm(rng, n, octaves=5) + 0.4 * _fbm(rng, n, octaves=7))
    relief = np.clip(hills * 0.5 + 0.5, 0, 1) * 700.0 * np.clip(above * 2.2, 0, 1)

    elev = np.where(
        land,
        above * 700.0 + relief + ranges * spec.range_height_m,
        -np.clip((thresh - field) / max(1e-6, thresh - field.min()), 0, 1) * spec.abyss_depth_m,
    )
    return elev.astype(np.float32)


def build_climate(spec: WorldSpec, elev: np.ndarray):
    n = spec.cells
    land = elev > 0

    # Continentality: km to the nearest ocean cell. The whole point.
    dist_km = _distance_to(~land, CELL_KM)
    dist_km[~land] = 0.0

    # Latitude, mapped onto the grid's rows. Row 0 is the poleward edge.
    lat_t = np.linspace(1.0, 0.0, n)[:, None] * np.ones((1, n))   # 1 = pole
    latitude_deg = 55.0 - 60.0 * lat_t                            # ~-5..55 N

    # --- temperature -------------------------------------------------------
    temp = spec.base_temp_c + (0.5 - lat_t) * spec.lat_temp_drop_c
    temp = temp - 6.5 * np.maximum(0.0, elev) / 1000.0            # lapse rate
    # Continental interiors swing further from the maritime mean, which is what
    # bio_4 measures; the mean itself barely moves, so only seasonality uses it.
    contin = 1.0 - np.exp(-dist_km / max(1e-6, spec.continentality_km))

    # --- precipitation -----------------------------------------------------
    # Latitude belt: wet near the equator and in the mid-latitude storm track,
    # dry in the subtropics around 25 degrees -- Earth's actual desert band.
    band = (0.55 + 0.45 * np.cos(np.radians(latitude_deg) * 2.2)
            - 0.55 * np.exp(-((np.abs(latitude_deg) - 25.0) / 9.0) ** 2))
    band = np.clip(band, 0.12, 1.35)

    precip = spec.coastal_precip_mm * band
    precip = precip * np.exp(-dist_km / max(1e-6, spec.continentality_km))

    if spec.orographic_strength > 0:
        precip = precip * _orographic(spec, elev)

    precip = np.maximum(precip, spec.min_precip_mm)
    precip = np.where(land, precip, spec.coastal_precip_mm * band)  # ocean stays wet

    # bio_4: sd(monthly) x100. Maritime ~400, strongly continental ~2000.
    seasonality = 350.0 + 1500.0 * contin + 6.0 * np.maximum(0.0, -temp)
    # bio_15: rainfall is peakier where it is scarcer.
    precip_cv = np.clip(35.0 + 90.0 * (1.0 - precip / max(1.0, spec.coastal_precip_mm)), 20.0, 150.0)

    return (temp.astype(np.float32), seasonality.astype(np.float32),
            precip.astype(np.float32), precip_cv.astype(np.float32), dist_km)


def _orographic(spec: WorldSpec, elev: np.ndarray) -> np.ndarray:
    """Rain-shadow multiplier: wet where the wind climbs, dry in the lee.

    March a parcel downwind, tracking the highest ground it has crossed. Rising
    against that maximum wrings moisture out (windward gets a boost); once past
    the crest the parcel is spent, and stays spent until it reaches sea again.
    Crude, one-pass, and enough to put a desert behind a mountain range -- which
    is the entire ask.
    """
    n = elev.shape[0]
    th = math.radians(spec.wind_from_deg)
    dy, dx = -math.cos(th), -math.sin(th)     # direction the wind blows TOWARD
    steps = int(n * 1.2)
    crest = np.zeros_like(elev)
    yy, xx = np.mgrid[0:n, 0:n].astype(np.float64)
    for s in range(1, steps):
        sy = np.clip((yy - dy * s).astype(int), 0, n - 1)
        sx = np.clip((xx - dx * s).astype(int), 0, n - 1)
        upwind = elev[sy, sx]
        # Ocean upwind resets the parcel: it has picked up moisture again.
        crest = np.where(upwind <= 0, 0.0, np.maximum(crest, upwind))
    lee = np.clip((crest - np.maximum(elev, 0)) / 1500.0, 0, 1)
    windward = np.clip((np.maximum(elev, 0) - crest) / 1200.0, 0, 1)
    k = spec.orographic_strength
    return np.clip(1.0 + 0.5 * k * windward - 0.75 * k * lee, 0.12, 1.8)


# ---------------------------------------------------------------------------

def write_tiffs(out: Path, spec: WorldSpec, chans: dict) -> None:
    try:
        import rasterio
        from rasterio.transform import from_bounds
    except ImportError:
        sys.exit("rasterio is required to write GeoTIFFs "
                 "(present in terrain-diffusion's venv)")

    out.mkdir(parents=True, exist_ok=True)
    n = spec.cells
    # A plate carree box sized so one cell is CELL_KM across at the equator.
    # tiff_export only needs a consistent CRS/transform across the five files;
    # it works in cells, not in ground units.
    deg = n * CELL_KM / 111.32
    transform = from_bounds(-deg / 2, -deg / 2, deg / 2, deg / 2, n, n)

    for name, arr in chans.items():
        path = out / name
        with rasterio.open(path, "w", driver="GTiff", height=n, width=n, count=1,
                           dtype="float32", crs="EPSG:4326", transform=transform,
                           compress="lzw") as dst:
            dst.write(arr.astype(np.float32), 1)
        print(f"  wrote {path.name:24s} {float(arr.min()):9.1f} .. {float(arr.max()):9.1f}")


def preview(path: Path, spec: WorldSpec, elev, temp, precip, dist_km) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(1, 4, figsize=(20, 5.4), dpi=110)
    land = elev > 0
    # Ocean drawn first in its own ramp, land over it -- sharing one ramp made
    # the shoreline invisible in the first version.
    ax[0].imshow(np.where(land, np.nan, elev), cmap="Blues_r", vmin=-6000, vmax=0)
    a = ax[0].imshow(np.where(land, elev, np.nan), cmap="terrain", vmin=0,
                     vmax=max(1.0, float(np.nanmax(np.where(land, elev, np.nan)))))
    ax[0].contour(np.where(land, 1.0, 0.0), levels=[0.5], colors="k", linewidths=0.8)
    ax[0].set_title(f"elevation  ({elev.min():.0f} .. {elev.max():.0f} m)")
    plt.colorbar(a, ax=ax[0], fraction=0.046)
    for i, (arr, name, cmap) in enumerate([
            (np.where(land, dist_km, np.nan), "km from ocean (continentality)", "magma"),
            (np.where(land, precip, np.nan), "precipitation mm/yr", "YlGnBu"),
            (np.where(land, temp, np.nan), "temperature C", "RdYlBu_r")], start=1):
        im = ax[i].imshow(arr, cmap=cmap)
        ax[i].set_title(name)
        plt.colorbar(im, ax=ax[i], fraction=0.046)
    for a_ in ax:
        a_.set_xticks([])
        a_.set_yticks([])
    fig.suptitle(spec.describe(), fontsize=10)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    print(f"  wrote {path}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True, help="directory for the 5 GeoTIFFs")
    ap.add_argument("--spec", help="JSON file of WorldSpec fields (overrides flags)")
    ap.add_argument("--seed", type=int)
    ap.add_argument("--cells", type=int)
    ap.add_argument("--continents", type=int)
    ap.add_argument("--land-fraction", type=float)
    ap.add_argument("--continentality-km", type=float,
                    help="e-folding distance for the rain decay; THE desert knob")
    ap.add_argument("--coastal-precip-mm", type=float)
    ap.add_argument("--base-temp-c", type=float)
    ap.add_argument("--wind-from-deg", type=float)
    ap.add_argument("--arid-interior", action="store_true",
                    help="shorthand: one big continent, sharp rain decay")
    ap.add_argument("--preview", help="also write a 4-panel PNG here")
    ap.add_argument("--dump-spec", help="write the resolved spec as JSON")
    args = ap.parse_args()

    spec = WorldSpec()
    if args.spec:
        spec = WorldSpec(**{**asdict(spec), **json.loads(Path(args.spec).read_text())})
    if args.arid_interior:
        spec.continents = 1
        spec.land_fraction = 0.5
        spec.continentality_km = 260.0
        spec.cells = max(spec.cells, 200)
    for f in ("seed", "cells", "continents", "land_fraction", "continentality_km",
              "coastal_precip_mm", "base_temp_c", "wind_from_deg"):
        v = getattr(args, f, None)
        if v is not None:
            setattr(spec, f, v)

    print(spec.describe())
    elev = build_elevation(spec)
    temp, seasonality, precip, precip_cv, dist_km = build_climate(spec, elev)

    land = elev > 0
    print(f"  land {land.mean():.1%}, inland reach {dist_km.max():.0f} km, "
          f"land rain {np.percentile(precip[land], 5):.0f}..{np.percentile(precip[land], 95):.0f} mm/yr")
    arid = (precip[land] < 400).mean() if land.any() else 0.0
    print(f"  land below 400 mm/yr (arid): {arid:.1%}")

    write_tiffs(Path(args.out), spec, {
        "heightmap.tif": elev,
        "temperature.tif": temp,
        "temperature_std.tif": seasonality,
        "precipitation.tif": precip,
        "precipitation_cv.tif": precip_cv,
    })
    if args.dump_spec:
        Path(args.dump_spec).write_text(json.dumps(asdict(spec), indent=2))
        print(f"  wrote {args.dump_spec}")
    if args.preview:
        preview(Path(args.preview), spec, elev, temp, precip, dist_km)


if __name__ == "__main__":
    main()
